TouK/nussknacker

- engine/example/src/main/java/pl/touk/nussknacker/engine/javaexample/ExampleProcessConfigCreator.java
- engine/example/src/main/scala/pl/touk/nussknacker/engine/example/ExampleProcessConfigCreator.scala
- engine/flink/management/java_sample/src/main/scala/pl/touk/nussknacker/engine/management/javasample/Objects.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DemoProcessConfigCreator.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/KeyValueTestHelper.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkProcessMainSpec.scala
- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/exception/DefaultEspExceptionHandler.scala
- engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/deployment/DeploymentServiceSpec.scala
> Use VerboselyLoggingRestartingExceptionHandler for ExampleProcessConfigCreator

- README.md
Added info about mailing list in readme
> Mailing list

- .travis.yml
Hopefully this will speed up travis build...
> Add cache to travis build

- engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/FlinkProcessRegistrar.scala
Impact can be seen only in performance tests...
> [FIX] output tag TypeInformation is created only once

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/AvroSerializationSchemaFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/AvroUtils.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/encode/BestEffortAvroEncoder.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/encode/BestEffortAvroEncoderSpec.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/serialization/SerializationSchemaFactory.scala
In particular:
- don't use exception to control flow
- make UUID as key optional
> [FIX] performance improvements in BestEfforAvroEncoder, minor fixes in avro serialization

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
Revert previous behavior of subprocess compilation when node is disabled as we don't have type information in this case.
> Fix disabled subprocess compilation

- demo/docker/docker-compose.yml
- demo/docker/elasticsearch/config/elasticsearch.yml
- demo/docker/grafana/runWithFlinkEspBoard.sh
- demo/docker/kibana/config/kibana.yml
- demo/docker/logstash/pipeline/logstash.conf
- Update base version zookeeper to 3.5.5
- Fix bug with docker compose: kibana / grafana
> Fixes: for issue 49

- demo/docker/testQuickstart.sh
- ui/client/common/JsonUtils.js
- ui/client/components/UserLeftPanel.js
- ui/client/containers/Processes.js
- ui/client/containers/SubProcesses.js
Fix bugs: 
- search subprocesses, 
- run service
- missing arrows. 
Updates:
- Add docker-compose tests for flink, kibana, grafana
> Fixes bugs and add upates part I 

- ui/client/common/VisualizationUrl.js
Nasty name overwrite. Makes it impossible to list services usage in admin tab.
> [Fix] Error on visualization url construction

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcess.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcessTest.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
1. on rewrite do not cut off disabled subprocess output
> [FIX] CanonicalProcess#withoutDsiabledNodes

- ui/client/components/graph/Graph.js
- ui/server/develConf/generic/application.conf
- ui/server/develConf/sample/application.conf
- Change max zoom at graph
- Fix devel backend app configs
> Fix: Zoom and backend app configs

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcess.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcessTest.scala
handle subprocess nodes recursively
> [FIX] CanonicalProcess#withoutDisabledNodes

- ui/client/common/ProcessUtils.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/containers/AdminPage.js
- ui/client/http/HttpService.js
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessObjectsFinder.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessObjectsFinderTest.scala
Change-Id: I821841168f562dd83a8554e0c9940d2bc3547683
> Feature component search

- ui/client/common/VisualizationUrl.js
- ui/client/containers/AdminPage.js
Change-Id: Id26c938c0d1a35331c11ea6036ef19fc17148799
> Fix invalid URL in component search

- ui/client/common/JsonUtils.js
- ui/client/components/graph/Graph.js
- ui/client/components/graph/NodeUtils.js
- ui/client/components/right-panel/UserRightPanel.js
- ui/client/containers/Visualization.js
- ui/client/reducers/graph.js
This PR allow to copy and paste single node between processes with <kbd>Ctrl+C</kbd> and <kbd>Ctrl+V</kbd>. For now groups cannot be copied and pasted but it seems doable.
At the beginning I wanted to use [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) and add buttons to copy and paste in the right panel but the API is not widely supported, especially by Firefox 67.
Below is a simple demo of this feature:
> Copy and paste arbitrary nodes between processes

- ui/client/common/VisualizationUrl.js
Change-Id: Id07f7ea9292e27cae9e2bbb93dcd2782d2d12f42
> Fix invalid URL in component search part 2

- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
Making processesDetails more RESTful by changing POST endpoint into GET.
> processesDetails GET endpoint

- .travis.yml
- ui/client/webpack.config.js
Move tests docker to docker release
> Improvement: Travies tests / releases

- ui/client/components/HealthCheck.js
- ui/client/components/PeriodicallyReloadingComponent.js
- ui/client/containers/Archive.js
- ui/client/containers/BaseProcesses.js
- ui/client/containers/CustomProcesses.js
- ui/client/containers/Processes.js
- ui/client/containers/SubProcesses.js
- ui/client/http/Settings.js
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/webpack.config.js
- ui/server/develConf/sample/application.conf
- ui/server/src/main/resources/defaultConfig.conf
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfig.scala
- ui/server/src/test/resources/application.conf
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/SettingsResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
* Fix interval reloading data
* Retrive interval configuration from back-end
> Feature: intervals improvement

- ui/client/common/ProcessDefinitionUtils.js
- ui/client/common/ProcessUtils.js
- ui/client/components/ToolBox.js
- ui/client/components/graph/Graph.js
- ui/client/components/graph/NodeUtils.js
- ui/client/test/NodeUtils-test.js
- ui/client/test/ProcessDefinitionUtils-test.js
Unknown nodes or available in other categories cannot be added to process.
> Add only nodes available from toolbox

- ui/client/components/graph/Graph.js
- ui/client/reducers/graph.js
> Move selected nodes

- ui/client/actions/actions.js
- ui/client/components/graph/Graph.js
- ui/client/components/graph/NodeUtils.js
- ui/client/reducers/graph.js
- ui/client/test/reducer-test.js
> Copy edges between selected nodes

- engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/FlinkProcessRegistrar.scala
> [FIX] Possible memory leak fix - SplitFunction as a class

- ui/client/actions/ActionsUtils.js
- ui/client/actions/notificationActions.js
- ui/client/components/graph/Graph.js
- ui/client/containers/Notifications.js
- ui/client/http/HttpService.js
- ui/client/index.js
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/reducers/index.js
* Replace notification system with redux wrapper.
* Notifications can be easily emitted from every component.
Demo:
> Notify number of copied elements and when trying to paste invalid nodes

- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/metrics/InstantRateMeter.scala
- engine/standalone/app/src/main/scala/pl/touk/nussknacker/engine/standalone/http/StandaloneHttpApp.scala
- engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala
- engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreterSpec.scala
- engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/deployment/DeploymentServiceSpec.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/StandaloneContext.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/metrics/MetricsProvider.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/metrics/WithEspTimers.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/metrics/dropwizard/DropwizardMetricsProvider.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/metrics/dropwizard/InstantRateMeter.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/metrics/dropwizard/StandaloneMetricsReporter.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/service/TimeMeasuringService.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/metrics/GenericInstantRateMeter.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/service/GenericTimeMeasuringService.scala
> [Refactor] standalone metrics setup is more independent of codahale metrics

- ui/server/develConf/sample/application.conf
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
Can be useful e.g. for some healthcheck requirements
> Can pass global buildInfo from config in app/buildInfo

- .travis.yml
… instead of target branch for better version naming and running coverall only on push to master
> travis: using source branch

- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/AvroSchemaSpelExpressionSpec.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Implicits.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionValidator.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
We leave frontend for different PR - it's tricky to do suggestions and language selection...
> Feature: can use template expressions - currently backend only

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/CustomStreamTransformer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/node.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/CustomNodeInvoker.scala
- engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala
- engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreterSpec.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/StandaloneSinkFactory.scala
This is first step to e.g. swagger generation for standalone
> Feature: standalone interpreter knows result types

- engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
- engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/Permission.scala
- engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/PermissionSyntax.scala
- engine/security-api/src/test/scala/pl/touk/nussknacker/ui/security/api/PermissionSyntaxTest.scala
- nussknacker-dist/src/universal/conf/docker-users.conf
- nussknacker-dist/src/universal/conf/users.conf
- ui/server/develConf/generic/users.conf
- ui/server/develConf/sample/users.conf
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AuthorizeProcessDirectives.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/security/BasicHttpAuthenticator.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/security/NussknackerInternalUser.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestPermissions.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparerSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/ProcessModelMigratorSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepositorySpec.scala
This PR closes #121 
- Remove Permission.Admin
- Add isAdmin property at user config file
- Add security for changing category, now this can do only admin
- Add some todos
- Some tests refactor
> Fix bug with permissions

- ui/client/components/graph/ExpressionSuggest.js
- ui/client/package-lock.json
- ui/client/package.json
> Turned on liveAutocompletion  + react-ace 7.0.2 -> 7.0.4

- build.sbt
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/CirceUtil.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/Displayable.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypeEncoders.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- engine/example/src/main/scala/pl/touk/nussknacker/engine/example/ExampleProcessConfigCreator.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/TestProcessConfigCreator.scala
- engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/FlinkProcessManagerSpec.scala
- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/sink/EmptySink.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- engine/standalone/api/src/main/scala/pl/touk/nussknacker/engine/standalone/api/ResponseEncoder.scala
- engine/standalone/app/src/main/scala/pl/touk/nussknacker/engine/standalone/http/ProcessRoute.scala
- engine/standalone/app/src/main/scala/pl/touk/nussknacker/engine/standalone/http/StandaloneRequestHandler.scala
- engine/standalone/app/src/test/scala/pl/touk/nussknacker/engine/standalone/http/TestConfigCreator.scala
- engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala
- engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/DefaultResponseEncoder.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/json/BestEffortJsonEncoder.scala
- engine/util/src/test/scala/pl/touk/nussknacker/engine/util/json/BestEffortJsonEncoderSpec.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
- new trait for displaying circe Json
- ResponseEncoder uses only circe (it's not widely used, so migration will be easier)
- BestEffortJsonEncoder uses circe
> Displayable, ResponseEncoder => Circe

- ui/client/components/modals/CompareVersionsDialog.js
- ui/server/src/main/scala/pl/touk/nussknacker/ui/util/ProcessComparator.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/util/ProcessComparatorSpec.scala
Currently compare functionality supports nodes and edges. This PR adds support for properties differences.
> Properties differences

- ui/client/app.styl
- ui/client/components/AddProcessDialog.js
- ui/client/components/CommentInput.js
- ui/client/components/ProcessComments.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/components/modals/CompareVersionsDialog.js
- ui/client/components/modals/GenerateTestDataDialog.js
- ui/client/containers/Processes.js
- ui/client/containers/SubProcesses.js
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/userPanel.styl
> Change comment section design, focus on first item in newly opened dialog, distinguish between read-only and other fields

- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
Currently subprocess is migrated as a process.
> Create subprocess when migrating one

- ui/client/components/graph/Graph.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/components/graph/NodeDetailsModal.js
- ui/client/stylesheets/graph.styl
Fixes:
- preview is not working in any browser,
- subprocess nodes' parameters are editable in the preview.
- user has to resize browser window to force preview to appear.
> Subprocess preview in Chromium

- ui/client/actions/actions.js
- ui/client/app.styl
- ui/client/assets/icons/InlinedSvgs.js
- ui/client/components/ProcessComments.js
- ui/client/components/ProcessHistory.js
- ui/client/components/RouteLeavingGuard.js
- ui/client/components/modals/ConfirmDialog.js
- ui/client/components/modals/GenericModalDialog.js
- ui/client/components/modals/PreventExitDialog.js
- ui/client/components/right-panel/UserRightPanel.js
- ui/client/containers/Visualization.js
- ui/client/reducers/ui.js
*This resolves #191 
*This resolves #180
> Erratic dialogs(#191), "align" in right menu(#180)

- ui/client/components/AddProcessDialog.js
- ui/client/components/Fields.js
- ui/client/components/graph/EdgeDetailsModal.js
- ui/client/components/graph/NodeDetailsModal.js
- ui/client/components/modals/CompareVersionsDialog.js
- ui/client/components/modals/ConfirmDialog.js
- ui/client/components/modals/GenericModalDialog.js
- ui/client/components/modals/PreventExitDialog.js
- ui/client/components/right-panel/UserRightPanel.js
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/stylesheets/graph.styl
This resolves #176 
This resolves #174 
This resolves #232
> Add movable modal dialogs

- ui/client/containers/Visualization.js
Currently capabilities are initialized in constructor and `fetchProcessDetails` is not immediately available. This results in capabilities not being properly refreshed once details are ready (processCategory is undefined initially) which then leads to `User.js` permission check failure.
> [FIX] Creator panel is not visible for non-admin users

- ui/client/components/Tips.js
- ui/client/components/graph/Graph.js
- ui/client/containers/AdminPage.js
- ui/client/containers/Archive.js
- ui/client/containers/EspApp.js
- ui/client/containers/Metrics.js
- ui/client/containers/Processes.js
- ui/client/containers/Search.js
- ui/client/containers/SubProcesses.js
- ui/client/containers/Visualization.js
- ui/client/package-lock.json
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/graph.styl
I've simplified the code and the probem is gone. Need react guru to look at this.
> fixes initial zoom issues after loading the graph

- ui/client/components/Tips.js
- ui/client/components/graph/Graph.js
- ui/client/containers/AdminPage.js
- ui/client/containers/Archive.js
- ui/client/containers/EspApp.js
- ui/client/containers/Metrics.js
- ui/client/containers/Processes.js
- ui/client/containers/Search.js
- ui/client/containers/SubProcesses.js
- ui/client/containers/Visualization.js
- ui/client/package-lock.json
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/graph.styl
> Revert "fixes initial zoom issues after loading the graph"

- .travis.yml
… cause unexpected package content on sonatype
> Fix for travis release stage for pull requests

- ui/client/app.styl
- ui/client/components/ProcessAttachments.js
- ui/client/components/ToolBox.js
- ui/client/stylesheets/_mixins.styl
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/toolBox.styl
This fixes #291
This fixes #287 
This fixes #289
This fixes #290
This fixes #292
This fixes #293
This fixes #288
> Ui improvements

- ui/client/common/Validators.js
- ui/client/components/Fields.js
- ui/client/components/Tips.js
- ui/client/components/graph/EdgeDetailsContent.js
- ui/client/components/graph/ExpressionSuggest.js
- ui/client/components/graph/ModalRenderUtils.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/components/graph/node-modal/BranchParameters.js
- ui/client/components/graph/node-modal/ExpressionInput.js
- ui/client/components/graph/node-modal/Fields.js
- ui/client/components/graph/node-modal/Input.js
- ui/client/components/graph/node-modal/MapVariable.js
- ui/client/components/graph/node-modal/Variable.js
- ui/client/components/modals/ValidationLabels.js
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/processes.styl
> Show params validation error in the context of params when possible

- ui/client/assets/img/arrows/arrow-left.svg
- ui/client/assets/img/arrows/arrow-right.svg
- ui/client/assets/img/buttons/zoomin.svg
- ui/client/assets/img/buttons/zoomout.svg
- ui/client/components/UserLeftPanel.js
- ui/client/components/graph/Graph.js
- ui/client/components/right-panel/UserRightPanel.js
- ui/client/containers/Visualization.js
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/togglePanel.styl
- ui/client/stylesheets/userPanel.styl
This resolves #296
This resolves #307
This resolves #188
> Change and move zoom in-out icons as well as arrow icons

- ui/client/components/graph/Graph.js
- ui/client/stylesheets/graph.styl
This fixes #284 
This fixes #275
> Fix initial zoom

- ui/client/components/Tips.js
- ui/client/containers/Visualization.js
This fixes #353 
This fixes #352
> Add error summary to upper-left panel and change cannot paste message

- ui/client/components/graph/ExpressionSuggest.js
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/processes.styl
- ui/client/stylesheets/userPanel.styl
> Restyling modal inputs

- ui/client/components/Fields.js
- ui/client/components/graph/EdgeDetailsContent.js
- ui/client/components/graph/EdgeDetailsModal.js
- ui/client/components/graph/ExpressionSuggest.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/components/graph/NodeDetailsModal.js
- ui/client/components/graph/node-modal/BranchParameters.js
- ui/client/components/graph/node-modal/ExpressionInput.js
- ui/client/components/graph/node-modal/Fields.js
- ui/client/components/graph/node-modal/Input.js
- ui/client/components/graph/node-modal/MapVariable.js
- ui/client/components/graph/node-modal/Variable.js
- ui/client/components/modals/CompareVersionsDialog.js
> Do not show validation errors in comparison modal

- ui/client/components/graph/EspNode.js
> Disabled node appearance improved

- ui/client/stylesheets/mainMenu.styl
> responsive menu

- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/CustomNodeProcessSpec.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- ui/client/common/graph/constants.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/components/graph/node-modal/Variable.js
Pass expression in field name in validation result, and display expression errors in scope of expression field
> [Issue 268] UI - better node expression validation result

- ui/client/app.styl
- ui/client/common/ProcessUtils.js
- ui/client/components/CommentContent.js
- ui/client/components/ProcessAttachments.js
- ui/client/components/ProcessComments.js
- ui/client/components/ProcessHistory.js
- ui/client/components/common/Date.js
- ui/client/components/graph/EspNode.js
- ui/client/components/graph/NodeDetailsModal.js
- ui/client/components/right-panel/UserRightPanel.js
- ui/client/containers/Archive.js
- ui/client/containers/Processes.js
- ui/client/containers/SubProcesses.js
- ui/client/containers/admin/CustomProcesses.js
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/userPanel.styl
This resolves #308 
This resolves #384
This resolves #385
This resolves #355
This resolves #331
This resolves #346
> Redesign attachment and comment sections

- .gitignore
- ui/client/.babelrc
- ui/client/.flowconfig
- ui/client/common/Validators.js
- ui/client/components/Fields.js
- ui/client/flow-typed/npm/lodash_v4.x.x.js
- ui/client/package-lock.json
- ui/client/package.json
1. Add init config
2. Type Validators.js
> JS static typing with Flow:

- ui/client/components/Fields.js
- ui/client/components/graph/EspNode.js
- ui/client/components/graph/NodeDetailsContent.js
- ui/client/components/graph/NodeDetailsModal.js
- ui/client/components/graph/markups/node.html
- ui/client/components/graph/node-modal/Fields.js
This fixes #395 
This fixes #394
This fixes disabled node opacity
> Fix edition when node/process read only

- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformer.scala
* fix UnionTransformer key type definition
* fix UnionTransformer results type
> Fix UnionTransformer

- ui/client/app.styl
- ui/client/components/ProcessAttachments.js
- ui/client/components/graph/NodeDetailsModal.js
- ui/client/components/table/TableSelect.js
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/main.styl
Closes #306
Closes #328 
This is with the exception of Ace Editor inputs. Seperate issue will be made to solve it.
> focus styling

- ui/client/components/graph/ExpressionSuggester.js
- ui/client/test/ExpressionSuggester-test.js
> Handle safe navigation in SpEL

- ui/server/src/main/resources/defaultConfig.conf
> Server request-timeout longer (1 min) instead of default (20 sec) 

- .travis.yml
- ciRunSbt.sh
- ui/client/common/ProcessUtils.js
- ui/client/components/graph/ExpressionSuggest.js
- ui/client/test/ProcessUtils-test.js
This closes #468  - it's not pretty.. But if we want do it good we should do huge refactor.. For quick fix it will be enough.
> Fix: filtering globalVariables by category

- ui/client/components/graph/EdgeDetailsModal.js
- ui/client/components/graph/NodeDetailsModal.js
* Resolved #420 
* Fixed error on `EdgeDetailsContent` component caused by undefined property which is not used.
> Modal actions naming

- ui/client/actions/notificationActions.js
> Fix notification disappearing

- ui/client/assets/img/documentation.svg
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/NodeDetailsModal.js
- ui/client/components/graph/node-modal/NodeDetailsModalHeader.js
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/graph.styl
> Node's subtype near node's title

- .gitignore
Created empty work directory with .gitkeep file for keep empty dir in repo.
> Improvement: development dist

- ui/client/stylesheets/graph.styl
> Fix multiline expanding

- ui/client/components/graph/node-modal/ExpressionSuggest.js
- ui/client/package-lock.json
- ui/client/package.json
Bump react-ace 7.0.4 -> 8.0.0 and liveautocompletion ehnancements:
- it works after hash now
- it works after dot now
- suggester is invoked even if some suggestions are computed
> Liveautocompletion ehnancements

- .travis.yml
- engine/flink/management/sample/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.api.process.ProcessConfigCreator
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/UnitTestsProcessConfigCreator.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/QueryableStateTest.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/SampleNotificationProcess.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/SampleRecommendationProcess.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
+ naming refactor: now we have only one DemoProcessConfigCreator and TestProcessConfigCreator was renamed to DevProcessConfigCreator
> Showcase for types of parameters 

- ui/client/components/AddProcessDialog.js
- ui/client/components/Tool.js
- ui/client/components/graph/node-modal/MapVariable.js
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/Variable.js
- ui/client/components/graph/node-modal/subprocess-input-definition/SubprocessInputDefinition.js
- ui/client/reducers/graph.js
- ui/client/test/reducer-test.js
This closes #495 
Adding nodes from creator panel:
Copy of node:
Copy of copy of node:
Id changed to name:
> Humanize naming of nodes (#495)

- engine/api/src/main/java/pl/touk/nussknacker/engine/javaapi/process/ExpressionConfig.java
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/conversion/ProcessConfigCreatorMapping.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/ExpressionConfig.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompiledProcess.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TestInfoProvider.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/testing/ProcessDefinitionBuilder.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/util/service/query/ExpressionServiceQuery.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/variables/GlobalVariablesPreparer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/variables/MetaVariables.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
> Hiding meta variable

- ui/client/components/right-panel/SideNodeDetails.js
> Fix side node details

- ui/client/index.js
- ui/client/registerServiceWorker.js
Currently we have only plugin to register some ServiceLoader - but we don't have any SL.. :)
> Fixes: Problem with ServiceLoader

- ui/client/containers/Visualization.js
> Notify user that selected content can not be copied

- ui/client/components/tips/Errors.js
- ui/client/components/tips/NodeErrorsLinkSection.js
- ui/client/stylesheets/visualization.styl
> Add invalid end of process tip

- ciFrontendTest.sh
- ui/client/components/tips/Errors.js
* Fix Refactor Tests Utils
* Add build frontend dist package at frontend tests
> Fix: Refactor Test Utils

- ui/client/stylesheets/graph.styl
> Fix properties error button styling (#358)

- ui/client/components/CommentContent.js
> [FIX] links in comments work

- ui/client/components/graph/node-modal/Variable.js
- ui/client/components/graph/node-modal/editors/field/LabeledTextarea.js
- ui/client/stylesheets/graph.styl
> Resize description field according to rows number

- ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js
- ui/client/components/table/TableRowIcon.js
- ui/client/containers/Archive.js
- ui/client/containers/BaseProcesses.js
- ui/client/containers/Processes.js
- ui/client/containers/SubProcesses.js
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/processes.styl
This resolves #543 
This resolves #454
> Fix expression and processes table focus

- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/editors/field/Input.js
- ui/client/components/graph/node-modal/editors/field/LabeledInput.js
> Fix React warnings in properties modal

- ui/client/app.styl
> Disable comment section textarea resize

- .travis.m2.settings.xml
- .travis.yml
sbt publish (publishMavenStyle := true)
> Force sbt to use google cloud as a maven central mirror also during publish

- ui/client/components/graph/node-modal/editors/expression/BoolEditor.js
- ui/client/components/graph/node-modal/editors/expression/EditableExpression.js
- ui/client/components/graph/node-modal/editors/expression/EditorType.js
- ui/client/components/graph/node-modal/editors/expression/ExpressionParser.js
- ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js
- ui/client/components/graph/node-modal/editors/expression/ExpressionWithFixedValues.js
- ui/client/components/graph/node-modal/editors/expression/RawEditor.js
- ui/client/components/graph/node-modal/editors/expression/StringEditor.js
- ui/client/components/graph/node-modal/editors/expression/SwitchIcon.js
- ui/client/components/graph/node-modal/editors/field/Input.js
- ui/client/components/graph/node-modal/editors/field/LabeledInput.js
- ui/client/components/graph/node-modal/editors/map/MapValue.js
> Add String editor

- ui/client/assets/img/handlebars.svg
- ui/client/components/graph/node-modal/subprocess-input-definition/MovableRow.js
- ui/client/stylesheets/graph.styl
> Apply style to drag and drop handlebars

- ui/client/stylesheets/processHistory.styl
This closes #575 
Before:
After:
> Highlight version on hover in Versions Panel

- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/FetchingProcessRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
> Hotfix: Canceled process

- nussknacker-dist/src/universal/conf/base-application.conf
- nussknacker-dist/src/universal/conf/dev-application.conf
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala
- ui/restmodel/src/test/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatusTest.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/db/DatabaseInitializer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
* More configurable db
* Some small refactor
> Improvements: More configurable db

- ui/client/package-lock.json
- ui/client/package.json
…  because of bug with pre-push: https://github.com/typicode/husky/issues/646
> FIX: husky bump 4.0.7 -> 4.0.10

- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/DualEditor.java
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/DualEditorMode.java
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/LabeledExpression.java
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/RawEditor.java
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/SimpleEditor.java
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/SimpleEditorType.java
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/NodeDependency.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/EditorExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/MethodDefinitionExtractor.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/EditorExtractorTest.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjects.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsSpec.scala
Configuration and FE support will be added as separate PRs
> Add possibility to configure editor for parameter

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessState.scala
- engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
- ui/client/common/ProcessStateUtils.js
- ui/client/components/Process/ListState.js
- ui/client/components/ProcessHistory.js
- ui/client/test/Process/ListState-test.js
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/processdetails.scala
- ui/restmodel/src/test/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatusTest.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/db/entity/ProcessDeploymentInfoEntityFactory.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/FetchingProcessRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/WriteProcessRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessObjectsFinderTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/util/PdfExporterSpec.scala
- Fix problem when process was canceled and manager doesn't return status for it
- Fix bug with comments at edit process
- Fix bug with comparing version when process is not deployed
> Fix: canceled state

- ui/client/components/graph/node-modal/EdgeDetailsModal.js
- ui/client/components/graph/node-modal/NodeDetailsModal.js
- ui/client/components/graph/node-modal/NodeGroupDetailsContent.js
- ui/client/components/graph/node-modal/editors/expression/SwitchIcon.js
- ui/client/components/graph/node-modal/editors/field/Checkbox.js
- ui/client/components/graph/node-modal/subprocess-input-definition/MovableRow.js
- ui/client/stylesheets/graph.styl
> Fix read-only presentation

- ui/client/components/Process/State/ProcessState.tsx
- ui/client/components/right-panel/UserRightPanel.js
- ui/client/stylesheets/processes.styl
- ui/client/stylesheets/userPanel.styl
> process state styling in right panel

- ui/client/actions/nk/process.js
- ui/client/common/VisualizationUrl.ts
- ui/client/http/HttpService.js
- ui/client/http/HttpService.ts
- Verify business view at start in process window
- Reload data after change business view
> Fix: Bug with bussines view

- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- ui/client/components/graph/node-modal/editors/expression/DateTimeEditor/DateTimeEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/DateTimeEditor/TimeEditor.tsx
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/editor/ParameterTypeEditorExtractor.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/uiconfig/defaults/TypeRelatedParameterValueExtractor.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/editor/ParameterEditorExtractorChainTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/uiconfig/defaults/TypeRelatedParameterValueTest.scala
> Better defaults for date time types

- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessManagerSpec.scala
- engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/StatefulSampleProcess.scala
> add ignored test proving bug when redeploying process with mapAgreggator

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala
I tried to make descriptions more precise and tooltips more actionable. Still there is some room for improvement.
> Improved status descriptions

- engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
This reverts commit fd7f186bde28ce13c3f5796a93be6a952a9c400f. This change broke compatibility of Flink 1.6.
> Revert "Fix Flink warn log when running jar"

- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/DefaultValueDeterminerChain.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/editor/ParameterEditorDeterminerChain.scala
Chain is created for each parameter, for each invocation of definition api.
> Parameter definition - less logging

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/defaults/ParameterDefaultValueDeterminer.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/NodeDependency.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractor.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/EvaluatedParameterPreparer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjects.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/ConfigParameterDefaultValueDeterminer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/DefaultValueDeterminerChain.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/EditorPossibleValuesBasedDefaultValueDeterminer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/OptionalityBasedDefaultValueDeterminer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/ParameterDefaultValueDeterminer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/TypeRelatedParameterValueDeterminer.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparerSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/EvaluatedParameterPreparerSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/defaults/ConfigParameterDefaultValueDeterminerTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/defaults/DefaultValueDeterminerChainTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/defaults/EditorPossibleValuesBasedDefaultValueDeterminerTest.scala
> Fix default value based on editor default values determining

- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- ui/client/components/graph/node-modal/editors/expression/duration/DurationEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/duration/PeriodEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/duration/TimeRangeEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/duration/timeRange.styl
> Allow simple duration editor with empty expression

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala
- engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkStateStatus.scala
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/ProcessStatus.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
> Fix: Bug with cancel running process with error

- ui/client/containers/Visualization.js
> Fix: error information about copy

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessState.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
…  instead of ManagementActor's failure + allow cancel for failures
> Statuses fix: always prefer failed state from process manager

- .travis.sbt.repositories
- BUILDING.md
- project/build.properties
- sbtwrapper
Building on Windows requires two changes:
* new version of sbtwrapper, which properly escapes paths
* renaming of ".gitkeep " to ".gitkeep" - otherwise JGit refuses to work and throws exceptions
> Fix build on Windows

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/CommonSupertypeFinder.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- engine/api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultSpec.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
Allow to checking tagged typed elements.
> Improvements: TaggedType compare

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- ui/client/common/DialogMessages.ts
- ui/client/components/AddProcessDialog.js
- ui/client/components/graph/node-modal/editors/Validators.ts
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/client/components/modals/ValidationLabels.tsx
- ui/client/test/ValidationLabels-test.js
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/PrettyValidationErrors.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ValidationResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
- Improve BE error type
- Some FE improvements
- FE fix bug on create new process
> Improvements: Editor Validators

- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/QueryableStateResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ServiceRoutes.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SignalsResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/TestInfoResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/initialization/Initialization.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/NewProcessPreparer.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/ProcessModelMigrator.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataProvider.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReader.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessActionRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/WriteProcessRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/uiresolving/UIProcessResolving.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/AdditionalPropertiesValidator.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
> [Refactor] ProcessingTypeDataProvider in separate package

- build.sbt
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSourceFactory.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaSinkFactory.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaSourceFactory.scala
* Add Dual Editor to kafka sources and sinks at topic field
* Mark NotBlank topic and schema registry field
> Improvements: Enriche kafka sinks and sources

- ui/client/components/sidePanels/ScrollbarsExtended.styl
- ui/client/components/sidePanels/ScrollbarsExtended.tsx
- ui/client/components/sidePanels/SidePanel.styl
- ui/client/components/toolbarComponents/ToolbarsLayer.styl
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/togglePanel.styl
> [fe-only] consistent sidePanels scrollbars

- build.sbt
- engine/flink/management/sample/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.additionalInfo.NodeAdditionalInfoProvider
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/SampleNodeAdditionalInfoProvider.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/additionalInfo/NodeAdditionalInfo.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/additionalInfo/NodeAdditionalInfoProvider.scala
- ui/client/components/graph/node-modal/NodeAdditionalInfoBox.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/tests/TestResults.js
- ui/client/http/HttpService.ts
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/stylesheets/markdown.styl
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessDirectives.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/NodeResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
Ability to show additional information for nodes, currently markdown format is supported
> Additional node info, markdown implementation

- ui/client/components/ProcessHistory.tsx
- ui/client/stylesheets/processHistory.styl
scroll is now thicker and easier to grab
> wider inner-scroll for version history (#826)

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
- engine/flink/management/sample/src/main/resources/reference.conf
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/validator/LiteralValidatorExtractor.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/validator/ValidatorsExtractorTest.scala
- ui/client/components/graph/node-modal/editors/Validators.ts
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/PrettyValidationErrors.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ValidationResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/AdditionalPropertiesValidatorTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
- Add BE and FE RegExpParameterValidator
- Replace LiteralIntValidator by RegExpParameterValidator
- Small refactor
This resolves https://github.com/TouK/nussknacker/issues/813
> Improvements: RegExpParameterValidator

- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/SslBindingSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/DictsFlowTest.scala
- Extract NussknackerBaseApp
- Allow to create own initialize app class at external project
> Feature: Extract NussknackerBaseApp

- ui/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
Sorry about that, I've introduced typo in previous PR
> Make FixedValuesEditor more explicit about current value - fixup (typo)

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ParameterTypeEditorDeterminer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/validator/FixedValueValidatorExtractor.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/validator/ValidatorsExtractorTest.scala
- ui/client/components/graph/node-modal/editors/EditableEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
- ui/client/stylesheets/processes.styl
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/defaults/EditorPossibleValuesBasedDefaultValueDeterminer.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/defaults/EditorPossibleValuesBasedDefaultValueDeterminerTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/editor/ParameterBasedEditorDeterminerChainTest.scala
> FixedValueEditor in dual editor mode for enums

- nussknacker-dist/src/universal/conf/base-application.conf
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
The information is already contained in JDBC url.
> Redundant DB type configuration property removed.

- engine/flink/management/sample/src/main/resources/reference.conf
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ValidationResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
Refactor example process params to be more real example - more human friendly.
> Improvements: Example process

- ui/client/components/modals/GenerateTestDataDialog.js
> [FIX] Validate generate data input, closes #1

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/CommonSupertypeFinder.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- engine/demo/src/main/scala/pl/touk/nussknacker/engine/demo/UtilProcessHelper.scala
- engine/flink/generic/src/main/scala/pl/touk/nussknacker/genericmodel/GenericConfigCreator.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/MethodDefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/propertyAccessors.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/TypeMethodReference.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/columnmodel/TypedClassColumnModel.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/types/EspTypeUtils.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/types/TypesInformationExtractor.scala
- engine/interpreter/src/test/java/pl/touk/nussknacker/engine/types/JavaClassWithVarargs.java
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/functions/conversion.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjects.scala
Futures were flatten during methods extraction instead what during method definition extraction
> Fix for: methods returning Futures

- docs/Changelog.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/ReturningType.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSchemaProvider.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSourceFactory.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSourceFactorySpec.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
- engine/test-util/src/main/scala/pl/touk/nussknacker/test/NussknackerAssertions.scala
On disabled SchemaRegistry - no connections:
Bad topic name:
Bad version number:
> Feature: More detailed node errors

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
Closes #747 
We didn't find all branch ends when there was custom node in the middle...
> [FIX] Union after custom node works

- ui/client/http/HttpService.ts
> [FIX] Fatal node validation prevents closing modal

- demo/docker/README.md
- demo/docker/docker-compose.yml
- docs/Changelog.md
- nussknacker-dist/src/universal/bin/nussknacker-entrypoint.sh
- nussknacker-dist/src/universal/bin/run.sh
> [Improvement] JVM options can be configured via env variable

- docs/MigrationGuide.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypedMap.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sinks.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/ProcessSpec.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/SqlProcessItTests.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/ProcessTestHelpers.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/propertyAccessors.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
> Typed map fixes

- docs/Changelog.md
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/AvroUtils.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/fixed/FixedKafkaAvroSchemaProvider.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaRegistryClient.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaRegistryKafkaAvroProvider.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClient.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/FixedConfluentSchemaRegistryClient.scala
- Changes at SchemaRegistryClient. Provided: getLatestFreshSchema and getFreshSchema methods
- Some enhancement at getting / parsing avro schema
> Improvement: avro schema enhancement

- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/PreviousValueTransformer.scala
- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/TransformStateTransformer.scala
- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/sampleTransformers.scala
- engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/transformers.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/functions/numeric.scala
> Making API (custom transfromers, utils) more friendly for CharSequence

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/fixed/FixedKafkaAvroSchemaProvider.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentSchemaRegistryProvider.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/FixedKafkaAvroSourceFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
- More pluggable fixed avro provider
> Improvements: Pluggable Avro Fixed

- docs/Changelog.md
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/SimpleEditorType.java
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/FixedKafkaAvroSourceFactory.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/EditorExtractor.scala
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/client/components/graph/node-modal/editors/expression/TextareaEditor.tsx
- ui/client/components/graph/node-modal/editors/field/Textarea.js
closes https://github.com/TouK/nussknacker/issues/862
> [Fix] enters in schema field

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/CustomNodeInvoker.scala
... for easier testing of expressions on user code side
> ExpressionLazyParameter and FixedLazyParameter visible 

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClientFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/MockSchemaRegistryClient.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/MockSchemaRegistryClientBuilder.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSourceFactorySpec.scala
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
When we deploy process with avro sink and DefaultCache then flink throws exception with information about serialization problem.
> Fix: Flink serialization cache

- demo/docker/docker-compose-env.yml
3081 is already used for app ;)
> [Fix] change port for demo

- ui/client/components/graph/Graph.js
- ui/client/components/graph/focusable.tsx
- ui/client/components/toolbarComponents/CollapsibleToolbar.styl
- ui/client/components/toolbarComponents/ToolbarButton.styl
- ui/client/containers/Visualization.js
- ui/client/stylesheets/_mixins.styl
> Bugfix #959 & #832

- engine/flink/avro-util/src/test/resources/application.conf
- Add resources for avro integration tests
> Fix: Avro Sink Tests

- docs/Changelog.md
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/transformer/DynamicParametersTransformer.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/transformer/LastVariableFilterTransformer.scala
- ui/client/actions/nk/nodeDetails.ts
- ui/client/components/graph/node-modal/BranchParameters.js
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/ParameterList.js
- ui/client/components/graph/node-modal/ParametersUtils.ts
- ui/client/components/graph/node-modal/editors/expression/ExpressionField.tsx
- ui/client/reducers/nodeDetailsState.ts
- ui/client/types/definition.ts
- ui/client/types/index.ts
- ui/client/types/node.ts
- ui/client/types/validation.ts
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
First version of handling dynamic parameters on FE. It works, but there are still some UX quirks and refactorings to be done:
- default values are not filled for dynamic parameters
- to display dynamic parameters correctly request to BE is done when modal is opened
- after adding parameters additional request to BE is done to validate them
- we filter out MissingParameters validation errors for parameters that are going to be added after handling request 
I'd like to leave those for next PRs, as this version is functional and I don't want to make it too large
> [Feature] Dynamic parameters on UI - first version

- docs/Changelog.md
- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/SimpleEditorType.java
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/EditorExtractor.scala
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/client/components/graph/node-modal/editors/expression/JsonEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/ace.ts
closes https://github.com/TouK/nussknacker/issues/894
> [Feature] json editor

- ui/client/components/graph/node-modal/EdgeDetailsContent.js
- ui/client/components/graph/node-modal/EdgeDetailsModal.js
- ui/client/components/graph/node-modal/MapVariable.js
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/Variable.js
- ui/client/components/graph/node-modal/editors/map/Map.js
- ui/client/components/graph/node-modal/editors/map/MapRow.js
- ui/client/components/graph/node-modal/editors/map/MapValue.js
> [FIX] Suggestions work for case expressions and variable definitions

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/namespaces/ObjectNaming.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseTransformer.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSpecMixin.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/NamespacedKafkaTopicSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactorySpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactorySpec.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/NamespacedKafkaSourceSinkTest.scala
* Added Kafko Avro Support for namespace at topics list // filtering by namespace prefix for example..
* Some refactor
* Add tests
> Feature: Kafka Avro support namespace at topics

- ui/client/components/graph/node-modal/AdditionalProperty.tsx
- ui/client/components/graph/node-modal/BranchParameters.js
- ui/client/components/graph/node-modal/EdgeDetailsContent.js
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/editors/EditableEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/BoolEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/DualParameterEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Duration/DurationEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Duration/PeriodEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Duration/TimeRangeComponent.tsx
- ui/client/components/graph/node-modal/editors/expression/Duration/TimeRangeEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Duration/TimeRangeSection.tsx
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/client/components/graph/node-modal/editors/expression/ExpressionField.tsx
- ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js
- ui/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/RawEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/StringEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/SwitchIcon.js
- ui/client/components/graph/node-modal/editors/expression/TextareaEditor.tsx
Editors were a bit messy, especially with FixedValues and DualEditor. We simplify structure, to make it similar to ParameterEditor hierarchy in backend.
> [Improvement] Editors of FE more consistent

- docs/MigrationGuide.md
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseTransformer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/BaseKafkaAvroSinkFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSink.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/BaseKafkaAvroSourceFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroNamespacedSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSpecMixin.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactorySpec.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sources.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/sink/KafkaSinkFactory.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSource.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactory.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/NamespacedKafkaSourceSinkTest.scala
- engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaUtils.scala
* Provided PreparedKafkaTopic for prepared topic name..
* Change KafkaSource Api - now it needs List[PreparedKafkaTopic]
> Fix: Object naming

- build.sbt
- docs/MigrationGuide.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/AvroUtils.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/encode/BestEffortAvroEncoder.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schema/DatumReaderWriterMixin.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/AbstractConfluentKafkaAvroDeserializer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroDeserializer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/typed/AvroSchemaTypeDefinitionExtractor.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSpecMixin.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/encode/BestEffortAvroEncoderSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/schema/PaymentDate.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/TestConfigPreparer.scala
> avro 1.8.2 -> 1.9.2 bump + support for logical types 

- .github/workflows/pr.yml
As first step we leave travis as-is, but add building with GH actions for PRs.
Next steps:
- disabling travis for PRs
- moving builds including publish to Sonatype/Docker to GH actions
> [Improvement] github actions for PR

- docs/Changelog.md
- ui/client/components/graph/node-modal/editors/expression/Duration/DurationEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Duration/PeriodEditor.tsx
closes https://github.com/TouK/nussknacker/issues/1062
> [Fix] duration and period editor

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseTransformer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/BasedOnVersionAvroSchemaDeterminer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaVersionOption.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/BaseKafkaAvroSinkFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSink.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroNamespacedSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSpecMixin.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactorySpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactorySpec.scala
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/convert.scala
Avro schema: explicit option instead of None for purpose of further api changes (like scham auto registration)
> Avro schema version option

- .travis.yml
- .travis/buildPushDocker.sh
- demo/docker/docker-compose-env.yml
- demo/docker/testQuickstart.sh
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
- Wait a bit longer for startup
- Make docker publish fail fast
> [Improvement] Make travis scripts more robust

- demo/docker/docker-compose.yml
- docs/Quickstart.md
> Switch default NUSSKNACKER_VERSION in docker-compose to latest

- demo/docker/docker-compose-env.yml
- demo/docker/docker-compose.yml
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverter.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/util/PdfExporter.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
Also minor fixes in demo/docker
> [FIX]  handle union after split,switch,filter

- ui/client/components/sidePanels/ScrollbarsExtended.styl
- ui/client/components/toolbarComponents/CollapsibleToolbar.styl
- ui/client/stylesheets/_variables.styl
- ui/client/stylesheets/mainMenu.styl
> Smaller nav

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ContextTransformation.scala
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformer.scala
sanitizeBranchName and findUniqueParentContext
> Context transformation utils extracted from UnionTransformer

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
> Fix for: bad classloader in node validation cause NoClassDefFound

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/AvroSchemaDeterminer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseTransformer.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/BasedOnVersionAvroSchemaDeterminer.scala
it was created for each request for definition
> Fix for: schema registry client leak

- demo/docker/docker-compose-env.yml
- Manage schema gui
- Manage kafka gui
> Feature: Docker Akhq support

- ui/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
- ui/client/components/graph/node-modal/subprocess-input-definition/MovableRow.js
- ui/client/stylesheets/_mixins.styl
- ui/client/stylesheets/graph.styl
- ui/client/stylesheets/select.styl
> fix: SelectBox in node details view is hidden unnecessarily #1025

- ui/client/components/toolbars/status/buttons/MetricsButton.tsx
- ui/client/reducers/selectors/graph.ts
> disable "deploy" & "metrics" for subprocess

- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/MetricsSpec.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/process/functional/TestReporter.scala
- Instancies as ConcurrentHashMap[String, TestReporter]
- Allow to: reset all reporters, reset specific reporter, remove all reporters, remove specific reporter, get specific reporter
> Improvements: More flexible TestReporter instancies implementation

- ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js
> disable find dialog in ace

- ui/client/components/withFocus.tsx
- ui/client/containers/Visualization.js
> Paste nodes inside viewport

- ui/client/components/graph/svg-export/prepareSvg.ts
- ui/client/components/healthCheck.styl
> HealthCheck icon size

- ui/client/containers/ProcessesList.tsx
- ui/client/containers/processesTable/ProcessesTable.tsx
- ui/client/local-types/reactable/index.d.ts
> case insensitive sorting

- build.sbt
- docs/Changelog.md
One of the main reasons is https://github.com/lightbend/config/pull/620
> [Improvement] Upgrade typesafe config

- .gitignore
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypeEncoders.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
- ui/client/actions/nk/nodeDetails.ts
- ui/client/common/ProcessUtils.ts
- ui/client/components/graph/NodeUtils.ts
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/Variable.js
- ui/client/components/graph/node-modal/editors/EditableEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/Editor.ts
- ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js
- ui/client/components/graph/node-modal/editors/expression/RawEditor.tsx
- ui/client/components/graph/node-modal/editors/types.ts
- ui/client/components/graph/node-modal/subprocess-input-definition/SubprocessInputDefinition.js
- ui/client/components/modals/ValidationLabels.tsx
- ui/client/containers/admin/Services.js
- ui/client/reducers/nodeDetailsState.ts
- ui/client/stylesheets/processes.styl
- ui/client/test/ProcessUtils-test.js
- ui/client/types/definition.ts
- ui/client/types/validation.ts
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/NodeResourcesSpec.scala
1. Validate variable expression definition in Variable modal.
2. Display inferred type in variable expression definition.
TODO in next iteration:
0. Return typed expression in ValidationResult of DisplayableProcess
1. VariableBuilder validation & inferred type
2. Refactor of NodeDataValidator - validation logic should be moved to NodeCompiler
> Variable node validation * inferred type info [#249]

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
1. Compile field and expressions with NodeCompiler
> Refactor PartSubGraphCompiler

- docs/Changelog.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/expression/Expression.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/dict/ProcessDictSubstitutor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/SqlExpressionParser.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/types/validation.ts
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/ValidationResults.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ValidationResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/uiresolving/UIProcessResolving.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
1. Add expression TypingResult to ValidationResult
2. Display inferred expression type on modal open
> Expression type info in validation result

- engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala
- engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessConfigCreator.scala
- engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreterSpec.scala
Exception that would happen in sink code would propagate outside interpreters
invoke function. Let's handle it with EspExceptionInfo
> Standalone - handle exception thrown in sink

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/QueryableStateTest.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/FlinkMiniClusterHolder.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/FlinkSpec.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/MiniClusterExecutionEnvironment.scala
* More elastic creating  flinkMiniCluster at FlinkSpec
* Move cancelJob, submitJob, listJobs to FlinkMiniClusterHolder interface
* Remove getClusterClient from FlinkMiniClusterHolder interface
* Missing MigrationGuide information
> Improvements: Flink test util

- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
1. Pass parent context for subprocess output fields compilation
> Fix subprocess output context:

- ui/client/containers/hooks/useSize.tsx
> resizeObserver polyfill enable

- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/transformer/DynamicParametersMixin.scala
- engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/EndRateMeterFunction.scala
- engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala
- engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/SplitFunction.scala
- engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/TypeInformationDetection.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/part.scala
- engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala
And pass more ValidationContext in FlinkProcessRegistrar.
This is preliminary work which aims to provide better TypeInformation in the future
> [Improvement] Extract TypeInformation detection to trait

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentSchemaRegistryProvider.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSpecMixin.scala
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/ProcessTestHelpers.scala
- engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaConfig.scala
- engine/kafka/src/test/scala/pl/touk/nussknacker/engine/kafka/KafkaConfigSpec.scala
Overloaded methods for: optional kafka config parsing and for default global config path
> Easier kafka config parsing

- docs/Changelog.md
Missing changelog entry after merging https://github.com/TouK/nussknacker/pull/1315
> Add missing changelog entry for Spring upgrade

- build.sbt
- docs/Changelog.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/NumberTypesPromotionStrategy.scala
- engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/aggregate/AggregatorBenchamark.scala
aggregate.add 5* speed up (0,333 us -> 0,058 us)
> Type promotion cache

- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregatorFunction.scala
- minimalResolutionMs as a method
- computeFinalValue can be overridden using computeFoldedAggregatedValue
> More configurable aggregates

- docs/Changelog.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ValidationContext.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/PrettyValidationErrors.scala
* Add validation variable name
* Changes in presentation error message
Before:
After:
> Improvements: Variable output validation

- ui/server/src/main/scala/db/util/DBIOActionInstances.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/QueryableStateResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/db/entity/CommentEntityFactory.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessActionRepository.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/TransactionSupport.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/WriteProcessRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepositorySpec.scala
Add transactionally on mark process as achived or unarchived.
> Improvements: Allowed actions transactionally

- ui/client/components/Process/ProcessLastAction.tsx
- ui/client/containers/Archive.tsx
- ui/client/containers/Processes.tsx
- ui/client/stylesheets/processes.styl
> UX Improvements

- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/BaseOAuth2Service.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/EpochSecondsCodecs.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtOAuth2Service.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectProfile.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectService.scala
- engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
I got it wrong from the specification before.
> Fix expiration units: milliseconds -> seconds

- build.sbt
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/RunGenericModelLocally.scala
- engine/interpreter/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.ProcessManagerProvider
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/ProcessManagerProvider.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/testing/ProcessManagerStub.scala
- ui/README.md
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/WebResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataProvider.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/util/LocalNussknackerWithSingleModel.scala
Helpers to make running UI with fixed model easier. This is especially needed when developing custom node transformers - we want to see result on UI, without packaging model into jar every time.
> [Feature] Make running local NK UI easier

- engine/api/src/main/java/pl/touk/nussknacker/engine/api/editor/SimpleEditorType.java
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/SqlSource.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/parameter/editor/EditorExtractor.scala
Part of https://github.com/TouK/nussknacker/issues/1106
> Improvements: BE Sql Editor supprot

- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/serialization/KafkaProducerHelper.scala
- engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/serialization/KafkaProducerHelperSpec.scala
…to null to let KafkaProducer decide
> KafkaProducerHelper - convert negative timestamp (eg. Long.MinValue) to null

- .github/workflows/pr.yml
- CONTRIBUTING.md
- build.sbt
- demo/docker/testQuickstart.sh
- docs/Changelog.md
- docs/Configuration.md
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/CustomStreamTransformer.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/Service.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/component/ComponentProvider.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/Sink.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/Source.scala
- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/WithCategories.scala
- engine/flink/management/sample/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.api.component.ComponentProvider
- engine/flink/management/sample/src/main/resources/defaultModelConfig.conf
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/component/SampleComponentProvider.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/modelconfig/SampleModelConfigLoader.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/SampleComponentProviderTest.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/component/ComponentExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/modelconfig/DefaultModelConfigLoader.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/component/ComponentExtractorTest.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/Implicits.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/logging/ExecutionTimeMeasuring.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
Introduces new way of providing Components (Services, SourceFactories, etc.)
Use cases:
- OpenAPI integration
- DB (SQL and noSQL) integration
- configurable aggregations etc.
> [Feature] ComponentProvider

- docs/Changelog.md
- engine/flink/generic/src/main/scala/pl/touk/nussknacker/genericmodel/GenericConfigCreator.scala
- engine/flink/model-util/src/main/java/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/SessionWindowTrigger.java
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/sampleTransformers.scala
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/transformers.scala
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/triggers.scala
- engine/flink/model-util/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/TransformersTest.scala
Simple session window, with:
- close session on timeout or ending event
- trigger on session end or on each window
> [Feature] Simple session window

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- ui/client/components/graph/node-modal/editors/Validators.ts
- ui/client/components/graph/node-modal/editors/expression/JsonEditor.tsx
* Fix number min / max validators
> Fix: Literal number validators

- .github/workflows/pr.yml
We need it to build correct staging image...
> [Temporary] Turn e2e tests off

- .github/workflows/pr.yml
This reverts commit 19c9fadc5f5aef3ef26f4843052ba5eed58d9183.
> Revert "[Temporary] Turn e2e tests off (#1787)"

- demo/docker/flink/flink-conf.yaml
- demo/docker/grafana/dashboards/Flink-ESP.json
- demo/docker/telegraf/telegraf.conf
- demo/docker/testData/continouslySendAudit.sh
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/transformers.scala
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/outer/OuterJoinTransformer.scala
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/richflink.scala
- nussknacker-dist/src/universal/conf/application.conf
Mainly RocksDB setup: exporting metrics, default values. 
Also added RocksDB panels to dashboard (as separate row, can be hidden by default)
> Some default setup improvements

- nussknacker-dist/src/universal/conf/base-application.conf
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessActivityResourceSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessPosting.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepositorySpec.scala
Just to be sure the process was migrated/synchronized. Currently when there is no difference between processes, on remote enviroment no comment is added, but on local environment a notification is displayed about successful migration.
> Add comment when updating process with the same version

- ui/client/actions/nk/process.js
- ui/client/actions/nk/userSettings.ts
- ui/client/common/userSettings.tsx
- ui/client/components/graph/EspNode/element.ts
- ui/client/components/graph/EspNode/esp.ts
- ui/client/components/graph/Graph.js
- ui/client/components/graph/GraphPartialsInTS/drawGraph.ts
- ui/client/components/graph/joint-events.ts
- ui/client/components/graph/node-modal/editors/expression/AceWrapper.tsx
- ui/client/components/graph/node-modal/editors/expression/JsonEditor.tsx
- ui/client/components/graph/node-modal/editors/expression/ace.ts
- ui/client/components/graph/node-modal/editors/expression/types.ts
- ui/client/components/toolbarSettings/TOOLBAR_COMPONENTS_MAP.ts
- ui/client/components/toolbarSettings/defaultToolbarsConfig.ts
- ui/client/components/toolbars/UserSettingsPanel.tsx
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/reducers/graph/types.ts
- ui/client/reducers/selectors/graph.ts
- ui/client/reducers/selectors/userSettings.ts
- ui/client/reducers/userSettings.ts
- ui/client/stylesheets/graph.styl
> Node test counts

- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/UriUtils.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/service/ProcessToolbarService.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/service/ConfigProcessToolbarServiceSpec.scala
- Added encodeing process name in urls
> Improvements: Process Toolbars

- build.sbt
"optional, provided" does not seem to work....
> [FIX] Leaner OpenAPI assembly

- .github/workflows/pr.yml
- ui/client/README.md
- CI uses .nvmrc file
- Notice about `nvm use` command
> UI client improvements - nvm use

- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactoryWithEditor.scala
> [FIX] Handle initial parameters status in KafkaSinkWithEditor properly

- ui/client/common/ProcessUtils.ts
This change fixes incorrect behaviour visible below:
> [FIX] nothingToSave ignores validationResult

- engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala
- engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactoryDefinitionExtractorSpec.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionValidator.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/TypeMethodReference.scala
- engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/types/EspTypeUtils.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/TyperSpec.scala
- engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala
Added static methods to clazz definition
> Method validation

- docs/installation_configuration_guide/DesignerConfiguration.md
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationConfiguration.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/GlobalPermission.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
- engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/RulesSet.scala
- engine/security/src/test/scala/pl/touk/nussknacker/ui/security/api/RulesSetSpec.scala
- engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
- engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactorySpec.scala
- engine/util/src/main/scala/pl/touk/nussknacker/engine/util/config/FicusReaders.scala
- nussknacker-dist/src/universal/conf/dev-application.conf
- ui/client/actions/nk/assignSettings.ts
- ui/client/common/models/User.ts
- ui/client/components/MenuBar.tsx
- ui/client/containers/AdminPage.js
- ui/client/containers/CustomTab.tsx
- ui/client/containers/DynamicTab.tsx
- ui/client/containers/Signals.js
- ui/client/reducers/selectors/settings.ts
- ui/client/reducers/settings.ts
- ui/server/src/main/resources/defaultUiConfig.conf
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/UserResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfig.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/UsersResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
- GlobalPermission can be an arbitrary string
- All top tabs can be defined now
> Configurable standard tabs

- ui/client/webpack.config.js
most of the time it's not useful
> chore: remove errors overlay in dev

- build.sbt
- engine/flink/api/src/main/scala/pl/touk/nussknacker/engine/flink/api/timestampwatermark/TimestampWatermarkHandler.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroTestProcessConfigCreator.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/TestFromFileSpec.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/BaseKafkaDelayedSourceFactory.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sources.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaContextInitializer.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSource.scala
- engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactory.scala
- engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/consumerrecord/ConsumerRecordToJsonFormatterSpec.scala
- engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactoryProcessConfigCreator.scala
- engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactoryProcessMixin.scala
- engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/source/TestFromFileSpec.scala
- engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/NoEndingSource.scala
- engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/PeriodicSourceFactory.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/process/ProcessToString.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
- engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/process/helpers/SinkForType.scala
> Correct timestamps in test from file for Kafka sources

- nussknacker-dist/src/universal/bin/nussknacker-entrypoint.sh
…rage can have other owner (root)
> docker volume fix

- docs/Changelog.md
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/AvroSinkValue.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/BaseKafkaAvroSinkFactory.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSink.scala
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KeyedRecordFlatMapper.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/sink/AvroSinkValueTest.scala
1. Do not map LazyParameter on each event.
2. Do not use refletcion; get typing from SinkValue instead.
> Fix KeyedRecordFlatMapper performance:

- .github/workflows/pr.yml
- ui/client/.eslintrc
- ui/client/bootstrap.tsx
- ui/client/components/toolbarSettings/ToolbarSelector.tsx
- ui/client/components/toolbarSettings/useToolbarConfig.tsx
- ui/client/components/versionInfo.tsx
- ui/client/containers/NussknackerApp.tsx
- ui/client/http/HttpService.ts
- ui/client/index.d.ts
- ui/client/stylesheets/visualization.styl
- ui/client/version.js
- ui/client/webpack.config.js
> feat: show (build) version number

- ui/client/package-lock.json
- ui/client/package.json
> Revert "build(deps-dev): bump webpack-dev-server from 3.11.2 to 4.3.0 in /ui/client"

- engine/base/kafka/src/main/scala/pl/touk/nussknacker/engine/baseengine/kafka/KafkaSingleScenarioTaskRun.scala
- engine/base/kafka/src/main/scala/pl/touk/nussknacker/engine/baseengine/kafka/KafkaTransactionalScenarioInterpreter.scala
- engine/base/kafka/src/main/scala/pl/touk/nussknacker/engine/baseengine/kafka/LoopUntilClosed.scala
- engine/base/kafka/src/test/scala/pl/touk/nussknacker/engine/baseengine/kafka/KafkaTransactionalScenarioInterpreterTest.scala
> Fixes for nu-streaming init, KafkaConfig is part of EngineConfig

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/kryo/AvroSerializersRegistrar.scala
- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/flink/TestFromFileSpec.scala
- engine/flink/components/kafka/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProvider.scala
- engine/flink/generic/src/main/resources/defaultModelConfig.conf
- engine/flink/generic/src/test/resources/application.conf
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericClassExtractionTest.scala
- engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
- engine/flink/management/sample/src/main/resources/defaultModelConfig.conf
- engine/flink/management/sample/src/test/resources/application.conf
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/NamespacedKafkaSourceSinkTest.scala
- engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/SampleComponentProviderTest.scala
- nussknacker-dist/src/universal/conf/application.conf
- nussknacker-dist/src/universal/conf/dev-application.conf
- utils/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/GenericRecordSchemaIdSerializationSupport.scala
Merge to staging after `release/1.1` branch is cut
> Use component config rather that global model data config

- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaSingleScenarioTaskRun.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaTransactionalScenarioInterpreter.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/LoopUntilClosed.scala
- engine/lite/kafka/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaTransactionalScenarioInterpreterTest.scala
…ent attempts + delay before restart
> Lite Kafka runtime: delay before restart + attempt logging

- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaSingleScenarioTaskRun.scala
- abortTransaction near begin / commit to make sure that it is done ASAP
- interpreter.invoke in transaction block to avoid e.g. multiple service invocations in case of beginTransaction failure
> Kafka lite runtime transactions tweaks

- docs/Changelog.md
- engine/flink/engine/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala
- engine/flink/engine/src/test/scala/pl/touk/nussknacker/engine/process/functional/ProcessSpec.scala
> [FIX] Results and exception were collected incompletely in async mode

- build.sbt
- engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/ClassPaths.scala
> Fix for provided dependencies in assembly

- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
> [FIX] DeploymentService has wrong ProcessId

- engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/AvroNodesClassloadingSpec.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/EmbeddedDeploymentManagerTest.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TestInfoProvider.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/testmode/TestDataPreparer.scala
- utils/test-util/src/main/scala/pl/touk/nussknacker/test/FailingContextClassloader.scala
> Fix classloaders in data generation

- docs/scenarios_authoring/AggregatesInTimeWindows.md
- docs/scenarios_authoring/BasicNodes.md
- docs/scenarios_authoring/Intro.md
Added Delay component description.
Some docs cosmetics.
-->
> added Delay component description + some docs cosmetics

- build.sbt
- engine/lite/components/base/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteBaseComponentProvider.scala
> Request response union docs

- docs/developers_guide/Components.md
- docs/installation_configuration_guide/ModelConfiguration.md
> Docs updates

- engine/lite/kafka/api/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/api/LiteKafkaSource.scala
- engine/lite/kafka/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/kafka/TestComponentProvider.scala
> Removed redundant method and moved logic into TestComponentProvider 

- ui/client/cypress/integration/components.ts
- ui/client/cypress/support/tools.ts
> Wait a bit longer for query in cypress

- engine/lite/k8sDeploymentManager/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.DeploymentManagerProvider
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sUtils.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/KafkaK8sSupport.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/config/UiConfigLoader.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/ConfigurationTest.scala
- utils/util/src/main/scala/pl/touk/nussknacker/engine/util/config/ConfigFactoryExt.scala
> K8s DeploymentManager - simple version

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentStatusMapper.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sProcessStateDefinitionManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sStateStatus.scala
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/inProgress.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/progressFailed.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/running.json
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentStatusMapperSpec.scala
> K8sDeploymentManager status

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
> Cancel K8s scenario

- build.sbt
> Smaller images for runtimes

- .github/workflows/benchmark.yml
> Fix benchmark output

- build.sbt
> Fix openapi httpUtils dependency scope

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sUtils.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerUnitTest.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeApp.scala
> K8s - redeployment

- nussknacker-dist/src/universal/conf/dev-application.conf
> Remove custom scenario from dev config

- build.sbt
> Correct image setting

- docs/Changelog.md
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/streaming/embedded/EmbeddedDeploymentManager.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/BaseEmbeddedDeploymentManagerTest.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/EmbeddedDeploymentManagerRestartTest.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/EmbeddedDeploymentManagerTest.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/LoopUntilClosed.scala
> Add During Deploy state for Embedded DeploymentManager

- ui/client/containers/processesTable/useRowsPerPage.tsx
> avoid scenario list flicker

- build.sbt
- docs/Changelog.md
- docs/developers_guide/Basics.md
- docs/installation_configuration_guide/Configuration.md
- docs/installation_configuration_guide/ModelConfiguration.md
- engine/lite/kafka/runtime/src/universal/conf/application.conf
- nussknacker-dist/src/universal/conf/dev-application.conf
- utils/util/src/main/scala/pl/touk/nussknacker/engine/util/loader/ModelClassLoader.scala
- utils/util/src/test/scala/pl/touk/nussknacker/engine/util/loader/ModelClassLoaderSpec.scala
> Handle dir in classloader path

- nussknacker-dist/src/universal/conf/application.conf
> Default classpath includes components

- ui/client/containers/ExternalLib/tools/loadComponent.ts
- ui/client/index.d.ts
- ui/client/version.js
- ui/client/webpack.config.js
- ui/submodules/configs/webpack/withModuleFederationPlugins.ts
> fixed (hopefully) cache in module federation

- components/sql/src/main/scala/pl/touk/nussknacker/sql/db/schema/MetaDataProviderFactory.scala
> SQL component classloader fix

- README.md
- docs/developers_guide/Components.md
> Links to nussknacker-custom-components

- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/SwaggerTyped.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseSwaggerRefSchemas.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/SwaggerParser.scala
- components/openapi/src/test/resources/swagger/embedded-schema.json
- components/openapi/src/test/scala/pl/touk/nussknacker/openapi/parser/SwaggerParserTest.scala
> OpenAPI small fixes

- ui/submodules/configs/webpack/common.ts
- ui/submodules/configs/webpack/prod.ts
- ui/submodules/packages/components/src/components/nkView.tsx
- ui/submodules/types/@override/index.d.ts
> hash in filenames

- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/component/package.scala
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/processdetails.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestProcessUtil.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/ConfigProcessToolbarServiceSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/util/PdfExporterSpec.scala
* Add modfiedBy field
* Add modifiedAt field
* Mark modificationDate as deprecated
> Improvement: Change modified information at BaseProcessDetails

- build.sbt
> Use jre-slim at kafka runtime

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
> Configure readiness proble for longer period

- build.sbt
> Use openjdk:11-jre in designer UI

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
* Configure readiness proble for longer period
* Fix unit test
> Configure readiness proble for longer period (#2779)

- README.md
> Update readme for lite

- interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
- nussknacker-dist/src/universal/conf/dev-application.conf
> Default values for GenericNodeTransformation

- interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
- nussknacker-dist/src/universal/conf/dev-application.conf
> Default values for GenericNodeTransformation (#2805)

- docs/Changelog.md
> Changelog - release dates added

- docs/developers_guide/Components.md
- docs/developers_guide/StreamingLiteComponents.md
> Lite components docs

- docs/scenarios_authoring/AggregatesInTimeWindows.md
> Flink only added; link fixed

- defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/migrations/ProcessSplitterMigration.scala
- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/ForEachTransformer.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/ForEachTransformerSpec.scala
> Add missing split -> for-each migration

- defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/migrations/ProcessSplitterMigration.scala
- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/ForEachTransformer.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/ForEachTransformerSpec.scala
> Add missing split -> for-each migration (#2824)

- docs/Changelog.md
> Fix flink update entry in changelog

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
> Set runtime image strictly

- defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/migrations/UnionParametersMigration.scala
> Fix UnionParametersMigration package name

- defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/migrations/UnionParametersMigration.scala
> Fix UnionParametersMigration package name (#2833)

- docs/installation_configuration_guide/DeploymentManagerConfiguration.md
> Add docs for nussknacker instance name label

- docs/developers_guide/Basics.md
- docs/installation_configuration_guide/DesignerConfiguration.md
- docs/installation_configuration_guide/Installation.md
- docs/installation_configuration_guide/README.md
> Fix broken links

- build.sbt
- interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
> Add flinkExtensionsApi to published modules

- dockerhub/nussknacker-lite-kafka-runtime/README.md
- dockerhub/nussknacker-lite-kafka-runtime/short.txt
- dockerhub/nussknacker-request-response-app/README.md
- dockerhub/nussknacker-request-response-app/short.txt
- dockerhub/nussknacker/README.md
- dockerhub/nussknacker/short.txt
- dockerhub/pulishReadme.sh
- engine/lite/kafka/runtime/src/universal/bin/nu-kafka-engine-entrypoint.sh
- engine/lite/kafka/runtime/src/universal/conf/application.conf
- release.sh
+ initial docs for nussknacker-lite-kafka-runtime and nussknacker-request-response-app
> Script updating dockerhub docs

- ui/client/containers/CustomTab.tsx
- ui/submodules/.babelrc
- ui/submodules/configs/webpack/common.ts
- ui/submodules/configs/webpack/withModuleFederationPlugins.ts
- ui/submodules/package-lock.json
- ui/submodules/package.json
- ui/submodules/packages/components/i18next-parser.config.js
- ui/submodules/packages/components/package.json
- ui/submodules/packages/components/src/settings/i18n.ts
- ui/submodules/packages/components/tsconfig.json
- ui/submodules/packages/components/webpack.config.ts
> better handled relative module paths

- build.sbt
> Add missing module 

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
> Add container spec override tests

- build.sbt
- ui/client/containers/Processes.tsx
> Component-api artifact name, small FE fix

- engine/lite/k8sDeploymentManager/src/main/resources/defaultMinimalDeployment.conf
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentUtils.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
> Make specifying runtime container image unnecessary

- components/sql/src/test/scala/pl/touk/nussknacker/sql/service/DatabaseLookupLiteRuntimeTest.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/RequestResponseEmbeddedDeploymentManagerTest.scala
- engine/lite/request-response/app/src/test/scala/pl/touk/nussknacker/engine/requestresponse/http/RequestResponseHttpAppSpec.scala
- engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/deployment/DeploymentServiceSpec.scala
- engine/lite/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/sample.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/EspProcessBuilder.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
> Common builder declaration

- docs/developers_guide/StreamingLiteComponents.md
- docs/installation_configuration_guide/Installation.md
- docs/installation_configuration_guide/model/Flink.md
- docs/operations_guide/Common.md
- docs/operations_guide/Flink.md
- docs/operations_guide/Lite.md
- docs/scenarios_authoring/AggregatesInTimeWindows.md
- docs/scenarios_authoring/DesignerTipsAndTricks.md
- docs/scenarios_authoring/Intro.md
> [DOCS] Engines comparison

- docs/operations_guide/Lite.md
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/BaseNuKafkaRuntimeDockerTest.scala
- engine/lite/kafka/runtime/src/universal/conf/docker-logback.xml
- utils/test-utils/src/main/resources/logback-test.xml
> Logging docs

- nussknacker-dist/src/universal/bin/nussknacker-entrypoint.sh
> Remove uncecessary chmod in docker entrypoint

- build.sbt
- docs/Changelog.md
Fix very important bug: https://issues.apache.org/jira/browse/FLINK-25732. Issue with running taskmanagers in cluster mode..
> Update flink to 1.14.4

- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/RequestResponseDeploymentStrategy.scala
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/RequestResponseAkkaHttpHandler.scala
> Initialize RequestResponseHandler only once

- engine/flink/components/base/src/it/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformerSpec.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformersExceptionHandlingSpec.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionWithMemoTransformerSpec.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/ModelUtilExceptionHandlingSpec.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/SingleSideJoinTransformerSpec.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/functional/ProcessSpec.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMainSpec.scala
- engine/lite/components/base/src/test/scala/pl/touk/nussknacker/engine/lite/components/UnionTest.scala
- engine/lite/kafka/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaTransactionalScenarioInterpreterTest.scala
- engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreterSpec.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/PartSortSpec.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/processreport/ProcessCounterTest.scala
> Rename branch to union in scenario builder

- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/FlinkStreamingProcessRegistrarOperatorUidSpec.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/FlinkStreamingProcessRegistrarSpec.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/functional/ProcessSpec.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/ScenarioBuilder.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
> Use ScenarioBuilder where possible

- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/RequestResponseDeploymentStrategy.scala
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/RequestResponseAkkaHttpHandler.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/RequestResponseEmbeddedDeploymentManagerTest.scala
> Correct handling of decoding errors in RequestResponse

- build.sbt
> Add logback-json for easier log configuration

- engine/lite/kafka/runtime/src/universal/conf/docker-logback.xml
> Remove flink reference in docker-logback.xml

- ui/client/actions/nk/nodeDetails.ts
- ui/client/components/graph/node-modal/NodeAdditionalInfoBox.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent.js
- ui/client/components/graph/node-modal/NodeDetailsContent/NodeDetails.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent/NodeDetailsContentConnected.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent/helpers.ts
- ui/client/components/graph/node-modal/NodeDetailsContent/selectors.tsx
- ui/client/reducers/nodeDetailsState.ts
- ui/client/types/definition.ts
- ui/client/types/node.ts
- ui/client/types/process.ts
> reset validation on window close

- docs/MigrationGuide.md
- engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkProcessStateDefinitionManager.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleProcessStateDefinitionManager.scala
- ui/deployment-manager-api/src/test/scala/pl/touk/nussknacker/engine/api/deployment/SimpleProcessStateSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
> [K8 engine] allow redeploy during deploy

- docs/operations_guide/Common.md
- docs/scenarios_authoring/DataSourcesAndSinks.md
> Improve avro serialization docs

- docs/installation_configuration_guide/DeploymentManagerConfiguration.md
- docs/installation_configuration_guide/ModelConfiguration.md
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/test/Waiting30SecsCheck.scala
> Fix docs & comment

- ui/client/components/graph/Graph.js
> update graph export data

- ui/server/src/main/scala/pl/touk/nussknacker/ui/util/PdfExporter.scala
> Node details PDF generation fix

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentStatusMapper.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sProcessStateDefinitionManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sStateStatus.scala
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/podsCrashLoopBackOff.json
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentStatusMapperSpec.scala
> Introduce Restarting status to K8 deploymentManager

- docs/developers_guide/Components.md
- docs/developers_guide/FlinkComponents.md
- docs/developers_guide/StreamingLiteComponents.md
- docs/developers_guide/Testing.md
> Testing components docs

- interpreter/src/main/scala/pl/touk/nussknacker/engine/types/EspTypeUtils.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala
- utils/utils/src/main/java/org/springframework/util/NumberUtils.java
Plus fix one two compiler warnings about use of deprecated BigDecimal methods
> Add test for Scala's primitive type erasure in generics

- docs/MigrationGuide.md
- docs/installation_configuration_guide/DesignerConfiguration.md
- security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/GenericOidcServiceSpec.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectProfile.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationConfiguration.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcService.scala
- security/src/test/resources/oidc-sample1.json
- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectUserInfoSpec.scala
> [Security] Configuring multiple roleClaims for OIDC

- build.sbt
> Publish testkits

- ui/submodules/packages/components/src/components/cellRenderers/categoriesCell.tsx
> fixed error when hiding categories column

- ui/submodules/package-lock.json
- ui/submodules/packages/components/package.json
- ui/submodules/packages/components/src/common/scenarioHref.tsx
> fixed regex error in safari

- build.sbt
- components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/OpenApiScenarioIntegrationTest.scala
- engine/flink/components/base/src/it/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformerSpec.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractor.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/testmode/TestComponentsHolder.scala
- utils/components-testkit/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.api.component.ComponentProvider
- utils/components-testkit/src/main/scala/pl/touk/nussknacker/engine/util/test/ModelWithTestComponents.scala
- utils/components-testkit/src/main/scala/pl/touk/nussknacker/engine/util/test/TestScenarioRunner.scala
- utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkTestScenarioRunner.scala
- utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunner.scala
- utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/RequestResponseTestScenarioRunner.scala
- utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/SynchronousLiteInterpreter.scala
- utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/minimalLiteRuntime.scala
- utils/lite-components-testkit/src/test/resources/META-INF/services/pl.touk.nussknacker.engine.api.component.ComponentProvider
- utils/lite-components-testkit/src/test/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunnerSpec.scala
> test API small enhancements

- ui/client/cypress/integration/components.ts
- ui/submodules/packages/components/src/common/scenarioHref.tsx
> fixed links to nu in submodules

- docs/Changelog.md
- docs/MigrationGuide.md
- extensions-api/src/main/scala/pl/touk/nussknacker/security/Permission.scala
- extensions-api/src/main/scala/pl/touk/nussknacker/security/api/GlobalPermission.scala
- extensions-api/src/main/scala/pl/touk/nussknacker/security/api/Permission.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationConfiguration.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/api/GlobalPermission.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/api/RulesSet.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/api/LoggedUserTest.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/api/RulesSetSpec.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/DefaultOAuth2ServiceFactorySpec.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AuthorizeProcess.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AuthorizeProcessDirectives.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ServiceRoutes.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/UserResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessCategoryService.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessDBQueryRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ServiceRoutesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockFetchingProcessRepository.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestPermissions.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepositorySpec.scala
`pl.touk.nussknacker.ui.security.api.Permission` (security module) moved to `pl.touk.nussknacker.security.Permission` (extension-api module)
> Improvements: Extract Security Api

- utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/cache/DefaultCache.scala
- utils/utils/src/test/scala/pl/touk/nussknacker/engine/util/cache/DefaultCacheTest.scala
It overrides access deadline instead of preserving
> Refactor of cashing mechanism: clarification of current None expireAfterWrite handling + test

- components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/OpenAPIServiceSpec.scala
- components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/OpenApiScenarioIntegrationTest.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/OpenAPIsConfig.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/SwaggerParser.scala
- components/openapi/src/test/resources/swagger/multiple-operations.yml
- components/openapi/src/test/scala/pl/touk/nussknacker/openapi/OpenAPIComponentProviderTest.scala
> Fix OpenAPI config parsing

- ui/submodules/packages/components/src/scenarios/filters/optionsStack.tsx
- ui/submodules/packages/components/src/scenarios/filters/scenariosFiltersModel.ts
- ui/submodules/packages/components/src/scenarios/filters/simpleOptionsStack.tsx
- ui/submodules/packages/components/src/scenarios/filters/sortOptionsStack.tsx
- ui/submodules/packages/components/src/scenarios/list/itemsList.tsx
> fixed sort in new scenarios

- docs/operations_guide/Flink.md
> fix docs after moving attachments to db

- ui/submodules/packages/components/src/common/parentNavigationProvider.tsx
- ui/submodules/packages/components/src/common/scenarioHref.tsx
> fix(components): better public path in links

- build.sbt
- engine/lite/kafka/runtime/src/universal/bin/nu-kafka-engine-entrypoint.sh
- engine/lite/kafka/runtime/src/universal/bin/run.sh
- engine/lite/kafka/runtime/src/universal/conf/jmx_prometheus.yaml
- nussknacker-dist/src/universal/bin/nussknacker-entrypoint.sh
- nussknacker-dist/src/universal/bin/run.sh
- nussknacker-dist/src/universal/conf/jmx_prometheus.yaml
- project/plugins.sbt
> Add PrometheusJmxExporter to docker images

- docs/Changelog.md
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtOAuth2Service.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtValidator.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Authenticator.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationConfiguration.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcService.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oidc/OidcServiceSpec.scala
> OIDC: More precise error messages during JWT validation

- docs/Changelog.md
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtOAuth2Service.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtValidator.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Authenticator.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/jwt/JwtValidator.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/jwt/ParsedJwtToken.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/jwt/RawJwtToken.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcService.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oidc/OidcServiceSpec.scala
- utils/utils-internal/src/main/scala/pl/touk/nussknacker/engine/util/SensitiveDataMasker.scala
- utils/utils-internal/src/test/scala/pl/touk/nussknacker/engine/util/SensitiveDataMaskerTest.scala
> Jwt symmetric encoding

- ui/submodules/configs/webpack/dev.ts
- ui/submodules/package-lock.json
- ui/submodules/packages/components/package.json
- ui/submodules/packages/components/src/components/utils/truncateWrapper.tsx
- ui/submodules/packages/components/webpack.config.ts
> fix: truncate all elements (empty cell)

- ui/client/components/toolbars/edit/buttons/PasteButton.tsx
- ui/client/components/withFocus.tsx
> fix: paste button

- version.sbt
> set version to 1.5.0-SNAPSHOT

- engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/aggregates.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregatesSpec.scala
Corrected the way zeros are handled in First and Last aggregator.
> Aggregates correct zeros

- ui/buildClient.sh
- ui/client/components/graph/SubProcessGraph.tsx
- ui/client/components/graph/node-modal/NodeAdditionalInfoBox.tsx
- ui/client/components/graph/node-modal/node/NodeDetails.tsx
- ui/client/components/graph/node-modal/node/SubprocessContent.tsx
- ui/client/components/graph/node-modal/node/selectors.tsx
- ui/client/containers/Visualization.js
- ui/client/containers/theme.tsx
- ui/client/http/HttpService.ts
- ui/client/package-lock.json
- ui/client/package.json
- ui/client/reducers/selectors/graph.ts
- ui/client/webpack.config.js
> fix: node windows error flickering

- ui/client/components/graph/NodeUtils.ts
- ui/client/types/edge.ts
> emoji in filter links

- engine/flink/components/base/src/main/java/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregateHelper.java
Change of one line to fix bug where selecting first or sum aggregator works incorrectly.
> Fixed selecting sum as parameter

- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
see https://github.com/TouK/nussknacker/pull/3126
> Fix version id in fetchProcessVersion request to the remote env

- ui/client/actions/nk/assignSettings.ts
- ui/client/components/CommentInput.tsx
- ui/client/components/modals/DeployProcessDialog.tsx
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
> added placeholder with example comment for deployment comment

- ui/client/containers/AdminPage.js
- ui/client/containers/admin/Services.js
> fix: admin tab styles

- docs/Changelog.md
- docs/MigrationGuide.md
> Set version to 1.4.0

- version.sbt
> Set version to 1.4.1 snapshot

- ui/client/components/ProcessAttachments.tsx
- ui/client/http/HttpService.ts
> Download attachment with correct API

- ui/client/cypress/integration/components.ts
> another flaky test fix

- security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationConfiguration.scala
> OIDC config fix

- docs/installation_configuration_guide/DesignerConfiguration.md
> Fix typo in designer config example

- docs/Changelog.md
- docs/MigrationGuide.md
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
> Exposing simple health check endpoint publicly

- docs/Changelog.md
> fix changelog

- ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.tsx
> fixed bug showing wrong row value after removing a row in MapVariable 

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sPodsResourceQuotaChecker.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sPodsResourceQuotaCheckerTest.scala
> Better message when K8 resource quota exceeded

- docs/Changelog.md
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/CachingOAuth2Service.scala
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactorySpec.scala
- utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/cache/Cache.scala
- utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/cache/DefaultCache.scala
- utils/utils/src/test/scala/pl/touk/nussknacker/engine/util/cache/DefaultCacheTest.scala
> Fix set maxAge

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala
> Fix k8 cleanup in K8sDeploymentManagerProviderTest

- scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/EdgeType.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
> Do not require switch edge uniqueness

- engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/util/source/CollectionSource.scala
- engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/util/source/ReturningClassInstanceSource.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/TestFlinkProcessCompiler.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMain.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompilerTest.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/helpers/ProcessTestHelpers.scala
- engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/BoundedSource.scala
- engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/DynamicParametersSource.scala
- engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/GenericSourceWithCustomVariablesSample.scala
- engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/SqlSource.scala
- engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/CorrectExceptionHandlingSpec.scala
- engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/process/helpers/BaseSampleConfigCreator.scala
- engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
- utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkTestScenarioRunner.scala
> Simplify CollectionSource

- docs/Changelog.md
- engine/flink/components/kafka/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProvider.scala
- engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaComponentProvider.scala
- ui/client/cypress/integration/components.ts
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/UniversalKafkaSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/UniversalKafkaSourceFactory.scala
> Universal kafka components: handling both avro and json - inital work

- build.sbt
- docs/Changelog.md
- docs/MigrationGuide.md
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/AbstractConfluentKafkaAvroSerializer.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroDeserializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroDeserializer.scala
> confluent 5.5->7.2, avro 1.9->1.11 bumps

- docs/MigrationGuide.md
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/functional/MetricsSpec.scala
- engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/process/functional/TestReporter.scala
> Fix MetricsSpec

- engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/GenericItSpec.scala
> Temporary GenericItSpec fix

- docs/Changelog.md
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/CachingOAuth2Service.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/CachingOAuth2ServiceSpec.scala
> CachingOAuth2Service fix: populate cache fully synchronously

- .github/workflows/pr.yml
- engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/GenericItSpec.scala
> temporarly increase log level for Flink classes in tests

- ui/client/components/graph/node-modal/MapVariable.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent/helpers.ts
- ui/client/components/graph/node-modal/SubprocessOutputDefinition.tsx
- ui/client/components/graph/node-modal/Variable.tsx
- ui/client/components/graph/node-modal/node/NodeDetails.tsx
> hide validation errors of invisible fields

- utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaClient.scala
> Kafka test utils fix: logging errors during sending messages

- ui/client/reducers/graph/reducer.ts
> preserve typing info after failed validation

- build.sbt
- docs/MigrationGuide.md
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/helpers/SchemaRegistryMixin.scala
- engine/flink/management/dev-model/src/test/scala/pl/touk/nussknacker/engine/process/NamespacedKafkaSourceSinkTest.scala
- engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/FlinkWithKafkaSuite.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/StreamingEmbeddedDeploymentManagerRestartTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeBinTest.scala
- utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/EmbeddedKafkaServer.scala
- utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaSpec.scala
> Using kafka raft instead of zk

- engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/GenericItSpec.scala
> Logging input topic messages for GenericItSpec flaky tests diagnosis

- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaAvroFunctionalTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeDockerAvroTest.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/AvroUtils.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/encode/BestEffortAvroEncoder.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentUtils.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/AbstractConfluentKafkaAvroSerializer.scala
- utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/LiteKafkaTestScenarioRunner.scala
* add discovering schema based on data..
* fix deserialization payload at `ConfluentUtil.deserializeSchemaIdAndData`
* alignment to the new version of confluent nad add support for ByteBuffer on serialization
> Improvements: avro utils

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/AvroNodesClassloadingSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroNamespacedSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroTestProcessConfigCreator.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaJsonPayloadIntegrationSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/helpers/KafkaAvroSpecMixin.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroSeDeSpecMixin.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/sink/flink/KafkaAvroSinkExceptionHandlingSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/sink/flink/KafkaAvroSinkFactoryWithEditorIntegrationTest.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/source/flink/DelayedKafkaAvroIntegrationSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/source/flink/KafkaJsonPayloadSourceFactorySpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/source/flink/TestFromFileSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/source/flink/TopicSelectionStrategySpec.scala
- engine/flink/components/kafka/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProvider.scala
- engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
- engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/MockFlinkKafkaComponentProvider.scala
- engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaComponentProvider.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseTransformer.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/BaseSchemaRegistryProvider.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaBasedMessagesSerdeProvider.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentAvroSchemaBasedMessagesSerdeProvider.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactoryWithEditor.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/UniversalKafkaSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/SpecificRecordKafkaAvroSourceFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/UniversalKafkaSourceFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/delayed/DelayedKafkaAvroSourceFactory.scala
* rename SchemaRegistryProvider -> SchemaBasedMessagesSerdeProvider
* decouple BaseSchemaRegistryProvider from SchemaBasedMessagesSerdeProvider
> SchemaRegistryProvider refactoring

- e2e-tests/docker-compose.yml
> Fix redpanda repo

- docs/LicenseInfo.md
> License info doc - first version

- docs/scenarios_authoring/BasicNodes.md
> Docs fixes: choice image urls fixed

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroSerializationSpec.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentSchemaBasedSerdeProvider.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/jsonpayload/ConfluentJsonPayloadSerializerFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaDeserializerFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/serialization/KafkaSchemaBasedKeyValueSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/serialization/KafkaSchemaBasedSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactoryWithEditor.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/UniversalKafkaSinkFactory.scala
* Refactor KafkaSchemaBasedSerializationSchemaFactory - use ParseSchema instead of AvroSchema
* add ConfluentUniversalKafkaSerializationSchemaFactory
> Introduce serialization factory for Universal Kafka components

- engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
- engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/ClassExtractionBaseTest.scala
- engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
> class extraction settings - expectations aligned with results

- engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/GenericItSpec.scala
> Explicitly send message on topic to not depend on logging configuration

- ui/submodules/packages/components/src/common/nuIcon.tsx
> changed svg filters/masks

- build.sbt
- utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/typing/JsonToTypedMapConverter.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/serde/CirceJsonDeserializer.scala
- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/serde/CirceJsonDeserializerSpec.scala
> Json serde

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/helpers/KafkaWithSchemaRegistryOperations.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroSerializationSpec.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/BasedOnVersionAvroSchemaDeterminer.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroToJsonFormatterFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/jsonpayload/ConfluentJsonPayloadSerializerFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaDeserializerFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaSerde.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/serialization/KafkaSchemaBasedKeyValueSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/serialization/KafkaSchemaBasedSerializationSchemaFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactoryWithEditor.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/UniversalKafkaSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/UniversalKafkaSourceFactory.scala
> pass schemaId to kafka headers when serializing data in kafka sinks

- docs/Changelog.md
- docs/MigrationGuide.md
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/AvroSchemaDeterminer.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/BasedOnVersionAvroSchemaDeterminer.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentSchemaBasedSerdeProvider.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroMessageFormatter.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroToJsonFormatterFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/UniversalMessageFormatter.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/UniversalMessageReader.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/UniversalToJsonFormatterFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/UniversalKafkaSourceFactory.scala
> introduce UniversalToJsonFormatterFactory

- .github/workflows/pr.yml
- build.sbt
- project/plugins.sbt
This change builds amd64 image on platforms other that amd.
Building multiple platforms images to be done in future
> Cross platform docker publish

- ui/client/common/ProcessUtils.ts
- ui/client/common/enumUtils.ts
- ui/client/components/graph/node-modal/EdgeTypeSelect.tsx
- ui/client/components/graph/node-modal/EdgesDndComponent.tsx
- ui/client/components/graph/node-modal/NodeDetailsContent.tsx
- ui/client/types/edge.ts
> Choice fe fixes

- ui/client/stylesheets/select.styl
> Remove unnecessary padding in dropdown

- ui/client/components/graph/node-modal/EdgeFields.tsx
> fixed double "true" in filter

- ui/client/components/modals/DeployProcessDialog.tsx
- ui/client/containers/Notifications.tsx
- ui/server/src/main/scala/pl/touk/nussknacker/ui/notifications/Notification.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/notifications/NotificationService.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
> Fix status refresh on fail

- ui/client/containers/Notifications.tsx
> Fix notification refresh

- ui/client/cypress/support/process.ts
> remove metadata (name) change when importing test data

- ui/client/cypress/integration/process.ts
> Cypress fix

- docs/Changelog.md
- engine/flink/components/kafka/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProvider.scala
- engine/flink/tests/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProviderTest.scala
- engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaComponentProvider.scala
- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaComponentProviderTest.scala
- utils/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/KafkaConfigSpec.scala
- utils/kafka-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaConfig.scala
> Add low level components based on configuration

- utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/service/TimeMeasuringService.scala
> Fix asynchronous service metrics

- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ObsoleteStateDetector.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestProcessChangeListener.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestProcessUtil.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
> Management actor extract

- .github/workflows/pr.yml
> fix test reports

- build.sbt
> [FIX] Add module 'liteKafkaComponents' to root module

- docs/Changelog.md
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/helpers/UniversalKafkaSpecMixin.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/sink/flink/KafkaAvroSinkImplFactorySpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/sink/flink/UniversalKafkaSinkValidationSpec.scala
- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaAvroSchemaFunctionalTest.scala
- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/UniversalSourceAvroSchemaLiteTest.scala
- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/UniversalSourceJsonSchemaLiteTest.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseComponentTransformer.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/encode/AvroSchemaOutputValidator.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/encode/JsonSchemaOutputValidator.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/encode/JsonSchemaOutputValidatorPrinter.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/UniversalSchemaSupport.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/UniversalKafkaSinkFactory.scala
> Raw mode in KafkaUniversalSink

- build.sbt
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/HandleResponse.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/ParametersExtractor.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/ServiceRequest.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/package.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseToSwaggerService.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseToSwaggerServices.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/SwaggerParser.scala
- components/openapi/src/test/scala/pl/touk/nussknacker/openapi/extractor/JsonToObjectTest.scala
- components/openapi/src/test/scala/pl/touk/nussknacker/openapi/parser/SwaggerParserTest.scala
- docs/Changelog.md
- docs/MigrationGuide.md
- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/UniversalSourceJsonSchemaLiteTest.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ParsedSchemaSupport.scala
- utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/UniversalSchemaSupport.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/JsonSchemaTypeDefinitionExtractor.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractor.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/serde/CirceJsonDeserializer.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/extractor/JsonToObject.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/parser/ParseSwaggerRefSchemas.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/parser/parser.scala
- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/JsonSchemaTypeDefinitionExtractorTest.scala
- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractorTest.scala
- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/serde/CirceJsonDeserializerSpec.scala
> Switch to swagger based typing and deserialization to typed map

- build.sbt
> Resolve conflict during ui publish

- build.sbt
> Resolve conflict during requestResponseApp publish

- docs/Changelog.md
- extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ExpressionConfig.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
> Array indexer fix

- interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
> Refactor: Even less parse method variants in SpelExpressionSpec

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroPayloadIntegrationSpec.scala
- engine/flink/avro-components-utils/src/test/scala/pl/touk/nussknacker/engine/avro/schema/PaymentNotCompatible.scala
- engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/DelayedFlinkKafkaConsumer.scala
- engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/FlinkKafkaDelayedSourceImplFactory.scala
- engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/serialization/FlinkSerializationSchemaConversions.scala
- engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryIntegrationSpec.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryProcessMixin.scala
- engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/MiniClusterExecutionEnvironment.scala
> (Flink) Handling kafka source deserialization errors by exceptionHandler

- docs/Changelog.md
- security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala
- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResourcesSpec.scala
> create http cookies with 'secure' attribute set to 'true'

- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/UnivseralSourceJsonFunctionalTest.scala
- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/utils/JsonTestData.scala
> Json functional tests

- build.sbt
- docs/Changelog.md
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/DeploymentStrategy.scala
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/RequestResponseDeploymentStrategy.scala
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/streaming/StreamingDeploymentStrategy.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/BaseNuRuntimeBinTestMixin.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeBinTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeTestMixin.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuReqRespRuntimeBinTest.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/RunnableScenarioInterpreterFactory.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/HealthCheckServerRunner.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaTransactionalScenarioInterpreter.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/LoopUntilClosed.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeApp.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/RequestResponseConfig.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/RequestResponseRunnableScenarioInterpreter.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/ScenarioRoute.scala
- engine/lite/kafka/runtime/src/universal/conf/application.conf
- engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/RunnableScenarioInterpreter.scala
- engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/TaskStatus.scala
> Request-response runtime - working bin test

- build.sbt
> Check result of fe build

- docs/Changelog.md
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/exception/DeployingInvalidScenarioError.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesExportImportResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ValidationResourcesSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/SampleFragment.scala
> validate scenario before deploy

- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/BaseNuKafkaRuntimeDockerTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeBinTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeDockerAvroTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeDockerJsonTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeDockerProbesTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeTestMixin.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuReqRespRuntimeBinTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuReqRespRuntimeDockerTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuRuntimeDockerTestUtils.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuRuntimeTestUtils.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/sample/NuKafkaRuntimeTestSamples.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/sample/NuReqRespTestSamples.scala
> Request-response runtime - working docker test

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/CommonSupertypeFinder.scala
- components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultSpec.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
> Generic params fix

- ui/server/src/main/scala/pl/touk/nussknacker/ui/notifications/NotificationService.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
> Fix deployment notification

- defaultModel/src/main/resources/defaultModelConfig.conf
> Fix choice docsUrl

- engine/lite/components/kafka/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaAvroSchemaFunctionalTest.scala
- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/AvroSchemaOutputValidator.scala
- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/JsonSchemaOutputValidator.scala
> Avro lax accept unknown

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
- engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
- interpreter/src/main/scala/pl/touk/nussknacker/engine/types/EspTypeUtils.scala
- interpreter/src/test/java/pl/touk/nussknacker/engine/types/JavaClassWithFilteredMethod.java
- interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala
Fixed bug where method filter in EspTypeUtils did not check for types like List[UndesiredType]
> Corrected method filter for generic types

- ui/client/containers/Services.js
> Fix: styles on services tab

- build.sbt
- docs/Changelog.md
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/RequestResponseDeploymentStrategy.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/BaseNuKafkaRuntimeDockerTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeBinTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeTestMixin.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuReqRespRuntimeDockerTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/requestresponse/NuReqRespRuntimeBinTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/requestresponse/NuReqRespRuntimeDockerTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/requestresponse/sample/NuReqRespTestSamples.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/utils/BaseNuRuntimeBinTestMixin.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/utils/NuRuntimeDockerTestUtils.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/utils/NuRuntimeTestUtils.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/RequestResponseConfig.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/RequestResponseRunnableScenarioInterpreter.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/requestresponse/ScenarioRoute.scala
- engine/lite/kafka/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/requestresponse/ScenarioRouteSpec.scala
- engine/lite/request-response/components-api/src/main/scala/pl/touk/nussknacker/engine/requestresponse/api/openapi/RequestResponseOpenApiSettings.scala
- engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreter.scala
- engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/openapi/RequestResponseOpenApiGenerator.scala
- engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/openapi/StandaloneOpenApiDataModel.scala
> request-response scenario's openApi definition endpoint

- docs/operations_guide/Common.md
- engine/flink/components/kafka/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProvider.scala
- engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaComponentProvider.scala
> Cleanup old docs references

- docs/Changelog.md
- docs/developers_guide/Basics.md
- utils/utils-internal/src/main/scala/pl/touk/nussknacker/engine/util/loader/ModelClassLoader.scala
- utils/utils-internal/src/test/scala/pl/touk/nussknacker/engine/util/loader/ModelClassLoaderSpec.scala
> Extra components placeholder dir

- security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/CachingOAuth2ServiceSpec.scala
> fix CachingOAuth2ServiceSpec

- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractorTest.scala
> test for type extraction of nested json schema

- build.sbt
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/utils/BaseNuRuntimeBinTestMixin.scala
- utils/test-utils/src/main/scala/pl/touk/nussknacker/test/ProcessUtils.scala
> ProcessUtils for tests purpose

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
> type-safe casting of TypingResult.valueOpt

- .github/workflows/pr.yml
- .k3d/single-cluster.yml
- engine/lite/k8sDeploymentManager/src/test/resources/application.conf
- utils/test-utils/src/main/resources/logback-test.xml
> Bump k3d abr

- .github/workflows/pr.yml
- .k3d/single-cluster.yml
- utils/test-utils/src/main/resources/logback-test.xml
> Revert "Bump k3d abr"

- build.sbt
- dockerhub/nussknacker-lite-kafka-runtime/README.md
- dockerhub/pulishReadme.sh
- docs/installation_configuration_guide/DeploymentManagerConfiguration.md
- docs/operations_guide/Lite.md
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/test/resources/deployment/deploymentFull.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/inProgress.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/podsCrashLoopBackOff.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/progressFailed.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/running.json
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerKafkaTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
- engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/utils/NuRuntimeDockerTestUtils.scala
- engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/NuRuntimeApp.scala
- engine/lite/kafka/runtime/src/universal/bin/nu-kafka-engine-entrypoint.sh
- engine/lite/kafka/runtime/src/universal/bin/run.sh
> Remove kafka from main class name

- CONTRIBUTING.md
- build.sbt
> Copy ui dist in one task instead of two: copyUiDist, copyUiSubmodulesDist

- nussknacker-dist/src/universal/conf/dev-application.conf
> set RR-K8 dashboard name in dev-application.conf

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/LiteScenarioValidator.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/RequestResponseSlugUtils.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/service/ServicePreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/LiteScenarioValidatorTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/RequestResponseSlugUtilsTest.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/ScenarioBuilder.scala
> Lazy determined slug sanitized like eager version

- docs/installation_configuration_guide/ModelConfiguration.md
- docs/installation_configuration_guide/model/Flink.md
- docs/installation_configuration_guide/model/Lite.md
- docs/integration/KafkaIntegration.md
> Kafka doc refactor

- nussknacker-dist/src/universal/conf/dev-application.conf
> Update rr metrics mapping

- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/WebResources.scala
> GZIP content + Cache-Control header

- ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
> Fix app startup when failed embedded scenario

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala
- engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerProvider.scala
- engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkStreamingDeploymentManagerProvider.scala
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/EmbeddedDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/request-response/components-api/src/main/scala/pl/touk/nussknacker/engine/requestresponse/api/openapi/RequestResponseOpenApiSettings.scala
- engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/management/RequestResponseDeploymentManager.scala
- nussknacker-dist/src/universal/conf/application.conf
- nussknacker-dist/src/universal/conf/dev-application.conf
- ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/DeploymentManagerProvider.scala
- ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/testing/DeploymentManagerStub.scala
- ui/server/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeData.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentService.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactorySpec.scala
> Additional properties in code

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
> Deployment strategy base on scenario typeSpecificData

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sPodsResourceQuotaChecker.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sPodsResourceQuotaCheckerTest.scala
> Check max surge when validating K8s deployment

- ui/client/components/graph/node-modal/IdField.tsx
- ui/client/components/graph/node-modal/editors/Validators.ts
- ui/client/reducers/selectors/graph.ts
> validate node id

- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala
> Fix for flaky test in ManagementActorSpec

- .github/workflows/pr.yml
> Trigger sample components + flink-compat builds

- docs/installation_configuration_guide/DesignerConfiguration.md
- ui/client/actions/nk/assignSettings.ts
- ui/client/components/toolbars/process/buttons/ArchiveButton.tsx
- ui/client/components/toolbars/process/buttons/UnArchiveButton.tsx
- ui/client/http/HttpService.ts
- ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfig.scala
> Sync with 1.5

- engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
> Flink DM: checking of slots doulbe instead of triple - no api changes

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala
> Delete RR service by listing selected instead of deletecollection

- ui/submodules/package.json
> fixed dev start script for submodules

- docs/integration/KafkaIntegration.md
- nussknacker-dist/src/universal/conf/dev-application.conf
> Update KafkaIntegration docs

- CONTRIBUTING.md
- dockerhub/pulishReadme.sh
- e2e-tests/setupAndRun.sh
- e2e-tests/waitForOk.sh
- ui/buildClient.sh
- ui/buildServer.sh
- ui/client/README.md
> Dev setup improvements

- ui/client/app.styl
- ui/client/containers/Services.js
* Fix scroll in services tab
* Fix scroll in services tab - fixes
> Fix services tab 1.5 (#3537)

- ui/client/actions/notificationActions.tsx
- ui/client/containers/Notifications.tsx
- ui/client/http/HttpService.ts
> UI: error response notification crash fix

- ui/client/components/toolbarSettings/buttons/ActionButton.tsx
- ui/client/components/toolbars/status/ProcessInfo.tsx
- ui/client/reducers/graph/reducer.ts
- ui/client/reducers/graph/types.ts
- ui/client/reducers/index.ts
- ui/client/reducers/scenarioState.ts
- ui/client/reducers/selectors/graph.ts
- ui/client/reducers/selectors/other.ts
- ui/client/reducers/selectors/scenarioState.ts
> Undo no longer messes scenario state

- ui/client/components/toolbarSettings/buttons/ActionButton.tsx
- ui/client/components/toolbars/status/ProcessInfo.tsx
- ui/client/reducers/graph/reducer.ts
- ui/client/reducers/graph/types.ts
- ui/client/reducers/index.ts
- ui/client/reducers/scenarioState.ts
- ui/client/reducers/selectors/graph.ts
- ui/client/reducers/selectors/other.ts
- ui/client/reducers/selectors/scenarioState.ts
> Undo fix backport

- .github/workflows/pr.yml
- .gitignore
- .k3d/single-cluster.yml
- CONTRIBUTING.md
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/ingress/IngressPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/ingress/IngressPreparerTest.scala
> RR: ingress handling improvements: better name, docs for k3d with nginx setup, gitignore

- docs/MigrationGuide.md
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/service/ServicePreparer.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala
- engine/lite/request-response/app/src/test/scala/pl/touk/nussknacker/engine/requestresponse/http/DeploymentServiceSpec.scala
- engine/lite/request-response/app/src/test/scala/pl/touk/nussknacker/engine/requestresponse/http/RequestResponseHttpAppSpec.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/ScenarioBuilder.scala
> Check slug uniqueness

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala
> Cleanup K8s service after slug change

- docs/installation_configuration_guide/DeploymentManagerConfiguration.md
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
- engine/lite/k8sDeploymentManager/src/test/resources/deployment/deploymentFull.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/inProgress.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/podsCrashLoopBackOff.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/progressFailed.json
- engine/lite/k8sDeploymentManager/src/test/resources/k8sResponses/running.json
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala
> Rename modelConfig.conf to runtimeConfig.conf

- ui/submodules/packages/components/src/scenarios/filters/quickFilter.tsx
> fix: unnecessary submit action on filters

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/FlinkScenarioNameValidator.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/FlinkScenarioNameValidationSpec.scala
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/PrettyValidationErrors.scala
> added description to error message for scenario name validation

- engine/lite/request-response/app/src/test/scala/pl/touk/nussknacker/engine/requestresponse/http/RequestResponseHttpOpenApi.scala
- engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreter.scala
- engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/openapi/RequestResponseOpenApiGenerator.scala
- engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/ScenarioRouteSpec.scala
> OpenAPI: generate operationId

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
- docs/Changelog.md
- docs/MigrationGuide.md
- engine/lite/components/base/src/test/scala/pl/touk/nussknacker/engine/lite/components/UnionTest.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerConfig.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProvider.scala
- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/LiteScenarioValidator.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerKafkaTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/RequestResponseScenarioValidatorTest.scala
- ui/client/actions/nk/nodeDetails.ts
- ui/client/components/graph/node-modal/IdField.tsx
- ui/client/components/graph/node-modal/properties.tsx
- ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/DeploymentManagerProvider.scala
- ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/PrettyValidationErrors.scala
- ui/server/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeData.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
- ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
- ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
> Move slug validation to DeploymentManager

- docs/installation_configuration_guide/Installation.md
> Update installation docs base image note

- engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/typeinformation/ConcreteCaseClassTypeInfo.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/InterpretationResultTypeInformation.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetection.scala
- engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/InputMetaTypeInformationProvider.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/InputMetaDeserializationSpec.scala
> Created common class for subclasses of CaseClassTypeInfo

- README.md
> Added one liner how to run embedded engine

- engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/util/source/CollectionSource.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/consumerrecord/ConsumerRecordDeserializationSpec.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryDefinitionExtractorSpec.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryMixin.scala
- engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/TestFromFileSpec.scala
> Fix testing from file with DisplayJsonWithEncoder

- .github/workflows/pr.yml
> trigger benchmark after publish + matrix for triggers

- designer/client/components/graph/node-modal/AdditionalProperty.tsx
- designer/client/components/graph/node-modal/editors/expression/JsonEditor.tsx
- engine/lite/request-response/components-api/src/main/scala/pl/touk/nussknacker/engine/requestresponse/api/openapi/RequestResponseOpenApiSettings.scala
> AdditionalProperties validation (also in JSON)

- .run/NussknackerApp.run.xml
- designer/client/package.json
> turn off reporting usage statistics in automated test setups

- designer/client/cypress/integration/components.ts
- designer/submodules/packages/components/src/common/filters/filtersContext.tsx
- designer/submodules/packages/components/src/scenarios/filters/filtersPart.tsx
- designer/submodules/packages/components/src/scenarios/filters/otherOptionsStack.tsx
> Scenarios filters update

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
> Better message when typing generic with illegal parameters

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
- components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultSpec.scala
- docs/Changelog.md
> Fix for: using Typed.fromDetailedType with scala type aliases cause exception

- engine/lite/request-response/app/src/main/scala/pl/touk/nussknacker/engine/requestresponse/http/RequestResponseHandler.scala
> Fix HttpApp

- docs/Changelog.md
- docs/developers_guide/LiteComponents.md
- docs/installation_configuration_guide/DeploymentManagerConfiguration.md
- docs/installation_configuration_guide/ModelConfiguration.md
- docs/integration/RequestResponse.mdx
- docs/scenarios_authoring/AggregatesInTimeWindows.md
- docs/scenarios_authoring/BasicNodes.md
- docs/scenarios_authoring/RRDataSourcesAndSinks.md
> Docs minor fixes

- designer/client/components/graph/node-modal/OutputParametersList.tsx
- designer/client/reducers/graph/reducer.ts
- designer/client/types/process.ts
- engine/lite/request-response/app/src/main/scala/pl/touk/nussknacker/engine/requestresponse/http/RequestResponseHandler.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/SubprocessResolverSpec.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/ScenarioBuilder.scala
> Fix fragment output

- designer/client/components/graph/node-modal/node/NodeGroupContent.tsx
- designer/client/components/graph/node-modal/node/selectors.tsx
- designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
- designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
- designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NodeResourcesSpec.scala
- docs/Changelog.md
> properties validation errors

- designer/client/components/graph/node-modal/OutputParametersList.tsx
> Fragment usages without outputVariableNames fix

- engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/PeriodicSourceFactory.scala
- engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/PeriodicSourceFactorySpec.scala
> Fix PeriodicSourceFactory typeInfo

- designer/server/src/main/scala/pl/touk/nussknacker/ui/api/WebResources.scala
- docs/integration/RequestResponse.mdx
> Reporting refferer & docs minor fixes

- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/InterpretationResultTypeInformation.scala
- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/SplitFunction.scala
- engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/ScenarioInterpreterFactory.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/InterpretationResult.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelConversionServiceOverrideSpec.scala
> Remove output from InterpretationResult

- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/ParsedSchemaSupport.scala
> Initialize encoder only once

- designer/server/src/main/scala/pl/touk/nussknacker/ui/api/WebResources.scala
- docs/Changelog.md
- docs/integration/RequestResponse.mdx
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/ScenarioDispatcherRoute.scala
- engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/RequestResponseEmbeddedDeploymentManagerTest.scala
> Fix req resp embedded staging

- docs/integration/OpenAPI.md
> Fix OpenAPI component config sample

- engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetection.scala
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetectionSpec.scala
> Fix TypingResultAware typing for fixed values

- engine/lite/components/request-response/src/main/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/jsonschema/sources/JsonSchemaRequestResponseSource.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/serde/CirceJsonDeserializer.scala
- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/serde/CirceJsonDeserializerSpec.scala
- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/ParsedSchemaSupport.scala
- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/OpenAPIJsonSchema.scala
- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/serialization/AbstractConfluentKafkaAvroDeserializer.scala
> Json deserialization optimize

- engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/LiteScenarioValidator.scala
- engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/RequestResponseScenarioValidatorTest.scala
> Fix fragment validation in ReqResponse

- nussknacker-dist/src/universal/conf/dev-application.conf
- nussknacker-dist/src/universal/conf/users.conf
> Change RR embedded category name

- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClient.scala
- utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClientFactory.scala
> More SchemaWithMetadata caching

- build.sbt
- docs/Changelog.md
- engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/JsonSchemaSubclassDeterminer.scala
> fix additionalProperties to use objectProperties instead of required

- engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
- engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/ScenarioDispatcherRoute.scala
> 1.6 fixes port

- designer/client/stylesheets/visualization.styl
> Fix: do not show extra scrollbar on scenario screen when panel to large

- designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentDefinitionPreparer.scala
- docs/Changelog.md
- interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
- scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/subprocess.scala
- scenario-api/src/test/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcessTest.scala
- scenario-api/src/test/scala/pl/touk/nussknacker/engine/graph/SubprocessRefSerializationSpec.scala
> fix backwards compatibility when validating scenarios with legacy fragments 

- docs/Changelog.md
- interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
> [FIX 1.6.1] fix validation of multiple same fragments in a row in legacy scenarios

- docs/Changelog.md
- interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
- interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
> [1.6.1] fix validation of multiple same fragments in a row in legacy scenarios

- docs/Changelog.md
- docs/MigrationGuide.md
- engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
- utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/RequestResponseTestScenarioRunner.scala
> TestScenarioRunner.requestResponseBased() api enhancements: returning scenario compilation errors as a ValidatedNel

- nussknacker-dist/src/universal/conf/application.conf
> Embedded engine dashboard mapping fix

- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/enrichers/SwaggerEnricher.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/http/backend/LoggingAndCollectingSttpBackend.scala
- components/openapi/src/test/resources/logback.xml
- designer/client/common/TestResultUtils.ts
- designer/client/components/graph/node-modal/tests/TestResults.tsx
- designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
- designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
- docs/Changelog.md
- docs/MigrationGuide.md
- docs/integration/OpenAPI.md
- engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMainSpec.scala
- engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/test/RequestResponseTestMainSpec.scala
- extensions-api/src/main/scala/pl/touk/nussknacker/engine/testmode/TestProcess.scala
- interpreter/src/main/scala/pl/touk/nussknacker/engine/testmode/TestServiceInvocationCollector.scala
- utils/utils-internal/src/main/scala/pl/touk/nussknacker/engine/util/LoggingListener.scala
> OpenAPI requests/response logging and collection

- utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/extractor/JsonToTypedMap.scala
- utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/swagger/extractor/JsonToTypedMapTest.scala
> Better JsonToTypeMap error

- components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypedMap.scala
> TypedMap comment fix

- designer/client/components/graph/node-modal/NodeTypeDetailsContent.tsx
> [FIX] Compare nodes doesn't crash

- components/openapi/src/it/resources/service-security.yml
- components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/SecurityTest.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/SwaggerSecurity.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/SecuritiesParser.scala
- docs/Changelog.md
> Full OpenAPI apiKey support

- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/OpenAPIComponentProvider.scala
- components/openapi/src/main/scala/pl/touk/nussknacker/openapi/discovery/SwaggerOpenApiDefinitionDiscovery.scala
> OpenAPI discovery small refactor, HOCON only in provider
