TouK/nussknacker

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/MetaData.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/marshall/ProcessMarshaller.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/marshall/ProcessMarshallerSpec.scala

This PR adds possibility to access additional fields from process meta data inside services. For now the fields are not deserialized and are None in the result. The downside is the fields are exposed as raw json that needs to be manually parsed but it is actually an instance of `ProcessAdditionalFields` from `restmodel` module.

Unmarshall process additional fields to raw json

---

engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
ui/client/http/HttpService.js

After job manager restart all uploaded jars cannot be longer used and we have to send them once again. This PR also fixes deployment error appearance on FE - currently deployment always seems to be successful which is not always a case.

Upload jar after job manager restart. Show deployment errors on FE

---

ui/client/components/Fields.js

Currently `field.name` is set as key of subprocess parameter list but this value is not immutable. This leads to frontend behaving odd on `field.name` change.

Unique id for subprocess parameters

---

engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/encode/BestEffortAvroEncoder.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompiledProcess.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilationError.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/SubprocessResolverSpec.scala
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/validated/ValidatedSyntax.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/util/PdfExporter.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/PrettyValidationErrors.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/TestMigrations.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala

Currently we are not validating input parameters of a subprocess. We are mapping them to `typed.Unknown`
In this change `SubprocessResolver` enriches `SubprocessInput` with suprocess typing input definition, so it can be validated in `PartSubGraphCompiler`.

Validate subprocess input parameters.

---

ui/server/src/main/scala/pl/touk/nussknacker/ui/api/EspErrorToHttp.scala

Unhandled errors are silently swallowed what makes debugging harder. In this PR behaviour is changed to log all unexpected errors with a stacktrace.

Log unhandled API errors

---

build.sbt
engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/QueryableStateTest.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkProcessManager.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/ProcessManagerProvider.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/queryablestate/QueryableClient.scala
engine/queryableState/src/main/scala/pl/touk/nussknacker/engine/flink/queryablestate/FlinkQueryableClient.scala
engine/queryableState/src/main/scala/pl/touk/nussknacker/engine/flink/queryablestate/QueryableClientProvider.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/QueryableStateResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfig.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/FetchingProcessRepository.scala

There is a misleading configuration option `flinkConfig.queryableStateProxyUrl` that is now being used for determining cluster location for querying jobs' state. It is also invalid to use it as different processing types might refer to different cluster locations. This change removes this legacy configuration and uses already defined, but not used `processTypes.[...].queryableStateProxyUrl`

Configuring queryable state from Flink configuration only

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/MetaData.scala
engine/httpUtils/src/main/scala/pl/touk/nussknacker/engine/dispatch/LoggingHandler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/MetaVariables.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/build/EspProcessBuilder.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/marshall/ProcessMarshaller.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/types/TypesInformationExtractor.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/variables/MetaVariables.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/marshall/ProcessMarshallerSpec.scala
ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/RestModelCodecs.scala
ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/DisplayableProcess.scala
ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/displayablenode.scala
ui/restmodel/src/test/scala/pl/touk/nussknacker/restmodel/RestModelCodecsSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/NewProcessPreparer.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/processreport/ProcessCounter.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/AdditionalPropertiesValidator.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
ui/server/src/test/scala/db/migration/V1_016__TypeSpecificMetaDataChangeSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesExportImportResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/codec/UiCodecsSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/UiProcessMarshallerSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/processreport/ProcessCounterTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/AdditionalPropertiesValidatorTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala

This PR introduces properties variable - allows business users to access process properties in diagram.
Additionally, I've decided to remove UserDefinedProcessAdditionalFields trait as it is source of many argonaut-related problems.

Properties variable

---

demo/docker/app/application.conf
docs/Configuration.md
engine/example/src/main/java/pl/touk/nussknacker/engine/javaexample/ExampleProcessConfigCreator.java
engine/example/src/test/scala/pl/touk/nussknacker/engine/example/BaseItTest.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSourceFactorySpec.scala
engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/KafkaSourceFactorySpec.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/CustomProcess.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/TestProcessConfigCreator.scala
engine/flink/management/src/it/resources/application.conf
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/FlinkProcessRegistrarKafkaSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkProcessMainSpec.scala
engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaConfig.scala
engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaEspUtils.scala
nussknacker-dist/src/universal/conf/application.conf
nussknacker-dist/src/universal/conf/docker-application.conf
ui/server/develConf/demo/application.conf
ui/server/develConf/generic/application.conf
ui/server/develConf/sample/application.conf
ui/server/src/test/resources/application.conf

In newer (like less than 3 years old...) zookeeper.connect is not used by clients

[CONFIG] - remove unused zkAddress config

---

engine/standalone/engine/src/it/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManagerSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala

Currently testMigration tries to fetch all processes' jsons via single HTTP request. As size of the response might be enormous we should fetch processes one by one.
There is one drawback of this solution though - I haven't been able to empty internal Akka HTTP requests queue and ended up opening new connection for every request.

[Fix] Migration test takes too long for large processes list

---

build.sbt
engine/processReports/src/main/scala/pl/touk/nussknacker/processCounts/CountsReporter.scala
engine/processReports/src/main/scala/pl/touk/nussknacker/processCounts/influxdb/InfluxCountsReporter.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfig.scala

We may want to get counts differently (e.g. not from influx?)

[Config] Other CountsReporters can be loaded via ServiceLoader mechanism

---

engine/standalone/app/src/main/scala/pl/touk/nussknacker/engine/standalone/http/ManagementRoute.scala
engine/standalone/app/src/test/scala/pl/touk/nussknacker/engine/standalone/http/StandaloneHttpAppSpec.scala

Simple healthcheck endpoint to ensure standalone application is running.

Add healthcheck endpoint in standalone app

---

ui/server/develConf/generic/application.conf
ui/server/develConf/sample/application.conf
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/FetchingProcessRepository.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala

Ultimately, I'd like to get rid of processesDetails endpoints altogether. This change mitigates problem with exposing all processes' jsons in one request.
Additionally, it adds batching support for migration testing

Fetch processes details by process names batch

---

ui/client/common/ClipboardUtils.js
ui/client/components/graph/Graph.js

`navigator.clipboard` is not accessible via HTTP. As a workaround in order to copy node's JSON, a hidden element is created, then text content is written to it and finally, second copy is executed. Because of copying twice, two events get generated so we need to discard artificial one.

Workaround copying to clipboard for content delivered via HTTP

---

ui/client/actions/actions.js
ui/client/components/graph/Graph.js
ui/client/components/graph/NodeUtils.js
ui/client/components/right-panel/UserRightPanel.js
ui/client/containers/Visualization.js
ui/client/reducers/graph.js
ui/client/test/reducer-test.js

* Select nodes with <kbd>Ctrl + click</kbd>.
* Copy, cut, paste, delete, duplicate selected nodes.
* Undo/redo paste in single step.
* I have discovered when deleting a group but I think it's a deprecated feature.
In next PR I am going to implement simple validation to ensure pasted nodes are available to choose from the left toolbox.
Short demo:

Select and operate on multiple nodes

---

engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala

Now it's consistent with other nodes like `Sink`, `Processor`, etc. What is more processes details could not be deserialized by circe because for some reason isDisabled field was omitted by argonaut - probably there is a different optional parameters behaviour in these libraries.

Convert isDisabled parameter in split to option

---

engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/deployment/ProcessRepository.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/deployment/FileProcessRepositoryTest.scala

After migration to circe, `ProcessName` is serialized as a value. On the other hand, using argonaut, it was serialized as an object. As a result existing processes could not be loaded. I added a test case to prevent such errors in future.

Test standalone process is correctly loaded from file

---

ui/client/containers/Processes.js
ui/client/stylesheets/processes.styl

For some reason nested input in table cell was not taking full width. Long process names were not fully visible.

Stretch process name text to full column width

---

ui/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/processdetails.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala

Returning merely commentId from this endpoint brings close to no value to the user. In scenario when user wants to read this comment's content they have to fetch all comments for all versions and filter them accordingly. Having explicit endpoint just to fetch comment seems redundant thus this change.

Include deployment comment in /api/processes/:name/deployments endpoint

---

engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/PermissionSyntax.scala
engine/security-api/src/test/scala/pl/touk/nussknacker/ui/security/api/LoggedUserTest.scala
engine/security-api/src/test/scala/pl/touk/nussknacker/ui/security/api/PermissionSyntaxTest.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AuthorizeProcess.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ServiceRoutes.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/UserResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparer.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjects.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessTypesForCategories.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/security/NussknackerInternalUser.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparerSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsSpec.scala

New permissions system introduced bug where admin user sees no elements in control panel. I've decided to redesign LoggedUser class to explicitly handle admin case on type level. The major problem currently is the need for categoryPermissions map for non-admin users. When admin is concerned, he shall always be permitted to do every action he needs and thus returning list of categories for which the permission is granted is redundant and has been removed.
Fixes #206

LoggedUser refactoring

---

docs/Security.md
engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/GlobalPermission.scala
engine/security-api/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
engine/security-api/src/test/scala/pl/touk/nussknacker/ui/security/api/LoggedUserTest.scala
nussknacker-dist/src/universal/conf/docker-users.conf
nussknacker-dist/src/universal/conf/users.conf
ui/client/common/models/User.js
ui/client/containers/EspApp.js
ui/server/develConf/sample/users.conf
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/UserResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/security/BasicHttpAuthenticator.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/UsersResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala

This PR introduces additional permissions configuration for use cases where one want to control access to certain functionalities but it is impossible or makes no sense to assign it to some category. 
Motivating example: admin tab in the UI. At the moment just admin user can access it but it also has pretty useful components for the end user - namely search / unused components and services. 
I was thinking about moving `custom processes` to a different place and eventually renaming `Admin` tab to something different. To make such change I'd like to discuss it with you guys first.

Global permissions

---

ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesExportImportResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala

Instead of importing process currently route` /api/processes/:name/:category` is matched instead.
Just reorganizing routes so that `/api/processes/import/:name` gets matched first.

Fixing /api/processes/import/:processName route

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/expression/Expression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompilationResult.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompiledProcess.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/CustomNodeInvoker.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TestInfoProvider.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionValidator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/SqlExpressionParser.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/util/service/query/ExpressionServiceQuery.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala

Refactoring:
- moved "factory" logic from ProcessCompiler to ProcessCompiler.compile to see which ExpressionCompiler's are used
- moved "factory" logic from SpelExpressionParser to SpelExpressionParser.default
- moved  typing logic from SpelExpressionValidator to Typer
- moved wrapping in dto logic from ProcessValidation to Resources to have one point to every validations in gui
- cleanup: passes ValidationContext to compileValidatedObjectParameters instead of Option[ValidationContext]
- Validated.fold -> Validated.map().valueOr()
- Validated[NonEmptyList[E],A] => ValidatedNel[E,A]

Fix for typing error: #input was available in parameter's expressions + some refactoring

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/expression/Expression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompilationResult.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/evaluatedparam.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessObjectFactory.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionValidator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/ast/SpelAst.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/ast/SpelNodePrettyPrinter.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/SqlExpressionParser.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala

This change adds typing info for each expression in each node in process. Typing info depends on used expression parser. Currently is implemented only typing info for SpEL. It contains computed type for each SpEL AST node.

Typing ast

---

ui/client/stylesheets/graph.styl

Fix for not working property height : 'fit-content' on Mozilla browser

Fix modal height on Mozilla

---

ui/client/components/AddProcessDialog.js
ui/client/components/graph/EdgeDetailsModal.js
ui/client/components/graph/NodeDetailsModal.js
ui/client/components/modals/ConfirmDialog.js
ui/client/components/modals/GenericModalDialog.js
ui/client/components/modals/PreventExitDialog.js
ui/client/stylesheets/graph.styl

This fixes input edition after modal move
This fixes modal sizes on different browsers
This fixed "save" button availability in "property" modal

Fix input edition after modal move

---

engine/httpUtils/src/main/scala/pl/touk/nussknacker/engine/sttp/SttpJson.scala
engine/processReports/src/main/scala/pl/touk/nussknacker/processCounts/influxdb/SimpleInfluxClient.scala

Right now whenever request to influxdb fails (e.g. series does not exist) user is presented with `Internal Server Error` message as this is what API returns. This PR explicitly handles exceptions providing user-friendly messages at the API level (and thus on the FE as these messages are forwarded as-is to the user).

Explicitly handle problems with requests to InfluxDB

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ValidationContext.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala

After custom node with join transformation global variables disappear. This is ugly fix - in future global variables should be moved out from ValidationContext

Copy global expressions after custom node with join transformation

---

ui/client/actions/actions.js
ui/client/common/ClipboardUtils.js
ui/client/components/right-panel/UserRightPanel.js
ui/client/containers/Visualization.js
ui/client/reducers/graph.js

Copied elements are saved in the system clipboard. Paste button is currently supported only in Chrome like browsers and it requires the user to grant access to the clipboard. `Ctrl+V` shortcut should work in most browsers. What's more paste button is always enabled since we cannot easily detect when clipboard content was modified.
Relates to #225.

Allow to copy, cut and paste elements across browser's windows

---

ui/client/http/HttpService.js

Successful deploy was always displayed as failed one. Axios fails promises for responses other than 2xx so additional check if response is successful is not needed, in contrast to fetch.

Properly notify successful deploy

---

ui/client/components/tips/Errors.js
ui/client/components/tips/Warnings.js
ui/client/stylesheets/visualization.styl

Now errors will wrap as they should, causing no horizontal scrolling situation.
I added blank spaces after `Errors in`, and node `disabled:` to separate it from links that come after.
I also added 5px to tip panel height, which now fits 2 lines of warnings and 2 lines of errors without the need to scroll it vertically.

tip panel styling

---

engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
ui/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/ProcessChangeListenerFactory.scala
ui/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/services/NussknackerServices.scala
ui/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/services/PullProcessRepository.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/PullProcessRepository.scala

* I've extracted additional trait for accessing process details in listeners module so we are in more controll what operations are avaialble in listener implementations.
* maybe we should also rewrite data to special DTOs instead of providing restmodel classes? (now, UI changes will have impact on listeners implementations)

add read only access to process details for listeners

---

engine/demo/src/test/scala/pl/touk/nussknacker/engine/demo/ExampleItTests.scala
engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/QueryableStateTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/DockerTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/batch/FlinkBatchProcessManagerSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessManagerSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessTestRunnerSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/JavaConfigProcessManagerSpec.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/FlinkStreamingProcessRegistrarKafkaSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/FlinkStreamingProcessRegistrarSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/api/EvictableStateTest.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/MetricsSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/SqlProcessItTests.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/util/service/query/ServiceQueryOpenCloseSpec.scala
engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/StoppableExecutionEnvironment.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/ServiceInvokerTest.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/sql/SqlExpressionTest.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/util/service/query/ExpressionServiceQuerySpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/util/service/query/ServiceQuerySpec.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/management/MultiInstanceStandaloneProcessClientSpec.scala
engine/test-util/src/main/scala/pl/touk/nussknacker/test/ExtremelyPatientScalaFutures.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/RemoteEnvironmentResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala

Switched all places of usage of Eventually/ScalaFutures to *PatientScalaFutures + added ExtremelyPatientScalaFutures used in docker tests (was waiting for 1,5min, now is waiting for 5min)

ExtremelyPatientScalaFutures in docker tests

---

ui/client/containers/NussknackerInitializer.js

At start page when token is expired then for a while we can see error page and after that we have redirect to sign in page. This PR fix this problem - we don't show error page when user api data returns 401 and backen is OAuth2.

Fix: OAuth2 expired token

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/ArgonautCirce.scala
engine/api/src/test/scala/pl/touk/nussknacker/engine/api/ArgonautCirceTest.scala

Problem:
Argonaut to circe conversion fails when JsonDecimal value is issued, as toCirce tries to parse the value to long.
Scenario:
1. Create a process with source that has Option[Double] attribute.
2. Prepare test data file with proper json fields, eg. {"foo":1.1}
3. Run test from file

Fixed conversion of argonaut JsonDecimal to circe

---

demo/docker/testData/DetectLargeTransactions.json
demo/docker/testData/DetectLargeTransactionsWithAggregation.json
demo/docker/testData/DetectLargeTransactionsWithAggregationAndEnricher.json
engine/demo/src/main/scala/pl/touk/nussknacker/engine/demo/DemoProcessConfigCreator.scala
engine/demo/src/test/scala/pl/touk/nussknacker/engine/demo/ExampleItTests.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/QueryableStateTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessTestRunnerSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/SampleProcess.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/StatefulSampleProcess.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/build/EspProcessBuilder.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/SampleProcess.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/DictsFlowTest.scala

We don't need example params at errorHandler:
After changes:

Improvements: Remove handlerErrors example params from models

---

ui/client/components/AddProcessDialog.js
ui/client/components/graph/node-modal/EdgeDetailsModal.js
ui/client/components/graph/node-modal/NodeDetailsModal.js
ui/client/components/graph/node-modal/NodeDetailsModalHeader.js
ui/client/components/modals/ConfirmDialog.js
ui/client/components/modals/GenericModalDialog.js
ui/client/components/modals/PreventExitDialog.js
ui/client/stylesheets/graph.styl

This closes #482 
Modal is now draggable with hover on modal header title. Modals without header, ConfirmDialog and PreventExitDialog are no longer draggable. 
On hover outside header:
On hover header:
On drag:
EdgeDetailsModal:

Moving modal on grabbing its name label (#482)

---

ui/client/actions/notificationActions.js
ui/client/common/ProcessUtils.js
ui/client/components/graph/Graph.js
ui/client/components/graph/GraphUtils.js
ui/client/components/graph/NodeUtils.js
ui/client/stylesheets/_variables.styl
ui/client/stylesheets/notifications.styl

This closes #474, closes #511 
Now we can drop nodes above and below groups:
TODO - handle inject of group when is dropped on line

Fix collapse group on icon click

---

engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkStubbedRunner.scala

It is started on 8081 port by default.

Start Flink web server on random during process test

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessManager.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/SavepointResult.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessManagerSpec.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkProcessManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala

During Flink upgrade it might be wise to snapshot job's state and cancel it in single action to avoid processing duplicates when restoring the job on new version of cluster. It is currently possible in two steps - making a snapshot and then canceling process so some duplicates are possible.
This PR also fixes making a snapshot with custom directory - it is ignored currently.
In next change redeploying a process could be improved by making a snapshot and canceling the job simultaneously.

Make snapshot and cancel process in single action

---

nussknacker-dist/src/universal/conf/dev-application.conf
ui/client/common/ProcessUtils.js

I haven't found any other node without id or type, so when it's empty then it's properties node, isn't it?
I prefixed properties with dollar sign, because it could be common to create own components with name properties.

Allow for setting documentation for process properties

---

engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaSinkFactory.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/PartitionByKeyFlinkKafkaProducer.scala
engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaEspUtils.scala

We change
props.putAll	
to 
foreach(...props.setProperty)
because in Java11 there are some weird overloading problems with the former. The rest is just code rearrangement

Small cleanup of passing kafka properties - getting ready for java11

---

engine/api/src/main/java/pl/touk/nussknacker/engine/javaapi/process/ClassExtractionSettings.java
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/conversion/ProcessConfigCreatorMapping.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassMemberPredicate.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassPredicate.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/columnmodel/TypedClassColumnModel.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/types/EspTypeUtils.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/types/TypesInformationExtractor.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/sql/columnmodel/TypedClassColumnModelTest.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala
engine/test-util/src/main/resources/logback-test.xml
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/logging/ExecutionTimeMeasuring.scala

Steps to verify api result:
```
baseurl='TODO'
processingType='streaming'
curl -d '{}' -H 'content-type:application/json' $baseurl/api/processDefinitionData/$processingType?isSubprocess=false | jq -c '.processDefinition.typesInformation[] | { cl: .clazzName.refClazzName, m: .methods | keys }' | sort
```
Before change on dev it looks like:
[staging-before-change.json.txt](https://github.com/TouK/nussknacker/files/4113381/staging-before-change.json.txt)
After change:
[staging-after-change.json.txt](https://github.com/TouK/nussknacker/files/4113518/staging-after-change.json.txt)
Diff:
[staging-diff.json.txt](https://github.com/TouK/nussknacker/files/4113519/staging-diff.json.txt)
Main changes:
- filtering logic moved from deep internals to setting available to reconfigure in user-space logic …

Exposing basic methods for collections in type definitions

---

engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractor.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/testing/ProcessDefinitionBuilder.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractorSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjects.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparerSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverterSpec.scala

Currently we extract type information each time we create ProcessDefinition - this e.g. includes tests, process runtime etc - while we need it only on UI. This operation can be a bit costly (performance-wise) so we move it to be peformed only when needed

[Perf] Extract TypeInformation only once and not in tests, backend etc.

---

ui/client/components/ProcessHistory.tsx
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala

- Refactor old deployAction namespace to action
- Most important think is change sortBy place at fetchProcessLatestActionsQuery
Example query before:
```
select * from (select * where "process_id" = 20 order by "performed_at" desc) x2 left outer join "process_comments" x10 on x2.x8 = x10."id"
```
Example query after:
```
select * from (select * where "process_id" = 2) x2 left outer join "process_comments" x10 on x2.x8 = x10."id" order by x2.x6 desc
```

Fix: fetching lastAction for process

---

engine/queryableState/src/main/scala/pl/touk/nussknacker/engine/flink/queryablestate/FlinkQueryableClient.scala

Flink's QueryableStateClient has bug which cause failures during fetch. Our current implementation of walk around was too verbose - we logged all stack traces with debug level. After this change we will log them with trace level.

Less verbose FlinkQueryableClient - stack traces on trace level.

---

engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/FlinkProcessRegistrar.scala

We should not handle internal Flink exception thrown from collector.collect - sometimes this can prevent process from cancelling/failing

[FIX] pass exceptions from collector.collect in sync interpretation

---

engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/AvroSchemaSpelExpressionSpec.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompiledProcess.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TestInfoProvider.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/TypeMethodReference.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/util/service/query/ExpressionServiceQuery.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionGenSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

There was hardcoded `ClassExtractionSettings.Default` in `TypeMethodReference` class, therefore it was not possible to provide own implementation

fix overriding ClassExtractionSettings

---

engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/FlinkStreamingProcessRegistrarKafkaSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/SubprocessSpec.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/canonicalgraph/ProcessNodesRewriter.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/node.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/SubprocessResolverSpec.scala
ui/client/components/graph/node-modal/MapVariable.js
ui/client/components/graph/node-modal/NodeDetailsContent.js
ui/client/components/graph/node-modal/SubprocessOutputDefinition.js
ui/server/src/main/scala/pl/touk/nussknacker/ui/definition/DefinitionPreparer.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessObjectsFinderTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/processreport/ProcessCounterTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala

Allow subprocess outputs to return value.
Subprocess can behave as MapVariable and pass fields to process.

Subprocess output returning map variable

---

ui/client/components/graph/node-modal/editors/expression/Editor.ts

When at BE we don't have any validators (ex. `@NotNull`) then FE set Mandatory and NotBlank Validators.. It should have place only when paramConfig is null - it's  situation for special nodes like:  Filter / Switch.

Fix: Mandatory validator

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/CustomStreamTransformer.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/CustomNodeProcessSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/ProcessTestHelpers.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala

After reusing CutomNodePart in compile/splitted graph support in flink streaming seems to be out-of-the-box, so I just added few tests.
I'm opening this PR to have a place for discussion about other thinks that may be missed for full support of optional ending custom nodes.

Ending custom nodes flink support

---

ui/client/common/ProcessUtils.js

Fix for accessing variableTypes regardless of nodeId value. (Now, if nodeId contains e.g characters `[ ]` we get null

[FIX] find context variables in nodes

---

ui/client/stylesheets/visualization.styl

it looks like this now:
This resolved #803

error indicator restyling (#803)

---

engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala

Fix check status when deployment of new version is finished before cancelling previous job on Flink. (Cancelled version has later
last-modification date then the new running version)

Fix checking status of Flink job

---

ui/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx

Problem I've found.
Editor would render the first option when the current value is invalid or blank.
It's misleading, user has no idea that the true value in process (as seen with
JSON export) is different
I've simplified the FixedValuesEditor so that it renders what it gets.
What in case the value is no longer valid?
Validation should take care and force user to select a new value.
What about default value?
I think it should be set on process/node creation time. It has nothing to do with render time.

Make FixedValuesEditor more explicit about current value

---

build.sbt
engine/benchmarks/Readme.md
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/spel/ScalaAccessorBenchmark.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/spel/SpelBenchmarkSetup.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/OptimizedEvaluationContext.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/propertyAccessors.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/preparevalues/ReadObjectField.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/variables/GlobalVariablesPreparer.scala
project/plugins.sbt

Optimizations: 
- ScalaPropertyAccessor is now compilable 
- more performant EvaluationContext initialization
Results for ScalaAccessorBenchmark:
avgt    8  0.978 ± 0.126  us/op  ==> base
avgt    8  0.618 ± 0.036  us/op  ==> with ScalaPropertyAccessor overriding ReflectivePropertyAccessor
avgt    8  0.122 ± 0.010  us/op  ==> with above + avoiding costly EvaluationContextInitialization

[Performance] first benchmarks and some SpEL performance fixes.

---

.travis.yml

When some job failed then date for release can be different. So we have to use date of last commit.

Fix: Same date for each travis job

---

demo/docker/grafana/dashboards/Flink-ESP.json
engine/demo/src/main/scala/pl/touk/nussknacker/engine/demo/DemoProcessConfigCreator.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/exception/RateMeterExceptionConsumer.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/metrics/MetricUtils.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/service/TimeMeasuringService.scala

+ fixes in demo dashboard:
- delays wasn't visible
- using non_negative_derivative(last) instead of mean(rate) for better values for long intervals
- added interval variable next to processName and env

Added count meter for error metric

---

ui/client/components/ValidateDeployComment.js
ui/client/test/ValidateDeployComment-test.js

Logic how many matches is allowed should be controlled by regular expression and not be hardcoded to 1.

allow to match deployCommentPattern more then once

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/FlinkStreamingProcessRegistrar.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/ProcessSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/SubprocessSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformer.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcess.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/part.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcessTest.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/SubprocessResolverSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/marshall/ProcessConverter.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/PrettyValidationErrors.scala

This fixes some bugs/deficiencies in joins/subprocesses. 
Most notably:
- in diagram there can be > 1 join
- some forms of joins can be used in subprocesses (most important - split/switch => union - in diamond shape)
To achieve this some refactoring of FlinkStreamingProcessRegistrar and SubprocessResolver had to be made...

[Improvement] Possibility to use unions in diamond-shaped subprocesses

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/ReturningType.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/service/CustomValidatedService.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/validation/PrettyValidationErrors.scala

I'd like to be able to add custom validation logic at a single node level.
simple use cases:
* check with external service
* parameter cross validation
The idea is to implement `WithCustomValidation.validate`.
I want it to be invoked after compilation, so we have access to both parameter Expression as well as it's TypingResult.
This is a rather dirty implementation, but just want to check if it makes sense at all

Add custom node validation (e.g. for parameters cross validation)

---

engine/standalone/engine/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/StandaloneProcessConfigCreator.scala
engine/standalone/engine/src/it/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManagerSpec.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala

[FIX] interpreter.open() was not called in standalone tests, closes #931

---

docs/Changelog.md
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/CanBeSubclassDeterminer.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
engine/api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultSpec.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

I think we should treat Typed.empty like Nothing type - in particular, it's subclass of all classes :)

[FIX] Empty inline lists have proper type

---

engine/demo/src/test/scala/pl/touk/nussknacker/engine/demo/ExampleItTests.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroSourceFactory.scala
engine/flink/generic/src/test/scala/pl/touk/nussknacker/genericmodel/GenericItSpec.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/signal/KafkaSignalStreamConnector.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaExceptionConsumer.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaSinkFactory.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaSourceFactory.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/PartitionByKeyFlinkKafkaProducer.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sources.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/signal/RemoveLockProcessSignalFactory.scala
engine/flink/management/sample/src/test/scala/pl/touk/nussknacker/engine/process/NamespacedKafkaSourceSinkTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessManagerSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/kafka-test-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaClient.scala
engine/kafka-test-util/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaZookeeperServer.scala
engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaConfig.scala
engine/kafka/src/main/scala/pl/touk/nussknacker/engine/kafka/KafkaUtils.scala
engine/kafka/src/test/scala/pl/touk/nussknacker/engine/kafka/KafkaUtilsTest.scala

- Rename KafkaEspUtils to KafkaUtils
- Rename KafkaUtils from kafka tests to KafkaZookeeperUtils
- Extract BaseKafkaSinkFactory 
- Add some helper methods like: KafkaConfig.parseProcessObjectDependencies and KafkaUtils.prepareTopic

Improvements: Kafka tools refactor

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/expression/Expression.scala
engine/benchmarks/Readme.md
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/ManyParamsInterpreterBenchmark.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/OneParamInterpreterBenchmark.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/spel/SpelBenchmarkSetup.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompiledProcess.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodevalidation/NodeDataValidator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/CustomNodeInvoker.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TestInfoProvider.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/NullExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionRepr.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/OptimizedEvaluationContext.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/SqlExpressionParser.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/util/service/query/ExpressionServiceQuery.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/sql/SqlExpressionTest.scala
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/SynchronousExecutionContext.scala

This change fixes some performance problems with handling global variables, also uses faster synchronous execution context (we don't have any real async there.
I also add two benchmarks. 
There is one change that I reverted: https://github.com/TouK/nussknacker/commit/3b24988035c082ee944d603f5f1ef33d53285cbf
It brings more performance benefits, but I think it needs further consideration...

[Improvement] More performant expression evaluation wrt globals

---

docs/Changelog.md
docs/MigrationGuide.md
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/expression/Expression.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/ManyParamsInterpreterBenchmark.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/OneParamInterpreterBenchmark.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/spel/SpelBenchmarkSetup.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodevalidation/ParameterEvaluator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/CustomNodeInvoker.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/NullExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/sql/SqlExpressionParser.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/util/service/query/ExpressionServiceQuery.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/sql/SqlExpressionTest.scala

Excessive use of Futures can cause performance problems due to context shifting. 
We had in theory ability to have asynchronous expression evaluation, but all expression languages were in fact synchronous. Making them synchronous also simplifies code.
If in the future we want to return to async evaluation probably it would be better to explore e.g. cats-effect or sth like that

[Improvement] synchronous Expressions for performance improvements

---

engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
ui/client/common/ProcessUtils.js
ui/client/components/graph/node-modal/AdditionalProperty.tsx
ui/client/components/graph/node-modal/BranchParameters.js
ui/client/components/graph/node-modal/NodeDetailsContent.js
ui/client/components/graph/node-modal/editors/EditableEditor.tsx
ui/client/components/graph/node-modal/editors/expression/ExpressionField.tsx
ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js
ui/client/components/graph/node-modal/editors/expression/RawEditor.tsx
ui/client/test/ProcessUtils-test.js

Currently suggestion engine in FE doesn't handle BranchParameters well. 
We refactor ExpressionSuggest a bit, so that list of variables is passed from outside. This allows to use other ValidationContext for branch parameters. 
It turns out we *already* pass ValidationContext for different branches for FE, so we use it, however this probably deserves refactoring so it's more explicit

[Improvement] corrent context is passed for branch parameters on UI

---

build.sbt
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/typed/CanBeSubclassDeterminer.scala

We still can't fully migrate on JDK11 as Flink supports it only from 1.10...

[Improvement] getting ready for JDK 11

---

ui/client/components/MenuBar.tsx

Frontend was failing if customTabs array was not provided in the configuration file.

Fix non-spreadable custom-tabs array problem

---

build.sbt
ciRunSbt.sh
engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/FlinkTestConfiguration.scala

- specified MaxMetaspaceSize
- specified NETWORK_BUFFERS_MEMORY
- switch from JAVA_OPTS to args in sbt invocation

Fix for out-of-memory in travis

---

docs/Changelog.md
engine/processReports/src/main/scala/pl/touk/nussknacker/processCounts/influxdb/InfluxGenerator.scala

Currently for newly deployed processes zero counts values are returned. What's more count values are incorrect (too small) because of the last aggregation.

Fix metrics query for 1 hour window

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/Context.scala
engine/api/src/main/scala/pl/touk/nussknacker/engine/api/definition/WithExplicitMethodToInvoke.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/service/DynamicService.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/service/UnionReturnObjectService.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ServiceInvoker.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessConfigCreator.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreterSpec.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/test/StandaloneTestMainSpec.scala

The idea is to pass some custom generated context id (correlation id) when invoking standalone process so that the same context id is available when executing services.
This way we are able to log inbound and outbound HTTP requests with the same correlation id (context id).

Add ContextId to the list of optional service parameters

---

ui/client/components/graph/node-modal/editors/expression/ExpressionSuggest.js

"#" is duplicated when suggestion capital letters (e.g. in utils):

[FIX] Avoid duplicate # in suggestions for helpers

---

engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/TyperSpec.scala

In case of template SpEL expressions, each of the subexpressions has it's own abstract tree with positions relative to the subexpressions starting position, e.g. 
expression `"result: #{#x + 1}"`, will be parsed as:
LiteralExpression: `"result: "`
SpelExpression: `"#x + 1"`
Therefore:
* positions in `CollectedTypingResult` are not correct (not absolute)
* we can have "Merging same types" warnings in case of positions clash

Fix template typing, drop intermediate results to get rid of "Merging same types..." warning

---

build.sbt

It's only cleanup - sttp already had proper version of async lib.

Fix: Http Util

---

engine/flink/api/src/main/scala/pl/touk/nussknacker/engine/flink/api/process/FlinkCustomNodeContext.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala

Job data is already available from services via RuntimeInjectedJobData trait.

Access job data from custom nodes

---

ui/client/common/ProcessUtils.ts

... with broken graph structure caused: failed cursor: DownField(type),DownField(input),DownField(variableTypes)

Fix for: node validation after source without returnType

---

ui/client/components/graph/node-modal/NodeDetailsContent.js

- Fix bug in compare versions dialog: FE crashed when Properties was selected after looking at "normal" node differences
- Removed warning in initialization
- nicer default value handling (credits to @trombka ...)

[FIX] Compare versions works better

---

docs/MigrationGuide.md
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/AvroSchemaDeterminer.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/BasedOnVersionAvroSchemaDeterminer.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaRegistryClient.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaWithMetadata.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SpecificRecordEmbeddedSchemaDeterminer.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClient.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClientFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/AbstractConfluentKafkaAvroDeserializer.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroDeserializationSchemaFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroDeserializer.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/serialization/KafkaAvroDeserializationSchemaFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/BaseKafkaAvroSinkFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/BaseKafkaAvroSourceFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/serialization/ConfluentKafkaAvroDeserializationSpec.scala

Passing schema with id to TypeInfo and ConfluentKafkaAvroDeserializer

---

ui/client/components/graph/node-modal/AdditionalProperty.tsx

Fix for missing `fieldName` property, which caused bugs in displaying validation labels in some specific cases.

[FIX][UI] Fix AdditionalProperty

---

ui/client/common/ProcessUtils.ts
ui/client/components/graph/node-modal/NodeDetailsContent.js
ui/client/components/graph/node-modal/NodeGroupDetailsContent.js
ui/client/test/ProcessUtils-test.js

- Collapsed group can be opened
- Variable definition can be opened
- Fallback variables, based on graph definition, are valid TypingResults

[FIX] some small UI fixes

---

.github/workflows/pr.yml
build.sbt

Things that are left for future PRs:
- computing coverage
- adding devModel for staging
- cross publishing
- building FE only once and caching artifacts
Refactor of workflows:
- GithubActions do not handle composite actions or other form of reusing parts of workflow definition (e.g. no support for YAML anchors...). There is composite run step: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-composite-run-steps-action, but one can only use "run" as steps and not other actions

[Build] Publish via githubactions - first version

---

ui/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/api/QueryableStateResources.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/JobStatusService.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala

Right now we always return state => process, because at ManagementActor we handle corner cases like missing state, mismatches etc.. 
* Refactor 
* JobStatusService now returns ProcessState instead of Option[ProcessState]

Improvements: Process state

---

engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/ProcessPartFunction.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompiler.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompilerData.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/CollectingSinkFunction.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkCompilerLazyInterpreterCreator.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/StreamExecutionEnvPreparer.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/SyncInterpretationFunction.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala

Due to complex structure of invocations/serialization we compiled whole process in each Flink operator (in (A)SyncFunction). 
For diagrams with complex structure it slows initialization process significantly

[Improvement] Compile process only once on Flink

---

engine/api/src/main/scala/pl/touk/nussknacker/engine/api/test/InvocationCollectors.scala
engine/benchmarks/src/main/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompiler.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/compiler/TestFlinkProcessCompiler.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkStreamingProcessMainSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMainSpec.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TestInfoProvider.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/util/service/query/ServiceQuery.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/ServiceInvokerTest.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/util/service/query/ServiceQuerySpec.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneProcessManager.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessConfigCreator.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/test/StandaloneTestMainSpec.scala

The main change is passing TestRunId to compiler explicitly, without hacks in e.g. TestFlinkProcessCompiler. 
This is first PR with test handling refactor. Some more will follow :)

[Improvement] Correct tests handling for EagerService

---

build.sbt
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticatorProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticator.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/DefaultOAuth2ServiceFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Authenticator.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticatorFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ClientApi.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceProvider.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticatorDataSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ClientApiSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceProviderSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala

I have found `ExecutionContext.Implicits.global` in a few places in the security package and changed it to implicit parameters so that we could use the main (from Akka) NK execution context.
I have also removed a locally created Sttp backend in favour of one created from Akka.

Global ExecutionContext and local Sttp backend removed

---

docs/Changelog.md
docs/MigrationGuide.md
engine/demo/src/main/java/pl/touk/nussknacker/engine/javademo/DemoProcessConfigCreator.java
engine/demo/src/main/scala/pl/touk/nussknacker/engine/demo/DemoProcessConfigCreator.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaRegistryProvider.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ConfluentSchemaRegistryProvider.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroMessageFormatter.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroToJsonFormatter.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/BaseKafkaAvroSourceFactory.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/RecordFormatter.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/sources.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSource.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactory.scala
engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/KafkaSourceFactorySpec.scala
engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/generic/JsonRecordFormatterSpec.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/functions/conversion.scala

`RecordFormatter` and `TestDataSplit` should have matching behaviour, as formatting has impact on test data split. This changes embeds `TestDataSplit` into `RecordFormatter`.
We also introduce `JsonRecordFormatter` to better handle different json formattings for kafka-json in tests (e.g. many new lines etc.)

[Improvement] RecordFormatter simplifications, correct json handling

---

build.sbt
engine/flink/api/src/main/scala/pl/touk/nussknacker/engine/flink/api/timestampwatermark/TimestampWatermarkHandler.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/signal/KafkaSignalStreamConnector.scala
engine/flink/management/sample/src/main/scala/pl/touk/nussknacker/engine/management/sample/service/CustomValidatedService.scala
engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/PeriodicSourceFactory.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/source/BlockingQueueSource.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/source/EmitWatermarkAfterEachElementCollectionSource.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/timestamp/BoundedOutOfOrderPreviousElementAssigner.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/timestamp/BoundedOutOfOrdernessPunctuatedExtractor.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala

Some dependency upgrades. Scala 2.11 holds us from upgrading circe and cats. Flink with its frozen Akka version makes it impossible to use a newer Akka HTTP.
NK extensions use nussknacker-ui assembly as their runtime so we should try keeping packaged dependencies up to date.

Upgrade project dependencies

---

engine/standalone/api/src/main/scala/pl/touk/nussknacker/engine/standalone/api/StandaloneCustomTransformer.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreter.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessConfigCreator.scala
engine/standalone/engine/src/test/scala/pl/touk/nussknacker/engine/standalone/StandaloneProcessInterpreterSpec.scala
engine/standalone/util/src/main/scala/pl/touk/nussknacker/engine/standalone/utils/customtransformers/ProcessSplitter.scala

Changing `createTransformation(outputVariable: String)` to `createTransformation(outputVariable: Option[String])` makes it possible to move extracting of `outputVariable` (or not extracting it) from `StandaloneProcessInterpreter` to `createTransformation`. 
That allows to create `StandaloneCustomTransformer` with no return value.

optional outputVariable for StandaloneCustomTransformer

---

engine/flink/model-util/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/CardinalityAggregator.scala
engine/flink/model-util/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregatesSpec.scala
engine/flink/model-util/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/HyperLogLogPlusAggregatorSpec.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetection.scala
engine/flink/process/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/internal/typedobject/TypedObjectBasedTypeInformation.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetectionSpec.scala

- HyperLogLogPlus is serialized much more efficiently for TypingResult based serialization
- isCompatibleWithReconfiguredSerializer is handled correctly for TypedObjectBasedTypeInformation

[Improvement] Correct HLL typed serialization, serialization improvements

---

engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/KafkaAvroBaseTransformer.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactoryWithEditor.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/KafkaAvroIntegrationSpec.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/helpers/KafkaAvroSpecMixin.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/sink/KafkaAvroSinkFactoryWithEditorIntegrationTest.scala

1. Remove unnecessary parameter: ValidationMode
2. Refactor: pass transformation state instead of var mutation

Avro sink enhancements

---

docs/Changelog.md
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessDBQueryRepository.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala

After moved rename to process properties we can observe that when we change name then system create new version.. In fact we always send rename request and update process request.. If we change 2-3 times name then we can observe that system creates new version of process - but in json we don't see differences.. I debug mode I saw that lastProcessVersion json contains white spaces like `\n` but in BE tests I couldn't reproduce it.. 
This MR fix this situation.

Fix: Update process with same json

---

demo/docker/docker-compose-env.yml

this solved the bug of some of the akhq ui links not working, 
In case you ask ... yes, I checked whether it works before asking for PR.
Additionally, some new akhq features arrived. The most exciting one is support for references in avro schemas

Upgraded akhq to 0.17, 

---

engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticatorFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticatorFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticatorFactory.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala

With my previous PR to the security module, I added implicit arguments to the constructor of `OAuth2AuthenticatorFactory`. This makes it impossible to load its subclasses with SPI.
I moved the `ec` argument to the `createAuthenticator` and pulled down STTP backend creation into the authenticator factory class.

Fixed SPI for AuthenticationProvider

---

demo/docker/grafana/dashboards/Flink-ESP.json
demo/docker/telegraf/telegraf.conf

Changed treatment of null metric values on the graph. Instead of extrapolating values  with a straight  line ("connect"), simply do not show anything in the time period when there were no metrics reported. The result is hopefully on the attached pic.
Additionally modified  the "max lag" graph , we were showing stacked sum of max lags as reported by each Flink parallelized task. This is roughly the same value shown and stacked as many times as the Flink task parallelism level. Decided to show only one value, commented the graph accordingly. 
An interesting new effect is visible - every 4 minutes reporting (hopefully only reporting) stops for ca 20s, I get this effect on both my local machine and client (N..a) deployment.

Grafana dashboard corrections

---

demo/docker/docker-compose-env.yml

Currently in the demo version jobmanager and taskmanager use their own (separate) docker volumes. As the result jobmanager is not deleting old checkpoint files created by taskmanager. 
Jobmanager and taskmanager should share volume where statedata are stored

jobmanager and taskmanager should share volume where state data are stored

---

engine/util/src/main/scala/pl/touk/nussknacker/engine/util/config/ConfigFactoryExt.scala
engine/util/src/test/resources/reference.conf
engine/util/src/test/scala/pl/touk/nussknacker/engine/util/config/ConfigFactoryExtSpec.scala

Loaded empty config (`ConfigFactoryExt.loadEmptyConfigWithOverrides`) contains settings from reference.conf. This should be used as last fallback configuration.

Fix: Load config app

---

docs/Changelog.md
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

TODO:
- Add tests
- Rethrow exception with content of expression for easier further diagnostics
- Add entry in changelog

Fix for Spel validation: Use not existing method reference

---

demo/docker/docker-compose.yml

Fixes ERROR: Named volume "nussknacker_storage_flink:/opt/flink/data:rw" is used in service "app" but no declaration was found in the volumes section.

Add missing volume declaration

---

engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroMessageReader.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/ConfluentAvroToJsonFormatterFactory.scala
engine/flink/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceFactory.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroPayloadSourceFactorySpec.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/KafkaAvroSourceSpecMixin.scala
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/source/TopicSelectionStrategySpec.scala

Problem with generic/specific record serialization to Array[byte]

---

engine/security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectServiceSpec.scala
engine/security/src/main/resources/META-INF/services/pl.touk.nussknacker.ui.security.api.AuthenticationProvider
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationConfiguration.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticationConfiguration.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticationProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticationResources.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticator.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Configuration.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/api/AuthenticationConfigurationSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticationResourcesSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/loader/ScalaServiceLoader.scala
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/multiplicity.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala

I have found out that the extension engine for authenticators is hardly useful.
You can override an authenticator, but you cannot add a new method name since they are defined in an enumeration. So in the case of a totally new authenticator, it is not possible to pass to FE a method name other than `Other`.
The PR drops the enumeration in favor of the NamedServiceProvider interface.
I have also renamed `DefaultAuthenticationConfiguration` to `Basic...` since it seems the only usage case and the class is not extendable.

More flexible authenticator customization by using named SPI services.

---

engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticatedUser.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationConfiguration.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationResources.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/LoggedUser.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticationProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticationResources.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticator.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/DefaultOAuth2ServiceFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/GitHubProfile.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Authenticator.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Profile.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceProvider.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectProfile.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/UserMappingOAuth2Service.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/api/LoggedUserTest.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/api/SecurityApiSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticationResourcesSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/DefaultOAuth2ServiceFactorySpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactorySpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResourcesSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceProviderSpec.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala

Solves https://github.com/TouK/nussknacker/blob/staging/engine/security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationProvider.scala#L15
AuthenticationProvider no longer delivers a LoggedUser but an AuthenticatedUser instance with a roles collection. Permission mapping is moved to an additional LoggedUser apply method.

Category-permission mapping extracted from AuthenticationProvider

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessManagerTest.scala

Process should be scheduled if previous, failed job is still accessible via Flink API

---

engine/interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

fixed class-validation changes derailing one of existing tests("not allow unknown variables in methods") in SpelExpressionSpec

fixed test failure after class-validation changes

---

build.sbt

root@12387d786282:/usr/local/openjdk-11/lib# ls libfontmanager.so 
libfontmanager.so

Use openjdk:11-jdk instead of openjdk:11-jdk-slim

---

engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/CustomNodeProcessSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/functional/ProcessSpec.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/helpers/ProcessTestHelpers.scala
engine/flink/process/src/test/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMainSpec.scala
engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala

This PR also coherents presenting results of 'tests from file'. New variables in context are preseneted in the following node in graph. Before this was true for all kind of nodes besides custom nodes.

Fix 'counts' functionality for custom nodes. Only incoming events should be counted

---

engine/security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectServiceSpec.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/BaseOAuth2Service.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/CachingOAuth2Service.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtOAuth2Service.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ClientApi.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Configuration.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ServiceFactory.scala
engine/security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/UserMappingOAuth2Service.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/DefaultOAuth2ServiceFactorySpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactorySpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/JwtTokenAuthenticationSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResourcesSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2ClientApiSpec.scala
engine/security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OpaqueTokenAuthenticationSpec.scala
engine/util/src/main/scala/pl/touk/nussknacker/engine/util/Implicits.scala
ui/client/containers/Auth/strategies/OAuth2Strategy.ts
ui/client/http/HttpService.ts

… in favor of dynamic evaluation in the FE
The redirect URI is unnecessary in configuration. When the frontend needs to call the authorization endpoint it already knows its own location, so there is no need to take this value from the backend settings. Though I left such an option for a yet-unknown reason.

redirectUri made optional in the OAuth2 configuration

---

docs/installation_configuration_guide/Configuration.md
docs/installation_configuration_guide/DeploymentManagerConfiguration.md
docs/installation_configuration_guide/DesignerConfiguration.md
docs/installation_configuration_guide/Installation.md
docs/installation_configuration_guide/ModelConfiguration.md
docs/scenarios_authoring/AggregatesInTimeWindows.md

Names of NK components (Designer, Executor Manager) should be capitalized.
Model is a concept, not a NK component -> use lower case instead of upper case.
Minor improvement of ApproximateSetCardinality aggregator description.

Docs refinement

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerProvider.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/DeploymentManagerStub.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkStreamingDeploymentManagerProvider.scala
engine/standalone/engine/src/main/scala/pl/touk/nussknacker/engine/standalone/management/StandaloneDeploymentManager.scala
ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/DeploymentManagerProvider.scala
ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/BaseDeploymentManager.scala
ui/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/testing/DeploymentManagerStub.scala
ui/server/src/main/scala/pl/touk/nussknacker/ui/process/NewProcessPreparer.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/NewProcessPreparerSpec.scala
ui/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala

- BaseDeploymentManager with rarely/not used methods implemented (as "not implemented" :) )
- TypeSpecificDataInitializer => TypeSpecificInitialData case class

Small Deployment API refactoring

---

ui/server/src/main/resources/defaultUiConfig.conf

Workaround for: sometimes FE sends invalid urls with not escaped square brackets

---

build.sbt
docs/Changelog.md
engine/flink/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/ConfluentKafkaAvroDeserializationSpec.scala
utils/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/jsonpayload/ConfluentJsonPayloadDeserializerFactory.scala
utils/avro-util/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/jsonpayload/JsonPayloadToAvroConverter.scala
utils/avro-util/src/test/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/jsonpayload/JsonPayloadToAvroConverterSpec.scala

kafka-registry-typed-json source was recognizing logical types during typing but during evaluation were used raw, underlying types

Fix for: kafka-registry-typed-json not handle logical types in runtime

---

engine/lite/kafka/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/NuKafkaRuntimeBinTest.scala

trying to fix problem: 
```
2022-01-25T14:46:26.4564733Z [ERROR] [01/25/2022 14:46:26.454] [nu-kafka-runtime-akka.actor.internal-dispatcher-3] [akka://nu-kafka-runtime/system/IO-TCP/selectors/$a/0] Bind failed for TCP channel on endpoint [/10.1.0.183:0]
2022-01-25T14:46:26.4565422Z java.net.BindException: [/10.1.0.183:0] Cannot assign requested address
2022-01-25T14:46:26.4565775Z 	at java.base/sun.nio.ch.Net.bind0(Native Method)
2022-01-25T14:46:26.4567982Z 	at java.base/sun.nio.ch.Net.bind(Net.java:455)
2022-01-25T14:46:26.4568536Z 	at java.base/sun.nio.ch.Net.bind(Net.java:447)
2022-01-25T14:46:26.4569529Z 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
2022-01-25T14:46:26.4572389Z 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdap …
```

GH actions workaround: binding to localhost

---

engine/lite/components/base/src/main/scala/pl/touk/nussknacker/engine/lite/components/ForEachTransformer.scala
engine/lite/components/base/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteBaseComponentProvider.scala
engine/lite/kafka/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaTransactionalScenarioInterpreterTest.scala
engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreterSpec.scala

Rename lite split component to avoid clash with base component name

---

engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala

* Add overriding container env in test
* Set runtime image strictly
* Log warn message when runtime image configured

Set runtime image strictly (#2803)

---

docs/installation_configuration_guide/model/Flink.md
engine/flink/api/src/main/scala/pl/touk/nussknacker/engine/flink/api/exception/FlinkEspExceptionConsumer.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/exception/FlinkExceptionHandlerSpec.scala
engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/exception/KafkaExceptionConsumer.scala
engine/flink/test-util/src/main/scala/pl/touk/nussknacker/engine/flink/test/RecordingExceptionConsumer.scala
engine/flink/util/src/main/scala/pl/touk/nussknacker/engine/flink/util/exception/DefaultExceptionConsumers.scala

Docs cleanup:
1. fixed url to kafka-exception-handling
2. replaced one of fixed-delay restartStrategy configuration example with some different (but still quite fundamental) strategy example
Parameter rename:
`FlinkEspExceptionConsumerProvider` does not get "additionalConfig" but full "exceptionHandler" configuration (see `FlinkExceptionHandler.extractBaseConsumer`). Here, that parameter name suggests that something else is taken into account.

Minor docs cleanup and parameter rename.

---

engine/flink/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/exception/KafkaExceptionConsumer.scala
engine/flink/kafka-util/src/test/scala/pl/touk/nussknacker/engine/kafka/exception/KafkaExceptionConsumerSerializationSpec.scala
engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaSingleScenarioTaskRun.scala
utils/kafka-util/src/main/scala/pl/touk/nussknacker/engine/kafka/exception/KafkaJsonExceptionSerializationSchema.scala

Changes:
1. Allow KafkaExceptionConsumerProvider to overwrite serializationSchema
2. Use KafkaSerializationSchema as a serializationSchema

Allow KafkaExceptionConsumerProvider to overwrite serializationSchema

---

docs/installation_configuration_guide/model/Flink.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/exception/FlinkExceptionHandler.scala
engine/flink/util/src/main/resources/META-INF/services/pl.touk.nussknacker.engine.util.exception.WithExceptionExtractor
engine/lite/kafka/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/kafka/KafkaSingleScenarioTaskRun.scala
utils/util/src/main/scala/pl/touk/nussknacker/engine/util/exception/DefaultWithExceptionExtractor.scala
utils/util/src/main/scala/pl/touk/nussknacker/engine/util/exception/WithExceptionExtractor.scala

Changes:
1. `WithExceptionExtractor` is configurable as a NamedServiceProvider
2. Custom implementations of `WithExceptionExtractor` should provide transient&nonTransient extractors
3. Default implementation is `DefaultWithExceptionExtractor`
4. FlinkExceptionHandler extracts name of `WithExceptionExtractor` from `exceptionHandler` configuration and loads via `ScalaServiceLoader.loadNamed`

Allow to configure a WithExceptionExtractor (with default impl)

---

ui/client/components/graph/node-modal/editors/Validators.ts

The list of possible values in error message for `fixedValuesValidator` are joined by comma. For larger lists the error message was so wide it could not fit inside the modal.
Before:
After:
Another things to consider, but not necessarily in this PR: 
1. This validator allows empty value. That's why the list starts with comma after `:`. This might be misleading to user - maybe it should be more verbose? Like `[EMPTY VALUE]` or some other placeholder? Or it should be completely removed if field is marked as required? 
2. If list of values is large (50? 100?) only return first `n` values in error message

`fixedValueValidator` - separate list of values by comma and space

---

ui/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx

Fixed values fields can be filtered, but text inserted by user appears on the bottom of the list. If list is long, user is unable to see what was already typed.
Here I've typed `202`:
and `testy` here:
This change moves inserted text to the top of list which should be more user-friendly.

Move inserted text in fixed values field from bottom to top

---

engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/util/Serializers.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/util/SpelHack.scala

Remove manual calls to `Output.flush` from custom serializers, it's not required and may degrade performance

Remove manual stream flushing from serializers

---

docs/installation_configuration_guide/DeploymentManagerConfiguration.md
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerProviderTest.scala

Expose jmx prometheus metrics in nussknacker-lite-runtime

---

ui/client/cypress/integration/processes.ts

temporarly disable screenshot matching in broken cypress test

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypedFromInstanceTest.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala

Typed.fromInstance(null) works now the same as literal null in SpEL

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/generics/ExpressionParseError.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/TypeMethodReference.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/TypeMethodReferenceSpec.scala

Added tests for type method reference, because before it was possible to make any use of overloaded functions cause errors and still pass all tests. Also made handling typing errors caused by overloaded functions more deterministic.

Test type method reference

---

docs/Changelog.md
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/SchemaRegistryClient.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClient.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClientFactory.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/ConfluentSchemaRegistryClient.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaDeserializerFactory.scala

* SchemaRegistryClient - introduced `getLatestSchemaId` operation
* ConfluentUniversalKafkaDeserializer fix - latest schemaId taken from cache

UniversalKakfaSource optimization - if message without schemaId, using cache when getting one

---

engine/flink/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/flink/FlinkKafkaUniversalSink.scala
engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalSinkImplFactory.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/ParsedSchemaSupport.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/UniversalSchemaSupport.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/client/AvroSchemaWithJsonPayload.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/formatter/UniversalToJsonFormatterFactory.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/AbstractConfluentKafkaAvroDeserializer.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaDeserializerFactory.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/schemaregistry/confluent/serialization/universal/ConfluentUniversalKafkaSerializationSchemaFactory.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/sink/UniversalKafkaSinkFactory.scala
utils/avro-components-utils/src/main/scala/pl/touk/nussknacker/engine/avro/source/UniversalKafkaSourceFactory.scala

* `UnsupportedSchemaType` is thrown once in one place
* When introducing new schema type, implementation of all "support methods" is now forced by interface

refactor UniversalSchemaSupport

---

docs/scenarios_authoring/AggregatesInTimeWindows.md

This change is for doc for Aggregates in Time Windows:
- Added example with composite value in the groupBy field - without it being in examples, it is not obvious that it is a valid way.
- Added column with value of the #key variable - currently this is in the 'result' column and it is not very readable
Pls have a look at the usage of `` - I think the proposed approach is bit more logical than previously, but still ...

docs: composite key in the groupBy field

---

ui/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala

The list of test cases is in random order (as returned from backend) and might differ from one node to another. The goal of this change is to have a consistent ordering of test cases (ordered by context id).

UI: Order test cases by context id

---

build.sbt
docs/Changelog.md

Change to eclipse-temurin base image due to openjdk deprecation

---

docs/Changelog.md
engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/requestresponse/ScenarioDispatcherRoute.scala
engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/RequestResponseEmbeddedDeploymentManagerTest.scala

Fix for serving OpenApi definition and SwaggerUI for deployed RequestResponse scenarios in embedded mode

---

docs/Changelog.md
engine/lite/request-response/app/src/test/scala/pl/touk/nussknacker/engine/requestresponse/http/RequestResponseHttpJsonSchemaSpec.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/JsonSchemaSubclassDeterminer.scala

```
{
"properties": {
"msisdn": {
"type": "string"
}
},
"additionalProperties": false,
} 
```
Before fix above example didn't allowed to pass request as `{"msisdn": "test"}` - It was required to add `"required": ["msisdn"]`.

Fix schema validation when using additionalProperties without required

---

engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/ForEachTransformer.scala
engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/ForEachTransformerSpec.scala

Fix for incorrect contextId assignment in `ForEachTransformer`.
Environment: 1.7.0-staging-2022-10-27-10064, e.g. https://staging.nussknacker.io/visualization/fmc_c1
Steps to reproduce: 
1. run "Test from file" on scenario with for-each component
2. see the values assigned to the output of for-each
3. on "Test case" list it is impossible to switch between individual cases within the same input collection, because all elements have the same Test case id = contenxtId (see attached image)
The "lite" version ForEachTransformer assigns contextId correctly.

Fix contextId assignment for the output of ForEachTransformer

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentDefinitionPreparer.scala
docs/Changelog.md
docs/MigrationGuide.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/subprocess.scala
scenario-api/src/test/scala/pl/touk/nussknacker/engine/canonicalgraph/CanonicalProcessTest.scala
scenario-api/src/test/scala/pl/touk/nussknacker/engine/graph/SubprocessRefSerializationSpec.scala

Cleanup legacy API in `SubprocessRef::outputVariableNames`

---

components/openapi/src/main/scala/pl/touk/nussknacker/openapi/package.scala

Fix: keep openapi classes in package rather that package object

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/ValidationResults.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrationsSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala

Rollback to desired behaviour:
* deployment of scenarios with warnings is allowed (without this change it is allowed on UI but fails after clicking "deploy")
* migration of scenarios with warnings is still disabled (can be discussed in the future whether it really should be disabled)

Fixup - deployment of scenarios with warning was failing after clicking deploy

---

docs/installation_configuration_guide/DeploymentManagerConfiguration.md
docs/installation_configuration_guide/DesignerConfiguration.md
docs/installation_configuration_guide/ModelConfiguration.md

Rewrote the "Configuring replicas count" in R-R processing mode.
+
This PR focuses on the cognitive aspects of the configuration documentation. The purpose is to reduce the cognitive distress of the reader - there is so much to understand and remember that we need to give the reader a hand in the journey through the documentation. 
The typical questions asked when you install Nu and try to understand its configuration:
- will I need to configure anything in this particular area (Designer, Deployment Manager, Model) or is everything set for me?
- If there are incremental changes to be applied, how to apply them in the Docker case and how to apply them in the K8s case?
These questions need to be answered for all three configuration areas.

Configuration docs cognitive aspects polishing

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultErrorMessagesSpec.scala
engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreterSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

Type map literal values

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidatorSpec.scala
designer/client/components/graph/node-modal/editors/Validators.ts
designer/client/test/Validators-test.tsx

Fixup to NotBlankParameterValidator:
* not empty expressions containing somewhere '' were treated as errors by FE validator
* spel string literals created using "" weren't checked
* test on be/fe added

Fixup to NotBlankParameterValidator

---

engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/util/Serializers.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/AvroStringSettingsInTests.scala

`setAccessible(true)` modifies only locally kept flag, there's no need to reset it

Remove unneeded setAccessible calls

---

build.sbt
docs/Changelog.md
docs/MigrationGuide.md

Bumps: jwks 0.19.0 -> 0.21.3, jackson: 2.11.3 -> 2.13.4

---

engine/lite/k8sDeploymentManager/src/main/resources/defaultMinimalDeployment.conf
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparer.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala

- added startupProbe
- timeout seconds increased from default 1 sec to 5 secs (in case of e.g. full GC) 
- liveness period: 10 sec -> 5 sec for faster unavailability detection 
- minReadySeconds: 10 -> 0 (default value) to make runtime containers ready as soon as they are ready

Runtime probes tune

---

engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala

additional logging in case of k8 deployment failure in tests

---

engine/flink/tests/src/test/resources/application.conf
engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/FlinkWithKafkaSuite.scala
engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/MockFlinkKafkaComponentProvider.scala
engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/BaseStreamingEmbeddedDeploymentManagerTest.scala
engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/MockLiteKafkaComponentProvider.scala
engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/RequestResponseEmbeddedDeploymentManagerTest.scala

work around to bug in intelliJ which causes that wrong classpath is provided when runining tests from intelliJ

unique name for test components providers

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
docs/Changelog.md
docs/MigrationGuide.md

Before
Healthcheck alerts when there is a scenario deployed-not-running.
After
Helathcheck alerts when there is scenario with any instance of ProblemStateStatus (including deployed-not-running)

Use ProcessStateStatus to detect alerting scenarios in healthcheck

---

build.sbt
components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/DatabaseInitializer.scala
docs/Changelog.md
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/DbInitializer.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/TypeDefinitionSet.scala
project/build.properties
security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/GenericOidcServiceSpec.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala
utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/EmbeddedKafkaServer.scala

Mostly safe upgrades, except:
* some commons dependencies were outdated when they were originally added to Nu, but there was no comment explaining that this was required - so I updated them
* netty is upgraded from 4.1.48.Final to 4.1.90.Final - we're already running model with 4.1.60, and AsyncHttpClient seems to work fine with 4.1.87: https://github.com/AsyncHttpClient/async-http-client/commits/main/pom.xml
Not updated:
* cats-effect left at 2.x
* testcontainers-keycloak - newer version fails in CI due to some JUnit dependency mismatch
* ignite - newer version fails in CI on some data type conversion error, I couldn't quickly find out why
Also, I added version overrides for various netty and Jackson libraries pulled as transitive dependencies - we were missing some of them, resulting in …

Bump dependencies

---

designer/client/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
designer/client/components/graph/node-modal/editors/expression/SqlEditor.tsx
designer/client/components/graph/node-modal/editors/expression/StringEditor.tsx
designer/client/components/graph/node-modal/editors/expression/TextareaEditor.tsx

Improved button hints when conversion from SpEL editor to basic editor is not possible and the button is disabled.

Changes in basic editor button hints

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/component/package.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/engine/CombinedProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentDefinitionPreparer.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentIdProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentObjects.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentsUsageHelper.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentsValidator.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/DefaultsComponentGroupName.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/DefaultsComponentIcon.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessObjectsFinder.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/util/LocalNussknackerWithSingleModel.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ComponentResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/ComponentsUsageHelperTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentIdProviderSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReaderSpec.scala
docs/Changelog.md

* `ComponentIdProvider` is not longer created eagerly during Nussknacker start up since it depends on components which can be reloaded. Component id provider is created once during processing data creation as a combined data of all processing types.
* Extracted `ComponentsValidator` which validates components configuration during processing data creation.
* Internal `ComponentObjectsService` extracted to hide complexity of `UIProcessObjects`.
* Extracted `ComponentsUsageHelper` from `ProcessObjectsFinder`.

 Components are aware of processing data reload

---

e2e-tests/Dockerfile

Hi!
The Dockerfile placed at "e2e-tests/Dockerfile" contains the best practice violation [DL3007](https://github.com/hadolint/hadolint/wiki/DL3007) detected by the [hadolint](https://github.com/hadolint/hadolint) tool.
The smell DL3007 occurs when the tag "latest" is used instead of a specific version tag for the base image.
In this pull request, we propose a fix for that smell generated by our fixing tool. We have verified that the patch is correct before opening the pull request.
To fix this smell, specifically, we use a heuristic approach that selects the most probable version tag for the base image in order to replace the "latest" tag. In detail, it selects the most recent image tag which corresponds to the same image digest that currently corresponds to the "latest" tag.
This change …

Fix for Dockerfile smell DL3007

---

components/openapi/src/test/scala/pl/touk/nussknacker/openapi/BaseOpenAPITest.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
docs/Changelog.md
engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/deployment/ProcessRepository.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/api/SecurityApiSpec.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/formatter/AvroMessageFormatter.scala
utils/utils-internal/src/main/scala/pl/touk/nussknacker/engine/util/UriUtils.scala

Sometimes error messages and descriptions may differ, and then they are reported as new ones in migration tests, even though they are not "new" (caused by migration):
* when description or message in Nu changes
* when locale between local and remote environment differs
* when error message or description depends on runtime environment's settings

Ignore error message and description when comparing errors lists in model migration tests

---

docs/installation_configuration_guide/model/Flink.md

Added short page summary in the 'description' parameter, which should be visible on the card in the list auto-generated on category page ('Model' page in this case).

Description added

---

benchmarks/Readme.md
docs/Changelog.md
docs/MigrationGuide.md
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassMemberPredicate.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassPredicate.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala

Regex matching accounts for 5-6% of time spent when validating scenario migrations. Recent changes from #4278 should help a lot here, but this was easy to change and made code a bit easier to read, so I went ahead and refactored these predicates.
Benchmark:
```scala
@Benchmark
@BenchmarkMode(Array(Mode.AverageTime))
@OutputTimeUnit(TimeUnit.MICROSECONDS)
def benchmarkScala(): AnyRef = {
EspTypeUtils.clazzDefinition(classOf[util.ArrayList[_]])(ClassExtractionSettings.Default)
EspTypeUtils.clazzDefinition(classOf[util.Set[_]])(ClassExtractionSettings.Default)
EspTypeUtils.clazzDefinition(functions.conversion.getClass)(ClassExtractionSettings.Default)
EspTypeUtils.clazzDefinition(functions.numeric.getClass)(ClassExtractionSettings.Default) …
```

Replace regex matching in expression compilation with string matching

---

interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/DefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/GlobalVariableDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/MethodDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/testing/ProcessDefinitionBuilder.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractorSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/variables/GlobalVariablesPreparerTest.scala

Refactor: MethodDefinition moved from StandardObjectWithMethodDef into ComponentImplementationInvoker

---

docs/Changelog.md
engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala

Expose more methods for use in expressions:
* `java.lang.CharSequence`: `replace`
* `java.util.Collection`: `lastIndexOf`
* `java.util.Optional`: `isEmpty`
* `scala.Option`, `scala.collection.Iterable`: `head`, `nonEmpty`, `orNull`, `tail`
* `io.circe.*` (deserialized raw JSON objects): `noSpacesSortKeys`, `spaces2SortKeys`, `spaces4SortKeys`
I'm also removing detection of Argonaut classes, as we got rid of them over three years ago (thanks to @jedrz for noticing it).

Expose more methods for use in expressions

---

components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/ServiceRequest.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
docs/Changelog.md
engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/DefaultResponseEncoder.scala
engine/lite/request-response/runtime/src/main/scala/pl/touk/nussknacker/engine/requestresponse/openapi/RequestResponseOpenApiGenerator.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/BestEffortJsonSchemaEncoder.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala
utils/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/serialization/schemas.scala
utils/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/sink/GenericJsonSerialization.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/universal/RecordFormatterSupport.scala
utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/json/BestEffortJsonEncoder.scala
utils/utils/src/test/scala/pl/touk/nussknacker/engine/util/json/BestEffortJsonEncoderSpec.scala

Without this we can't preview arrays in SpEL Interactive:

Support arrays in BestEffortJsonEncoder

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/simple/SimpleStateStatus.scala
designer/deployment-manager-api/src/test/scala/pl/touk/nussknacker/engine/api/deployment/OverridingProcessStateDefinitionManagerTest.scala
designer/deployment-manager-api/src/test/scala/pl/touk/nussknacker/engine/api/deployment/StateStatusCodingSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
docs/Changelog.md
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentProcessStateDefinitionManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicStateStatus.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessServiceIntegrationTest.scala
engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/EmbeddedStateStatus.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessState.scala

This is the first change related to statuses refactor. The general concept of this refactor:
1. make pluggable deployment manager responsible for state management
2. move Flink specific status handling (e.g. `ObsoleteStatusDetector` or `DeploymentServiceImpl.handleFinishedProcess`) to proper deployment manager
3. deployment manager should know what each state means and should be responsible for state recognition and 
The steps:
1. identify and serialize StateStatus by name (https://github.com/TouK/nussknacker/pull/4299)
2. some class renames (https://github.com/TouK/nussknacker/pull/4300)
3. move state inconsistency detection and resolution to deployment manager (https://github.com/TouK/nussknacker/pull/4302)

Identify and serialize state status by name

---

docs/Changelog.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/TypeReferenceTyper.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

Fix for spel validations: Typing type reference with class starting from lower case caused nasty error

---

build.sbt

I tried to deploy Nussknacker with Flink executor using the recommended method:
* application classpath: `nussknacker-designer:assembly` + `nussknacker-flink-manager`
* model: `nussknacker-flink-executor:assembly` + components  (`nussknacker-flink-base-components:assembly` + `nussknacker-flink-kafka-components:assembly` + `nussknacker-sql:assembly`)
This failed on startup with:
```
java.lang.NoClassDefFoundError: org/apache/flink/streaming/api/datastream/DataStream
at pl.touk.nussknacker.engine.flink.util.transformer.FlinkBaseComponentProvider.create(FlinkBaseComponentProvider.scala:27)
```
The issue is that nothing provides Flink runtime, which is required by model.
This fix adds building `assembly` version of `nussknacker-flink-manager`, and corrects version of …

Publish assembly artifact for nussknacker-flink-manager

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/DisplayableProcess.scala
designer/restmodel/src/test/scala/pl/touk/nussknacker/restmodel/NodeDataCodecSpec.scala

DisplayableProcess legacy decoder fix - typeSpecificProperties instead of typeSpecificData

---

designer/client/src/components/toolbars/status/buttons/CustomActionButton.tsx
engine/development/deploymentManager/src/main/resources/web/static/assets/buttons/test_deploy.svg
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala

Custom action icons, when defined in config file, are rendered as inline `<svg>somefile content</svg>`. When custom action is defined in `DeploymentManager.customActions: List[CustomAction]` icon is rendered as `<img src="somefile.svg" />`. 
Example - double arrow is permanently black (black..ish ?), but color of the text below the icon is set correctly :

Replace img with inlined svg for CustomAction buttons.

---

components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/SwaggerParser.scala
components/openapi/src/test/resources/swagger/swagger-2.0-refs.yml
components/openapi/src/test/scala/pl/touk/nussknacker/openapi/parser/SwaggerParserTest.scala
docs/Changelog.md

In SwaggerParser when we get a Swagger 2.0 definition which has references which we are using later (such as in parameters or response body), we are not able to properly parse it and convert to SwaggerService. This is because we are passing empty parser config to a dedicated Swagger 2.0 parser which has reference resolving turned off. This problem is not seen in OpenApi 3.0, because we are not passing any config, and it default to resolving refs.
I propose using a unified OpenAPIParser, since it is a higher level interface which parses Swagger 2.0 and Openapi definitions. It gets the same parser config with resolution turned on.

Fix: resolve references in Swagger 2.0

---

docs/Changelog.md
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingDeploymentManagerSpec.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/HttpFlinkClient.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala

Change caused by https://issues.apache.org/jira/browse/FLINK-28758

Fix stopping processes with `/api/adminProcessManagement/stop/{processName}` endpoint on recent Flink versions

---

engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala

K8s test: more precise logging of test failure cause

---

build.sbt
components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/OpenAPIServiceSpec.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/OpenAPIsConfig.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/discovery/SwaggerOpenApiDefinitionDiscovery.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/enrichers/SwaggerEnricher.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/http/backend/SharedHttpClient.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
docs/MigrationGuide.md
utils/http-utils/src/main/scala/pl/touk/nussknacker/http/backend/HttpBackendProvider.scala
utils/http-utils/src/main/scala/pl/touk/nussknacker/http/backend/HttpClientConfig.scala
utils/http-utils/src/main/scala/pl/touk/nussknacker/http/backend/LoggingAndCollectingSttpBackend.scala
utils/http-utils/src/main/scala/pl/touk/nussknacker/http/backend/RequestResponseLog.scala

In https://github.com/TouK/nussknacker/commit/5205163169f5e11c7170d5df91ea8587cbe6e063  we added `readTimeout` to `HttpFlinkClient.findJobsByName`.
Akka does not support such setting and sttp uses idleTimeout as readTimeout, see sttp.client3.akkahttp.AkkaHttpBackend :
```
private def connectionSettings(r: Request[_, _]): ConnectionPoolSettings = {
//...
connectionPoolSettingsWithProxy
.withUpdatedConnectionSettings(_.withIdleTimeout(r.options.readTimeout))
} 
```
And that idle/readTimeout means that after timeout connection is killed via RST (see also https://github.com/akka/akka-http/issues/3346).
Therefore, to avoid broken sessions of findJobsByName, when HttpFlinkClient is created we should replace use AsyncHttpClientFutureBackend instead of AkkaHttpBackend.

Replace AkkaHttpBackend with AsyncHttpClientFutureBackend

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala

Allow to pass http proxy properties to sttp in Nussknacker by:
```
java11 -Dhttps.proxyHost=your-proxy.domain -Dhttps.proxyPort=8080 -cp nussknacker-designer.jar pl.touk.nussknacker.ui.NussknackerApp
```

Fix: Allow to pass to sttp client default options, e.g. http proxy

---

designer/client/src/components/tips/Warnings.js

Scenario warnings are displayed without a header message. This is caused by incorrectly mapping warning message to header message on the FE.
Now:
After this change:

Fix warnings message

---

designer/client/src/i18n.ts
designer/submodules/packages/components/src/settings/i18n.ts
designer/submodules/packages/legacy_scenarios/src/i18n.ts

- The issue was caused by i18n built-in suspense which was sometimes fired since we have lazy loading and fallback loaders, there is no reason to declare root suspense (in theory it should also resolve this issue, but didn't check it), so we can just remove the built-in  i18n suspense
- The issue is only reproducible on specific environments (we cannot reproduce it locally), I was able to reproduce it and fix it, on the Nu cloud instance by the replacing Nu image with this one https://hub.docker.com/layers/touk/nussknacker/preview_NU-980-error-on-page-open-latest/images/sha256-ac5876187a9aacc35f1506ae4eb7d9a969fa2df0857247143e8849f2f178cff5?context=explore
https://github.com/TouK/nussknacker/assets/9945753/b9842207-cfc1-4018-9bf1-d21aba7f93fd

NU-980: Error on page open

---

designer/client/src/brace/theme/nussknacker.css

Currently text input color inside Search & Replace Ace Editor's  is very unfriendly. Here I propose new colours 
====== BEFORE ======
====== AFTER ======

Customize search and replace ace editor styles

---

.gitignore
benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/ManyParamsInterpreterBenchmark.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/SyncInterpretationFunction.scala
engine/lite/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/sample.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/SynchronousLiteInterpreter.scala

Fixed issues:
- `IOShape`: use `IO.apply` instead of `IO.pure` 
- `SyncInterpretationFunction`: in case of IO monad usage, the code should be symmetric to the Future-based implementation (added timeout to the sync run)
- `AsyncInterpretationFunction`: in case of the Future-based implementation - the callback was not invoked
- `interpreter.scala`: converting from Future to Effect (IO or Future) should be done using the sync execution context (now the intention is more clear than before)
IMO the issues above should be solved before bumping cats-effect lib. Ref: https://github.com/TouK/nussknacker/pull/4287
--- 
Benchmarks:
Before changes:
```
[info] Benchmark                                           Mode  Cnt        Score        Error  Units
[info] …
```

[bugfix] interpreters fixes

---

build.sbt

It's related to #4414. Basically this PR publish assembly artifacts required to run scenarios based on Lite engine. FYI those assembly artifacts are already also included in Nussknacker Docker image.

Publish assembly artifacts for all deployment managers and components

---

designer/client/src/windowManager/PromptContent.tsx

- There is a problem with the library used by nk-windows https://github.com/bokuweb/react-rnd/issues/760 -> The fix proposed in this issue doesn't work, so the only way to fix it, is probably to downgrade react-and library.
- However, we can disable this dialog drag option in case of touch devices, which will resolve this issue.

[NU-1027] Disable backgroundDrag on touch devices

---

.github/workflows/release.yml

This adds a check for release branch name in a release workflow. This way we can avoid mistakingly releasing a non-release branch.

Add a check for release branch in release workflow

---

designer/client/src/actions/nk/genericAction.ts
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggest.tsx
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggester.ts
designer/client/src/components/modals/GenericActionDialog.tsx
designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx
designer/client/src/http/HttpService.ts
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
docs/Changelog.md
docs/MigrationGuide.md

The discussion took place in a https://github.com/TouK/nussknacker/pull/4693 MR. It wont be merged as patch to 1.11 since it is API change so I've created this MR to staging instead.

Use processingType for validate nad sugesstions api

---

designer/client/src/components/Process/ProcessErrors.tsx
designer/client/src/components/Process/ProcessStateIcon.tsx
designer/client/src/components/toolbars/process/buttons/SaveButton.styl
designer/client/src/components/toolbars/status/ProcessInfo.tsx

fix popover fragment status, doesn't show red NU :)
rewrite ProccessInfo from class to function component.
before:
after:

NU-1058 fix popover for fragment status

---

designer/client/src/store/nodeValidationMiddleware.ts

Clear history action triggered process validation, which made empty request which couldn't be decoded causing this error:
This change only adds this action to ignored list in the middleware.

Fix empty validation request on undo history clear

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidatorSpec.scala
designer/client/src/components/graph/node-modal/editors/Validators.ts
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/AdditionalPropertiesValidatorTest.scala
docs/Changelog.md
docs/MigrationGuide.md
docs/installation_configuration_guide/model/ModelConfiguration.md
interpreter/src/test/resources/reference.conf
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractorSpec.scala

Fix: RegExpParameterValidator, trimming SpEL comprehension

---

docs/Changelog.md
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkTestScenarioRunner.scala

Improvement: FlinkTestScenarioRunner allow passing timestampAssigner

---

designer/client/src/reducers/selectors/graph.ts
docs/Changelog.md

For some time migration of fragments wasn't possible - checking for deploy on allowed actions list doesn't make sense because state for fragment is always null.

Fragment migration fixup

---

designer/submodules/packages/components/src/components/usages/nodesCell.tsx

fix highlightting searched column text
before:
after:

NU-1120 fix highlightting searched column text

---

.github/workflows/release.yml
build.sbt

… which was bad because cypress tests relies on these images and release images doesn't contain developer's extensions which are required by these tests

[NU-1104] Fix for: the release process published the release image under the release_VERSION-latest tag

---

build.sbt

> The tapir-swagger-ui and tapir-swagger-ui-bundle modules rely on a file in the META-INF directory tree, to determine the version of the Swagger UI
Without it designer (assembly) won't start with a message:
```java.lang.ExceptionInInitializerError: META-INF resources are missing, please check https://tapir.softwaremill.com/en/latest/docs/openapi.html#using-swaggerui-with-sbt-assembly```

Fix sbt assembly while using tapir swaggerUi

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/AppApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/BaseEndpointDefinitions.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NuDesignerApiAvailableToExposeYamlSpec.scala
docs/Changelog.md
docs/MigrationGuide.md
security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationResources.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicAuthenticationResources.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/dummy/DummyAuthenticationResources.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala

The change is needed to implement custom auth or to fallback while using multiple authentication methods.

Change authenticationMethod type from Auth to EndpointInput

---

docs/Changelog.md
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessStateDefinitionManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/PeriodicProcessesRepository.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/PeriodicProcessDeployment.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/SchedulesState.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessDeploymentGen.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessStateDefinitionManagerTest.scala

Right now deployments are sorted by `runAt` and it might produce problems when in some specific cases you want to run instant batch without waiting for schedule (using custom actions). Then `runAt` is still set by CRON but deployment starts immediately. In such case we can produce > 1 records with `runAt` set to same value and NU cannot handle states properly.

Sort periodic process deployments not only by runAt but also by createdAt

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/UserApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/services/NuDesignerExposedApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/services/UserApiHttpService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/UserApiSpec.scala
docs-internal/api/nu-designer-openapi.yaml

Replaced `UserResources` with `UserApiEndpoints` and `UserApiHttpService` using tapir.
This also updated nu-designer-penapi.yaml

[NU-1259] Replacing Akka HTTP in user endpoint with tapir

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NotificationApiSpec.scala

Removed a test after `prepareCancel` which is an asynchronous call from `NuScenarioConfigurationHelper`. Instead a method `createDeployedCanceledProcess` is used which creates 2 notifications in the same call.
Using just `createDeployedCanceledProcess` was one way to deal with the problem, could also just map a HTTP request on the `prepareCancel` call so it would be performed after the cancellation  happened.
Also, changed file name to `NotificationApiSpec` to comply with the naming convention.

[NU-1356] Remove nondeterminism in NotificationApiSpec

---

docs/Changelog.md
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/flink/FlinkJarManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/JarManagerTest.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkModelJarProvider.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala

Recreate model JAR for Flink if model written to temp directory got removed. E.g. systemd-tmpfiles on CentOS removes files from default `java.io.tmpdir` after 10 days.

Recreate assembled model JAR for Flink if it got removed (e.g. by systemd-tmpfiles)

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/services/AppApiHttpService.scala
docs/Changelog.md

Extends API to make it possible to fetch validation results without detailed typing information.
Example for `/api/processesDetails?names=...&skipNodeResults=true`:
* before: 796 kB (11,31 MB uncompressed) - our average production scenario has 5-10 MB of typing information
* after: 11,62 kB (68,65 kB uncompressed)
This allows us to reduce migration test time for 449 scenarios and 73 fragments from ~13,5 to ~11 minutes. I'm heavily averaging here, but assuming that an average scenario has 500 kB of JSON data (5 MB uncompressed) this gives us:
* 250 MB less sent between live application and CI server
* 2,5 GB less JSON data to parse

Add skipNodeResults parameter to API calls that return validated scenarios

---

common-api/src/main/scala/pl/touk/nussknacker/engine/util/Implicits.scala
designer/server/src/main/scala/pl/touk/nussknacker/engine/CombinedProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/factory/LocalProcessingTypeDataStateFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessCategoryService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReload.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ConfigProcessCategoryServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReaderSpec.scala
docs/Changelog.md
docs/MigrationGuide.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkRunner.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/DockerTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessTestRunnerSpec.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeConfig.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Configuration.scala

[NU-1400] Legacy categories config removal

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/component/UIComponentGroupsPreparerSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/component/defaultconfig/DefaultComponentConfigDeterminer.scala

Fix for: pallete didn't contain fragmentDefinition component group

---

designer/client/src/components/graph/NodeUtils.ts
designer/client/src/reducers/graph/correctFetchedDetails.ts
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/DefinitionsService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionsServiceSpec.scala

… on the FE side due to changes in the definition api

Fix for: outgoing edges from node that used fragment which lost outputs weren't automatically cleaned

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ValidationContext.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/validation/Validations.scala
designer/client/src/components/graph/node-modal/fragment-input-definition/FieldsSelect.tsx
designer/client/src/components/graph/node-modal/fragment-input-definition/item/Item.tsx
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/PrettyValidationErrors.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/FragmentParameterValidator.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSuggester.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala

Moves remaining fragment parameters validation to BE - that is checking if:
1. Parameter name is unique
2. Parameter name is a valid identifier.
To ensure consistency, I've centralized the logic of checking variable identifier validity in api.
When names are duplicated, the validation doesn't return more specific errors than about names. The errors are displayed based on name so if it wasn't fail-fast, we'd get duplicated errors for parameters with duplicated names. And  we shouldn't rely on index since that causes problems with drag'n'drop.
A good way to solve this would be to rely on an identifier from FE. To not pass this data to db, a custom encoder could skip the id field. I can leave it as is - this behaviour should be exactly the same from user perspective or I can make this change …

[NU-1361] Move fragment input definition validation to BE

---

build.sbt
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/RemoteEnvironmentResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrationsSpec.scala

Parallelize scenario migrations testing

---

build.sbt

The lack of open java.base/java.util module caused runtime issues with the following spel expression constructs:
```
* {"a": 1}.getOrDefault(“a”, -1)
* {"a": 1}.get("a")
* {1,2,3}.get(0)
* {1,2,3}.lastIndexOf(3)
* {1,2,3}.indexOf(3)
* {1,2,3}.contains(1) 
* {1,2,3}.toString
```
Alternatively we can add `--add-opens=java.base/java.util=ALL-UNNAMED` to `engine/lite/runtime-app/src/universal/bin/nu-engine-entrypoint.sh` but still we will have different jdk in CI and different in a production use.

Fixup: jdk downgraded from 17 to 11 in lite runner image (due to issues with InaccessibleObjectException)

---

engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/DelayedUniversalKafkaSourceAvroPayloadIntegrationSpec.scala
utils/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/delayed/DelayedKafkaSourceFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/KafkaUniversalComponentTransformer.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/sink/UniversalKafkaSinkFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/UniversalKafkaSourceFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/delayed/DelayedUniversalKafkaSourceFactory.scala

…(#5534)
* Adds fixedValuesEditor for timestampField in kafkaSource
* sorts values in editor
* changes after CR:
- empty value in FixedValuesParameterEditor
- storing schemaValidationResults in GenericNodeTransformation.State
- some tests if ParameterEditor sets correctly
* changes after CR:
- rename and new TODOs
* removing some code duplication from DelayedUniversalKafkaSourceFactory
* fixed missed during rebase
---------

Add fixed values parameter editor for timestampField in kafka source

---

.github/workflows/pr.yml
CONTRIBUTING.md
docs/Changelog.md
docs/integration/KafkaIntegration.md
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/AzureSchemaRegistryKafkaAvroTest.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/AzureSchemaRegistryClientFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/SchemaNameTopicMatchStrategy.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/AzureSchemaRegistryClientIntegrationTest.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/SchemaNameTopicMatchStrategyTest.scala

`SchemaNameTopicMatchStrategy` uses reference topic (or eventhub) list to match topic (or eventhub) name with schema name. It is still an estimation/guess but it doesn't rely on strict topic name convention and allows to loosen topic naming restrictions (see https://nussknacker.io/documentation/docs/integration/KafkaIntegration/#association-between-schema-with-topic).
Reference topic list is fetched in `AzureSchemaRegistryClient` by kafka admin client, therefore both schema registry and kafka client properties must be provided (see https://nussknacker.io/documentation/cloud/azure/#setting-up-nussknacker-cloud).
Schema `FooBarValue` is used to describe data in topics (eventhubs):
- foo.bar
- foo-bar
Documentation to update:
https://nussknacker.io/documentation/docs/integration/KafkaIntegrat …

[5615] Fix for eventhub naming convention with Azure Schema Registry

---

designer/client/src/components/graph/node-modal/NodeDetailsContent/NodeTableStyled.tsx
designer/client/src/components/graph/node-modal/tests/ExpressionTestResults.tsx
designer/client/src/components/graph/node-modal/tests/TestValue.tsx

Currently during scenario testing with 'ad hoc' tests and tests from file there is an issue with presenting longer contents of textAreas. The problem exists because of how textArea's rows dictate its height. 
```
function ReadonlyTextarea({ value = "" }: { value: string }) {
return <textarea className="node-input" readOnly value={value} rows={value.split("\n").length} />;
```
Row count is based on number of new line characters in the contents. This approach has an issue when we have a longer string content without new line characters as it is presented in a textArea that has only one row. As a result the hide/show content "eye" icon is not working as intended. It 'shrinks' the textArea to 100px and fades its the bottom as it assumes the textArea's height is set to its full content size. …

Modify TestValue textArea height calculation

---

designer/client/src/actions/nk/calculateProcessAfterChange.ts
designer/client/src/common/ProcessUtils.ts
designer/client/src/components/graph/NodeUtils.ts
designer/client/src/components/graph/node-modal/DescriptionField.tsx
designer/client/src/components/graph/node-modal/IdField.tsx
designer/client/src/components/graph/node-modal/NodeField.tsx
designer/client/src/components/graph/node-modal/ScenarioProperty.tsx
designer/client/src/types/node.ts

- We made some changes to the FE and BE related to the scenario state.Now, after performing the EDIT_NODE action, which changes the scenario state, we added a redundant scenario id to the scenarioGraph.properties. That's why, our mechanism to detect whether the Save button should be enabled or disabled is now detecting changes even when there aren't any.

[NU-1544] change of scenario name to the same value force user to save scenario

---

designer/client/src/components/graph/node-modal/NodeDetailsContent/NodeTableStyled.tsx
designer/client/src/components/graph/node-modal/tests/TestResults.tsx
designer/client/src/components/graph/node-modal/tests/TestResultsVariables.tsx
designer/client/src/components/graph/node-modal/tests/TestValue.tsx

Currently, when we test a scenario with ad hoc tests or tests from a file we get textAreas with contents displayed fully as shown on the screen.
When contents are large it becomes cumbersome to scroll to find the variable that actually interests us, and generally it's not too pleasant to read.
To solve this I added mechanism with the "eye" symbol similar to the one introduced in this merged PR: https://github.com/TouK/nussknacker/pull/5690
If a variable's contents fit into 4 lines of text in textArea we do not show the "eye" icon.
Else, we render the icon in its "active" form hiding large content as shown on the screen below.
Additionally, I removed the unused space that occurred when the fade effect was active on a textArea (screen below). Currently, it takes the same space as other …

Add show and hide option for variables in test case

---

engine/flink/components/base-unbounded/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/DelayTransformer.scala

* ~~remove state descriptor from component's fields - it doesn't belong there~~
* or not, if it's not a class-level `val` then closure cleaner complains about `nodeCtx.contextTypeInfo`
* replace element prepending with appending, making it cheaper and removing the need for list reversal when emitting elements

Optimize Delay component

---

designer/client/src/components/useProcessFormDataOptions.test.ts
designer/client/src/components/useProcessFormDataOptions.ts

Temporary fix for unintelligible exception raised when category field is missing

Temporary fix for unintelligible exception raised when category field is missing

---

build.sbt
docs/Changelog.md
engine/flink/scala-utils/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinfo/caseclass/CaseClassTypeInfoFactory.scala
engine/flink/scala-utils/src/test/scala/pl/touk/nussknacker/engine/flink/api/typeinfo/caseclass/CaseClassSerializationTest.scala

Currently when we try to serialize `@TypeInfo` case class with fields defined inside of its body we get `IndexOutOfBoundsException`. 
For example serializing case class:
```
@TypeInfo(classOf[SimpleCaseClassWithAdditionalField.TypeInfoFactory])
final case class SimpleCaseClassWithAdditionalField(constructorField: String) {
val bodyField: String = "body " + constructorField
}
object SimpleCaseClassWithAdditionalField {
class TypeInfoFactory extends CaseClassTypeInfoFactory[SimpleCaseClassWithAdditionalField]
}
```
Will throw the following exception:
```
1
java.lang.IndexOutOfBoundsException: 1
at scala.runtime.Statics.ioobe(Statics.java:196)
at pl.touk.nussknacker.engine.flink.api.typeinfo.caseclass.SimpleCaseClassWithAdditionalField.productElement(CaseClassSerializationTest.scala:61)
at …
```

Fix Scala case class with fields in body serialization

---

docs/Changelog.md
utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/SynchronousExecutionContextAndIORuntime.scala

`SynchronousExecutionContextAndIORuntime` provides sync IORuntime. The runtime is rather dummy and there is no simple way to close it properly. We thought that there was no simple way to close it, but the closing is not required because it's a dummy. It figures out that it's not so true, because by default, during creation, MBean is registered. We don't need the monitoring functionality provided by the MBean, so we simply disable it before creating the sync IORuntime. Now, we consider it really a dummy one.

[NU-1609] fixed: Nu runtime memory leak 

---

utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/config/CustomFicusInstances.scala
utils/utils/src/test/scala/pl/touk/nussknacker/engine/util/config/CustomFicusInstancesSpec.scala

We hit few cases of [Lightbend Config string length limitations](https://github.com/lightbend/config/issues/627), so I'm proposing a generic decoder that can make working with a workaround (basically writing long strings as lists of shorter strings) a bit easier.

Make CustomFicusInstances extendable

---

utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/config/CustomFicusInstances.scala

Follow-up to #5913, allows for overriding of `ValueReader[String]`.

Use explicit readers in CustomFicusInstances

---

designer/client/src/components/toolbars/search/utils.ts

Variable expression value was qualified as "Output" category in search results:
Fixed, expression value goes into "Value" category:

Fix search node qualifier (selector) for variable node

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfig.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfigTest.scala

`object DeploymentCommentSettings` was never used in "production" code. It was only used (tested) in tests. I see two ways:
1. remove `object DeploymentCommentSettings`
2. use it to validate configuration
And here I go with the latter option.

Bring back deploymentCommentSettings validation

---

engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/async/DefaultServiceExecutionContextPreparer.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala

We've run into the problem a few times now with the scenario getting a closed (Terminated) pool of threads from before the restart.
The idea is to remove the mechanism of atomic counting of the number of calls to open/close the pool. Instead, we use the "closeAsyncExecutionContext" hook and in the case of pool closure, we simply unregister user's class loader from Flink and reset the static variable: DefaultServiceExecutionContextPreparer#asyncExecutionContext.
BEWARE:  Asynchronous tests can still have this problem, because the tests share the same class loader, and in parallel execution that class loader is not unloaded - resulting in the pool not being closed!

[NU-1657] Fixup to async DefaultAsyncExecutionContextPreparer

---

designer/client/src/components/MenuBar/TabElement.tsx
designer/client/src/components/MenuBar/menu.tsx
designer/client/src/containers/DynamicTab.tsx

replace this <img width="438" alt="Zrzut ekranu 2024-05-22 o 11 43 51" src="https://github.com/TouK/nussknacker/assets/965924/3ba317c4-a394-4cec-80c9-b60d265a8601"> with some civilized version

added `spacerBefore` prop in menu element to allow adding separators

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessActionRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessDBQueryRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/base/it/WithAccessControlCheckingConfigScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
docs/Changelog.md

This PR fixes the discrepant (and in the case of `lastDeployedActionData` incorrect in both cases) behaviour of `lastStateActionData/lastDeployedActionData` determining between `fetchLatestProcessDetailsByQueryAction` and `fetchProcessDetailsForVersion`
Here are the behaviours BEFORE the changes in this PR: ('list' is `fetchLatestProcessDetailsByQueryAction`, 'single' is `fetchProcessDetailsForVersion`)
lastActionData:
- 'single' and 'list' - latest action out of those that are `Finished/ExecutionFinished`
lastStateActionData:
- 'single' - latest action out of those that (are `Finished/ExecutionFinished` _**AND**_ are state actions)
- 'list' - latest action out of those that (are `Finished/ExecutionFinished`) **_IF IT IS_** a state action
lastDeployedActionData (could be renamed to …

Fix last action data determining

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NuDesignerApiAvailableToExposeYamlSpec.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthManager.scala

After [impersonation changes](https://github.com/TouK/nussknacker/pull/6053) when anonymous access was not configured and user tried to access main page he was getting authentication error.
It happend beacuse regardless of whether anonymous access was configured or not `NoCredentialsProvided` were passed further in the Authentication.
To fix that i added one check which was present before impersonation changes:
`case (None, None) if !anonymousAccessEnabled => DecodeResult.Missing`
With that when user enters the main page he gets possibility to log in with basic auth.

[NU-1649] Fix situation where no credentials were provided and anonymous access is not permitted

---

designer/client/src/components/modals/CustomActionDialog.tsx
designer/client/src/components/toolbarSettings/actions.ts
designer/client/src/components/toolbars/actions/buttons/CustomActionButton.tsx
designer/client/src/components/toolbars/scenarioActions/buttons/CancelDeployButton.tsx
designer/client/src/components/toolbars/scenarioActions/buttons/CustomActionButton.tsx
designer/client/src/components/toolbars/scenarioActions/buttons/DeployButton.tsx
designer/client/src/stylesheets/variables.ts

Two problems (staging, v1.16):
1) When comment validation fails error message expands action dialog box. 
~2) Inconsistent position of actions buttons: deploy and cancel are centered, custom actions are aligned to the right~
Fix:
1) Long error message does not change the width of the dialog
~2) For all actions footer buttons are centered.~

Fixed width for actions dialogs when error message is too long

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/DeploymentRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/synchronize/DeploymentsStatusesSynchronizer.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/mock/MockDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/flink/FlinkJarManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/FlinkClientStub.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/CachedFlinkClient.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/FlinkClient.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/HttpFlinkClient.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/flinkRestModel.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/rest/FlinkHttpClientTest.scala
engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/EmbeddedDeploymentManager.scala

+ synchronisation of statuses uses job details endpoint instead of jobs overview + job config endpoints

[NU-1712] Passing deployment ID as a Flink's job's ID

---

designer/client/src/components/graph/node-modal/ScenarioProperty.tsx
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala

Currently there is a missmatch between what FE expects and BE provides while fetching `ProcessDefinitionData`.
Frontend's `ScenarioPropertiesConfig` contains attribute `values: Array<PossibleValue>` however backend does not return that. Instead it returns `defaultValue: Option[String]` which is ignored by the FE.
The `values` attribute isn't utilized on Frontend so I aligned the attribute to the BE response:
```  
@JsonCodec final case class UiScenarioPropertyConfig(
defaultValue: Option[String],
editor: ParameterEditor,
label: Option[String]
)
````
I noticed that mismatch when I had to use the `defaultValue` in an external project.

Fix FE ScenarioPropertyConfig's attribute to align to the BE response

---

designer/client/jest.config.js
designer/client/src/components/graph/Graph.tsx
designer/client/webpack.config.ts

- In jointjs package.json there is a sideEffects flag set to false, which effectively means "this imported module is not used anywhere in the application" for a webpack and `import "jointjs/dist/joint.css";` is not used anywhere from a webpack perspective. We need to set explicitly this flag to true in case of CSS files in the webpack config
- Remove absolute `styl` from our codebase and config
- Import minified version of jointsjs css

[NU-1559] fix joint js style loading

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/component/ComponentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/ScenarioStatistics.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/CustomComponentService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/ScenarioStatisticsTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsServiceTest.scala

Remove creating `ComponentListElement` DTOs just to get component usages.
Instead, map of usages per `DesignerWideComponentId` is provided by `ComponentService` and then mapped by id to available components

[NU-1719] Component statistics without restmodel

---

docs/Changelog.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMain.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/testmode/ResultsCollectingListener.scala

[NU-1683] Fixes memory leak in test mechanism introduced in #4956

---

designer/client/src/components/comment/StyledComment.tsx
designer/client/src/components/modals/GenericAction/GenericActionDialog.tsx
designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx
designer/client/test/CommentContent-test.tsx

3 small fixes
1. Error when submitting empty field in ad hoc form (was caused by omitting empty fields when setting form state causing `Cannot read properties of undefined (reading 'expression')` in editors
2. No ad hoc form header styling caused by not passing className prop (was raising warnings since the component was used in 2 contexts - one requiring passing className) - still not an ideal solution
Before:
After:
3. No styling in comment links in comment panel
Before:
After:

[NU-1697] Fix ad hoc submitting empty field error and other small fixes

---

designer/client/cypress/e2e/process2.cy.ts
designer/client/src/components/toolbars/search/SearchPanel.tsx

Search node panel updates:
1. Do not catch ctrl-f event to move focus and cursor to node search. Users use ctrl-f to engage browser search as a last stand solution to search anything within UI.
2. Use exact phrase to search nodes.
Need backport to 1.15 and 1.16.

Fix search nodes panel (do not catch ctrl f)

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/Utils.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/UtilsSpec.scala

The changes in https://github.com/TouK/nussknacker/pull/5907 proved insufficient, because `gracefulStop` patiently waits for the actor to finish processing ALL it's queued messages, which is a bit too graceful.
After the change, it will only finish it's currently processing message then stop.

Stop deployment and reschedule actors less gracefully on reload

---

docs/Changelog.md
docs/MigrationGuide.md
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/service/EagerServiceWithStaticParameters.scala

At `EagerServiceWithStaticParameters.returnType` we return `ValidatedNel[ProcessCompilationError, TypingResult]`. Most of  the `ProcessCompilationError` implementation requires nodeId, so it seems obvious that we need to pass nodeId on the `returnType`  call.

Improvement: Pass implicite nodeId at EagerServiceWithStaticParamers. returnType

---

designer/client/src/components/graph/node-modal/fragment-input-definition/settings/variants/StringBooleanVariants/useGetAllDicts.ts
designer/client/src/http/HttpService.ts

Currently `type` is hardcoded as `TypedClass` string. 
With this change we add a possibility to pass different `type` while fetching Dicts.

Add type to FE http service Dict api

---

.github/workflows/pr.yml

- so we remove triggering the benchmark from the pipeline definition

benchmark is no longer available in the Quickstart repo

---

docs/configuration/Common.md
docs/configuration/ScenarioDeploymentConfiguration.md
docs/configuration/index.md
docs/configuration/model/ModelConfiguration.md
docs/integration/OpenAPI.md
docs/integration/Sql.md
docs/scenarios_authoring/Enrichers.md

The section on the environment variables was removed from the Configuration overview document, leaving only the overview and concepts in this document. Environment variables are now in a dedicated page (same path), the title of the page is "Common"
<This checklist does not apply>

removed environmental variables from the main configuration doc

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/ConfigParameterDefaultValueDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/EditorBasedLanguageDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/OptionalityBasedDefaultValueDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/SimpleLanguageDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/TypeRelatedParameterValueDeterminer.scala

little change to make `ConfigParameterDefaultValueDeterminer` language aware.

language of parameter's expression is based on editor type

---

docs/Changelog.md
engine/flink/components/base-unbounded/src/main/scala/pl/touk/nussknacker/engine/flink/FlinkBaseUnboundedComponentProvider.scala
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/DelayTransformer.scala
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkBaseComponentProvider.scala
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/PreviousValueTransformer.scala

Delay and previousValue can be used in the same way in bounded as in unbounded types. There's no reason not to use them in bounded.

Extension: Move previousValue and delay components from unbounded to base Flink components

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypeEncoders.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/CommonSupertypeFinder.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultErrorMessagesSpec.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultSpec.scala
components/sql/src/main/scala/pl/touk/nussknacker/sql/db/schema/TableDefinition.scala
docs/MigrationGuide.md
engine/common/components/src/main/scala/pl/touk/nussknacker/engine/common/components/DecisionTable.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregatesSpec.scala
engine/flink/components/base-unbounded/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/aggregates.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/source/TableSource.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/utils/DataTypesConversions.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/utils/RowConversions.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetection.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetectionSpec.scala
engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/global/DocumentationFunctions.scala
engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/DynamicParametersSource.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/KafkaAvroPayloadSourceFactorySpec.scala
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/RequestResponseTestWithParametersTest.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/BuiltInNodeCompiler.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/variables/MetaVariables.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/compile/validationHelpers.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/typing/TypingUtils.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/typed/AvroSchemaTypeDefinitionExtractor.scala

[NU-1766] TypedObjectTypingResult.fields are backed by ListMap for correct RowTypeInfo fields order purpose

---

build.sbt
docs/Changelog.md
engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala

Added a workaround for situations when an updated scenario with Kafka source started reading from the earliest offsets.
Explanation is in code comments.

Work around Kafka source resetting to earliest offsets on some state restores

---

docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/EditorPossibleValuesBasedDefaultValueDeterminer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/EditorPossibleValuesBasedDefaultValueDeterminerTest.scala

Currently when Component's parameter has `DictParameterEditor` editor type with no default value provided. It's language is set to `spel` instead of `DictKeyWithLabel` by `NodeDependency.finalDefaultValue`. This change properly establishes dictionary's langauage in case no default value is provided.

Determine dictionary parameter editor language when no default value is present

---

docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/EditorPossibleValuesBasedDefaultValueDeterminer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/EditorPossibleValuesBasedDefaultValueDeterminerTest.scala

Cherry-pick of changes in https://github.com/TouK/nussknacker/pull/6685

Determine dictionary parameter editor language when no default value is present (#6685)

---

designer/client/src/components/graph/node-modal/NodeDetailsContent/selectors.tsx
designer/client/src/components/graph/node-modal/nodeDetails/NodeDetailsModalHeader.tsx
designer/client/src/components/graph/node-modal/properties.tsx
designer/client/src/types/scenarioGraph.ts
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/DefinitionsService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionsServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
docs/configuration/model/ModelConfiguration.md
nussknacker-dist/src/universal/conf/dev-application.conf

* Added docsUrl to PropertiesConfig on BE, added docsUrl icon display in properties on FE

Added docsUrl to PropertiesConfig (#6578)

---

docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

[NU-1801] Fix no validation when indexing on Lists and Maps

---

designer/server/src/main/scala/db/migration/V1_056__CreateScenarioActivitiesDefinition.scala
designer/server/src/main/scala/db/migration/V1_057__MigrateActionsAndCommentsToScenarioActivitiesDefinition.scala
designer/server/src/main/scala/db/migration/hsql/V1_057__MigrateActionsAndCommentsToScenarioActivities.scala
designer/server/src/main/scala/db/migration/postgres/V1_057__MigrateActionsAndCommentsToScenarioActivities.scala
designer/server/src/test/scala/db/migration/V1_057__MigrateActionsAndCommentsToScenarioActivities.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/base/db/DbTesting.scala

There was a problem with UUID generation. Query generated by Slick always used the same UUID for all activities, instead of generating new one for each comment.

[Fix][NU-1772] Scenario activities migration fix

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/DictsFlowTest.scala
docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/ComponentExecutorFactory.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala

Currently, there is a problem with nodes that utilize presets as sometimes labels are not present and are presented as `null`. 
This happens when we want to use a component or fragment with presets, select some values for them and save the scenario. 
If there were any errors during compilation of that node presets will have null labels.
This happens because `ProcessDictSubstituor` dynamically adds and removes presets' labels.
```
if (expr.language == Expression.Language.DictKeyWithLabel && !expr.expression.isBlank) {
if (isReverse)
addLabelToDictKeyExpression(process, expr, optionalExpressionTypingInfo, nodeExpressionId)
else
removeLabelFromDictKeyExpression(process, expr, nodeExpressionId) // no need to keep label in BE
```
To add labels at that level we need parameters' types which are …

Preserve typing information during expression compilation

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/component/ComponentProvider.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/component/NussknackerVersionTest.scala
docs/Changelog.md
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/source/FlinkMiniClusterTableOperations.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/test/ModelDataTestInfoProvider.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/testmode/TestDataPreparer.scala
utils/test-utils/src/main/scala/pl/touk/nussknacker/test/installationexample/DockerBasedNuInstallationExampleEnvironment.scala

Fix for testing mechanism for table sources: using full, model classpath instead of only flinkTable.jar

---

docs/Changelog.md
docs/MigrationGuide.md
engine/flink/scala-utils/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinfo/caseclass/CaseClassTypeInfoFactory.scala

Improvement: TypeInformation support for scala.Option

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/suggester/ExpressionSuggester.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ExpressionSuggesterSpec.scala
docs/Changelog.md
docs/scenarios_authoring/Spel.md
scenario-compiler/src/main/java/pl/touk/nussknacker/engine/spel/NuReflectiveMethodExecutor.java
scenario-compiler/src/main/java/pl/touk/nussknacker/engine/spel/internal/ConversionAndExtensionAwareMethodsDiscovery.java
scenario-compiler/src/main/java/pl/touk/nussknacker/engine/spel/internal/ConversionAndExtensionsAwareMethodInvoker.java
scenario-compiler/src/main/java/pl/touk/nussknacker/engine/spel/internal/RuntimeConversionHandler.java
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/extension/Cast.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/extension/ExtensionMethods.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSuggester.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/internal/OptimizedEvaluationContext.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/util/classes/Extensions.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/definition/component/parameter/validator/ValidationExpressionParameterValidatorTest.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/util/classes/ExtensionsSpec.scala

[NU-1701] Casts suggester

---

designer/client/src/components/graph/node-modal/editors/expression/DictParameterEditor/DictParameterEditor.tsx
docs/Changelog.md

Currently, when user wants to change the selected value in dict editor and see possible options he firstly has to manually delete the value:
With this little change on editor open user will be presented with all the options so he does not have to delete the value first.

Show all dict values on dict parameter editor open

---

designer/client/src/components/graph/node-modal/fragment-input-definition/settings/variants/fields/UserDefinedListInput.tsx

In this PR I add the following "Add" button when defining "User defined list" inside fragments input definition:

[NU-7016] Introduce Add button when typing element in user defined list

---

designer/server/src/main/resources/db/migration/hsql/V1_059__FixLineBreaksInActivityAdditionalProperties.sql
designer/server/src/main/resources/db/migration/postgres/V1_059__FixLineBreaksInActivityAdditionalProperties.sql

Plaintext activity details from old tables (for example for migration or automatic update) were migrated as part of the JSON in the new table. Newlines were incorrectly migrated as line breaks instead of \n in previous migrations.

[NU-1772] Fix line breaks in ScenarioActivities db table

---

docs/Changelog.md
docs/scenarios_authoring/Spel.md
engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/clazz/ClassDefinitionDiscovery.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/clazz/ClassDefinitionSet.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/internal/OptimizedEvaluationContext.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/internal/propertyAccessors.scala
scenario-compiler/src/test/java/pl/touk/nussknacker/engine/spel/JavaClassWithStaticParameterlessMethod.java
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/TyperSpec.scala

For now we want:
* enable by default dynamic access using indexer operator for expressions typed to Unknown
* computed type for such an access is always Unknown (or concrete type if property is known)

NU-1827 allow dynamic access via indexer operator on expressions typed to unknown

---

build.sbt
docs/Changelog.md
docs/MigrationGuide.md
docs/configuration/model/Flink.md
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/docker/WithFlinkContainers.scala
examples/dev/nu-scala213.override.yml

We build Nu with Scala 2.13.12 and use Tapir built with Scala 2.13.13, which is incompatible - see SIP-51 for details. If we were using sbt 1.10.0+ our build would fail.

Update Scala 2.13 to 2.13.15

---

engine/flink/components-api/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinformation/FlinkTypeInfoRegistrar.scala
engine/flink/components-api/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinformation/TypeInformationDetection.scala
engine/flink/components-api/src/test/scala/pl/touk/nussknacker/engine/flink/api/typeinformation/FlinkTypeInfoRegistrarTest.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/ExecutionConfigPreparer.scala

[NU-1848] Work around for broken compatibility with Flink < 1.19: environment variable allowing to disable Flink TypeInfos

---

designer/client/cypress/e2e/activities.cy.ts
designer/client/src/components/modals/ModifyActivityCommentDialog.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItem.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItemComment.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItemCommentModify.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItemHeader.tsx
designer/client/src/components/toolbars/activities/helpers/extendActivitiesWithUIData.ts
designer/client/src/components/toolbars/activities/types.ts
designer/client/src/components/toolbars/activities/useActivitiesSearch.test.ts
designer/client/src/windowManager/ContentGetter.tsx
designer/client/src/windowManager/WindowKind.tsx

- fix searching for removed attachment name in activities
- Provide the right padding to the activity icons
- Provide separate title and confirmation button text for add/edit activity comment

Nu 1865 activities changes

---

.github/workflows/benchmark-e2e.yml
.github/workflows/benchmark-jmh.yml
.github/workflows/pr.yml

[NU-1866] Bump GitHub actions artifact plugins

---

docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/language/dictWithLabel/DictKeyWithLabelExpressionParser.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/language/dictWithLabel/DictKeyWithLabelExpressionParserTest.scala

Since `TypedClass` does not have information about passed value `valueOpt = None :: Option[Any]` I propose to lift this `TypingResult` into `TypedObjectWithValue` at the stage of passing down `TypingResult` to `DictKeyWithLabelExpression`. The fact of this `valueOpt` being `None` leads to the validation problem when `CompileTimeEvaluableValueValidator` is being used for `DictKeyWithLabelExpression`'s.
For more context, see linked issue to this PR.

[NU-7142] Lift TypingResult information for dictionaries 

---

engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala

More logging while cancelling Flink jobs
