designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala

Initialize providers in designer only once

---

docs/Changelog.md
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafaUniversaJsonFunctionalTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/utils/JsonTestData.scala
engine/lite/components/request-response/src/main/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/jsonschema/sinks/JsonRequestResponseSinkFactory.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/JsonSchemaOutputValidator.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/JsonSchemaOutputValidatorPrinter.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/encode/JsonSchemaOutputValidatorTest.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/AvroSchemaOutputValidator.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/ParsedSchemaSupport.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/UniversalSchemaSupport.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/sink/KafkaAvroSinkFactory.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/encode/JsonSchemaOutputValidatorTest.scala

Sink validaiton of JsonSchema with addtionalProperties

---

engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/sink/flink/UniversalKafkaSinkValidationSpec.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafaUniversaJsonFunctionalTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalAvroSchemaFunctionalTest.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/output/OutputValidatorErrorsConverter.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/output/OutputValidatorErrorsMessageFormatter.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/JsonSchemaOutputValidator.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/AvroSchemaOutputValidator.scala

improve error msg for type validation errors in Sinks

---

docs/Changelog.md
docs/MigrationGuide.md

Cleanup changelog before 1.7

---

build.sbt

consistent jackson version

---

build.sbt
project/build.properties
project/plugins.sbt

Upgrade sbt + some plugins

---

engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerKafkaTest.scala

K8s test fix - realistic CPU requests

---

docs/scenarios_authoring/Spel.md

minor fix in Spel docs

---

components/openapi/src/test/resources/swagger/recursive.yml
components/openapi/src/test/scala/pl/touk/nussknacker/openapi/parser/SwaggerParserTest.scala
docs/Changelog.md
docs/integration/OpenAPI.md
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala

Handle recursive schema in OpenAPI with fallback

---

engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalJsonFunctionalTest.scala
engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/BestEffortJsonSchemaEncoder.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/encode/BestEffortJsonSchemaEncoderTest.scala

More friendly encode error messages

---

engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
engine/lite/components/request-response/src/main/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/jsonschema/sinks/JsonRequestResponseSinkFactory.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/GenericNodeTransformationValidator.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/validationHelpers.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/sink/UniversalKafkaSinkFactory.scala

Avoid infinite loop with buggy NodeTransformer

---

security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/JwtTokenAuthenticationSpec.scala

Increase security test timeout

---

components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseToSwaggerService.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseToSwaggerServices.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/SecuritiesParser.scala
components/openapi/src/test/resources/swagger/incorrect-service.yml
components/openapi/src/test/resources/swagger/recursive.yml
components/openapi/src/test/resources/swagger/service-security.yml
components/openapi/src/test/resources/swagger/swagger-3.1-array.yml
components/openapi/src/test/scala/pl/touk/nussknacker/openapi/parser/SwaggerParserTest.scala
docs/Changelog.md
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/parser/ParseSwaggerRefSchemas.scala

- Handle some null pointers
- Improve error message
- Fix problems with typing arrays in OpenAPI 3.1

OpenAPI edge cases

---

dockerhub/nussknacker/README.md
docs/integration/KafkaIntegration.md

Minor docs fixes

---

.run/NussknackerApp.run.xml
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/DeploymentManagerProvider.scala
designer/runServer.sh
designer/server/src/main/resources/defaultDesignerConfig.conf
designer/server/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/config/UsageStatisticsReportsConfig.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/ProcessingTypeUsageStatistics.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsHtmlSnippet.scala
designer/server/src/test/resources/designer.conf
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsHtmlSnippetTest.scala
nussknacker-dist/src/universal/bin/nussknacker-entrypoint.sh
nussknacker-dist/src/universal/bin/run.sh

Deployment manager stats + source field

---

utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractorTest.scala

JSON Schema: handle anyOf/oneOf for object schemas

---

designer/client/actions/nk/assignSettings.ts
designer/client/containers/NussknackerApp.tsx
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/WebResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettings.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/SettingsResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsTest.scala

Usage statistcs reporting trggered by FE client

---

e2e-tests/docker-compose.yml
e2e-tests/test/pong.bats
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/DockerTest.scala
engine/lite/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/BaseNuKafkaRuntimeDockerTest.scala
utils/kafka-components-utils/src/it/scala/pl/touk/nussknacker/engine/kafka/validator/CachedTopicsExistenceValidatorTest.scala

kafka & sr docker images to latest versions

---

components/openapi/src/test/scala/pl/touk/nussknacker/openapi/parser/SwaggerParserTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalJsonFunctionalTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/utils/JsonTestData.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/BestEffortJsonSchemaEncoder.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/extractor/JsonToNuStruct.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractorTest.scala

Fix support for enum type in JsonSchema

---

engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/extractor/JsonToNuStruct.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractorTest.scala

Decoding recursive schemas

---

engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/extractor/JsonToNuStruct.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/SwaggerBasedJsonSchemaTypeDefinitionExtractorTest.scala

Decoding recursive schemas (#3817)

---

designer/client/actions/nk/processUtils/saveProcess.ts
designer/client/http/HttpService.ts

Don't send ValidationResult on process update

---

docs/MigrationGuide.md
utils/schemed-kafka-components-utils/src/main/java/org/apache/flink/formats/avro/typeutils/NkSerializableParsedSchema.java
utils/schemed-kafka-components-utils/src/test/scala/org/apache/flink/formats/avro/typeutils/NkSerializableParsedSchemaSpec.scala

Fix for Flink serialization of large schemas

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala

Terminate ActorSystem if initialization fails

---

designer/client/http/HttpService.ts

One more place with too much data sent

---

designer/client/containers/NussknackerApp.tsx
designer/client/http/HttpService.ts

restore reporting refferer in user statics reports

---

build.sbt
designer/server/src/main/resources/defaultDesignerConfig.conf
security/src/test/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticationResourcesSpec.scala

Fix max-connection-backoff for akka-http in designer

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
docs/Changelog.md

To be merged after releasing 1.7.

Remove /subprocessDetails in favor of /processesDetails?isSubprocess=true

---

.github/workflows/pr.yml
designer/client/cypress.config.ts
designer/client/cypress/plugins/index.js
designer/client/cypress/support/overrides.ts
designer/client/package-lock.json
designer/client/package.json
designer/client/webpack.config.js

One run snapshots

---

.github/workflows/pr.yml
e2e-tests/docker-compose.yml
e2e-tests/setupAndRun.sh
e2e-tests/test/helpers.bash

Self hosted runner

---

docs/Changelog.md
docs/MigrationGuide.md

Added date of release for v1.7.0 in docs

---

build.sbt
utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/EmbeddedKafkaServer.scala

Bump Kafka to 3.3.1

---

.github/workflows/pr.yml
build.sbt
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerConfig.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/deployment/DeploymentPreparerTest.scala

cross publish docker images

---

designer/server/src/main/resources/defaultDesignerConfig.conf
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/metrics/RepositoryGauges.scala
designer/server/src/test/resources/designer.conf

Configurable repository gauges cache length

---

build.sbt

Upgrade some libraries to their newest versions

Bump dependencies

---

.github/workflows/pr.yml

Fix Graal error during build

---

docs/Changelog.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/FlinkScenarioNameValidator.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/FlinkScenarioNameValidatorSpec.scala

Synchronize with release/1.7

---

build.sbt

change default scala version to 2.13

---

CONTRIBUTING.md
project/plugins.sbt

Bump sbt-native-packager

---

interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompilationResult.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/canonize/MaybeArtificial.scala

No weird warnings on artificial nodes

---

docs/integration/OpenAPI.md
docs/scenarios_authoring/TestingAndDebugging.md

Update testing docs

---

designer/client/components/toolbars/Survey.tsx
designer/server/src/main/resources/defaultDesignerConfig.conf

Update survey texts

---

designer/client/http/HttpService.ts
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessCategoryService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
docs/Changelog.md

Add endpoint to get category with processingType

---

components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/OpenApiScenarioIntegrationTest.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/ServiceRequest.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/package.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseToSwaggerService.scala
docs/Changelog.md

Add content-type to openapi enrichers

---

components/openapi/src/it/scala/pl/touk/nussknacker/openapi/functional/OpenApiScenarioIntegrationTest.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/ServiceRequest.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/package.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/parser/ParseToSwaggerService.scala
docs/Changelog.md

* Add content-type to openapi enrichers
* Add test
* Review - simplify

Update fixes branch - Add content-type to openapi enrichers (#3958)

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestCategories.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestPermissions.scala
docs/Changelog.md
engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala

Filter services based on user permissions

---

designer/client/actions/nk/assignSettings.ts
designer/client/containers/EnvironmentTag.tsx
designer/client/reducers/selectors/settings.ts

Fix FE crash when environmentAlert is null

---

build.sbt

compile to java11 bytecode for scala 2.13

---

build.sbt

fix 'prepareDev' sbt task

---

version.sbt

set 1.9.0-SNAPSHOT version

---

docs/scenarios_authoring/Spel.md

DateTime info  in Scenario Authoring - cosmetics

---

build.sbt
docs/Changelog.md
engine/flink/management/src/it/resources/docker/Dockerfile

bump flink to 1.16.1

---

utils/kafka-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/exception/KafkaErrorTopicInitializer.scala

set timeout on topics listing in KafkaErrorTopicInitializer

---

engine/lite/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/utils/NuRuntimeDockerTestUtils.scala

use lite image tagged with scala version in tests

---

.github/workflows/pr.yml
.k3d/k3s_manifests/ingress-controller.yaml
.k3d/single-cluster.yml
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala

bump k3d to 5.4.7 and k3s to v1.25.6

---

designer/submodules/package-lock.json
designer/submodules/packages/components/package.json
designer/submodules/packages/legacy_scenarios/package.json

downgrade react-router to 6.3.0

---

engine/lite/components/request-response/src/main/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/jsonschema/sinks/JsonRequestResponseSinkFactory.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/sinkvalue/SinkValueData.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/sink/UniversalKafkaSinkFactory.scala

Editor validation param name

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/CustomActionInvokerService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentManagerDispatcher.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ProcessStateService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/test/ScenarioTestService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActorSpec.scala

ManagementActor - lightening

---

build.sbt
security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/GenericOidcServiceSpec.scala

bump testcontainers-keycloak version

---

docs/Changelog.md
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/serialization/UniversalKafkaDeserializerTest.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/AvroUtils.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/SchemaWithMetadata.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/serialization/AzureAvroSerializerFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/ConfluentUtils.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClient.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/CachedConfluentSchemaRegistryClientFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/ConfluentSchemaRegistryClient.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/client/MockConfluentSchemaRegistryClientFactory.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/formatter/UniversalRecordFormatterSpec.scala

Forward port:  Fix for: generate test data mechanism didn't work for json messages with defined schema id

---

docs/installation_configuration_guide/DeploymentManagerConfiguration.md

Docs: how to configure custom ingress class name

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessingTypeDeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/EspErrorToHttp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/notifications/NotificationService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/CustomActionInvokerServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/LoggedUserConversions.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ProcessStateServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ScenarioTestExecutorServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/DefaultProcessingTypeDeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/test/ScenarioTestService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/util/LocalNussknackerWithSingleModel.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/StubManagementService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/DBProcessServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReaderSpec.scala

Refactor: Designer loosely coupled with ManagementActor

---

docs/Changelog.md
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalJsonFunctionalTest.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/encode/BestEffortJsonSchemaEncoder.scala
utils/json-utils/src/test/scala/pl/touk/nussknacker/engine/json/encode/BestEffortJsonSchemaEncoderTest.scala

Fix encoding object in sink with JSON schema pattern properties

---

common-api/src/main/scala/pl/touk/nussknacker/engine/api/CirceUtil.scala

Fix empty error message in decodeJsonUnsafe

---

build.sbt

Nu scala version switcheable by env variable

---

build.sbt
release.sh
version.sbt

fix release script

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/EspErrorToHttp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesConcurrentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/StubManagementService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestProcessChangeListener.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementServiceSpec.scala
docs/Changelog.md

Removed conccurrent deployments check limitation

---

nussknacker-dist/src/universal/conf/dev-application.conf

Service tab removal

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ManagementActor.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesConcurrentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockDeploymentManager.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/ManagementServiceSpec.scala

Fix for: When deploys were ran concurrently, invalid status is returned

---

.github/workflows/pr.yml

Increase Xmx & Xms in CI

---

docs/installation/Installation.md

update nginx config snippet for public path

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/AvroSchemaOutputValidator.scala

TypingResult.primitiveClass for easier checking if numeric is assignable to other numeric (simpler logic of AvroSchemaOutputValidator)

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/notifications/NotificationService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentActionsInProgressActor.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentActionsInProgressRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
docs/Changelog.md

Removal of notifications about scenarios during deploy

---

build.sbt
docs/Changelog.md
security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticator.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticationResourcesSpec.scala

Change BCrypt library

---

components/sql/src/main/scala/pl/touk/nussknacker/sql/service/DatabaseEnricherInvoker.scala
components/sql/src/main/scala/pl/touk/nussknacker/sql/service/DatabaseEnricherInvokerWithCache.scala
components/sql/src/test/scala/pl/touk/nussknacker/sql/service/DatabaseQueryEnricherWithCacheTest.scala
docs/Changelog.md
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkProcessTestRunner.scala

fix database query invoker to be async

---

nussknacker-dist/src/universal/conf/dev-application.conf

disable deployment comment validation in dev

---

designer/server/src/main/resources/db/migration/hsql/V1_036__ProcessActionState.sql
designer/server/src/main/resources/db/migration/postgres/V1_036__ProcessActionState.sql

ProcessActionState migration fix - added uuid generation for id

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockDeploymentManager.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/util/DBIOActionValues.scala

SQLTransactionRollbackException, with message: transaction rollback: serialization failure was thown by prepareDeployedProcess(processName).dbioActionValues

DeploymentServiceSpec flaky test fix?

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala

Fix for NPE during handling int schemas without ranges on scala 2.12

---

docs/installation_configuration_guide/DesignerConfiguration.md

A bit clearer structure of the security config

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/StubDeploymentService.scala
docs/Changelog.md

+ refactor: now only DeploymentService is responsible for scenario state computation. Before the change, this logic was in resource class

Presenting in progress actions on scenario list

---

CONTRIBUTING.md

add docs desribing contributing to docs

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/ProcessValidationSpec.scala
docs/Changelog.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/node.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/split/ProcessSplitter.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/splittedgraph/SplittedNodesCollector.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/splittedgraph/splittednode.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/canonize/ProcessCanonizer.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala

fix compiling scenarios with filter with only false edge

---

designer/submodules/packages/components/src/common/filters/filtersContext.tsx
designer/submodules/packages/components/src/components/componentsRoutes.tsx
designer/submodules/packages/components/src/components/rootRoutes.tsx
designer/submodules/packages/components/src/navigation.tsx
designer/submodules/packages/components/src/root.tsx
designer/submodules/packages/components/src/scenarios/scenariosView.tsx

fixed filter/query loop on screnarios

---

.github/workflows/pr.yml

short git sha in NU version

---

designer/server/src/main/resources/defaultDesignerConfig.conf
designer/server/src/test/resources/designer.conf
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/ConfigurationTest.scala

Obsolete attachmentsPath configuration property removal

---

.github/workflows/pr.yml
designer/server/src/main/resources/defaultDesignerConfig.conf

Fix default submodules urls when NU served from custom context-path

---

designer/client/containers/Visualization.tsx
designer/submodules/packages/components/src/scenarios/useScenariosQuery.tsx
docs/Changelog.md

Reduced status api calls

---

designer/client/components/SvgDiv.tsx
designer/client/components/UrlIcon.tsx
designer/client/components/common/ErrorBoundary.tsx
designer/client/test/Process/ProcessStateIcon-test.tsx
designer/client/test/Process/__snapshots__/ProcessStateIcon-test.tsx.snap

add default fallback icon to avoid crash if src is null

---

.github/workflows/pr.yml

docker based test without npm cache

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessStateDefinitionManager.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/DefaultProcessingTypeDeploymentService.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessState.scala

Refactor: Periodic - merge Flink's process state with deployments state in db done in Service

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ScenarioResolver.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ScenarioTestExecutorService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/subprocess/SubprocessResolver.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
docs/Changelog.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompiler.scala
engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/ScenarioInterpreterFactory.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/SubprocessComponentDefinitionExtractor.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/AdditionalVariableSpec.scala

Fix for: Deadlock during resolving fragments by EmbeddedDeploymentManager

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/RemoteEnvironmentResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/RemoteEnvironmentResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestProcessUtil.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
docs/MigrationGuide.md

Handling failed migration when target process archived on remote 

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactorySpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/SubprocessResolver.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/SubprocessComponentDefinitionExtractor.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala

Fix in fragment definition extraction: properly handling empty fragments

---

designer/server/src/main/scala/pl/touk/nussknacker/engine/CombinedProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/AppResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/initialization/Initialization.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/NewProcessPreparer.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentManagerDispatcher.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/ProcessModelMigrator.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/TestModelMigrations.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReload.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessActionRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/test/ScenarioTestService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettings.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/uiresolving/UIProcessResolving.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/util/LocalNussknackerWithSingleModel.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/AdditionalPropertiesValidator.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/ProcessValidation.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionServiceSpec.scala
docs/Changelog.md

Use combined data in ProcessStateDefinitionService.

ProcessingTypeDataProvider has combined data being a result of all processing types

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/ProcessingTypeUsageStatistics.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettings.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReaderSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsTest.scala

Statistics: handling missing deployment manager type

---

designer/client/src/i18n.ts

i18n path fix

---

designer/client/src/components/Process/ProcessStateIcon.tsx
designer/client/src/components/Process/ProcessStateUtils.ts
designer/client/src/components/toolbars/status/ProcessInfo.tsx
designer/client/src/reducers/index.ts
designer/client/src/reducers/scenarioState.ts
designer/client/src/reducers/selectors/graph.ts
designer/client/src/reducers/selectors/scenarioState.ts
designer/client/test/Process/ProcessStateIcon-test.tsx
designer/client/test/Process/__snapshots__/ProcessStateIcon-test.tsx.snap
designer/client/test/reducer-test.js

initial status fixed

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
docs/Changelog.md

During deploy invalid scenario fix

---

designer/client/webpack.config.js

watch only src in webpack dev

---

designer/client/src/assets/img/arrows/arrow-right.svg
designer/client/src/stylesheets/togglePanel.styl

collapse arrow color fixed

---

.github/workflows/release.yml

GHA Bug, resolution from https://github.com/actions/runner/issues/1483#issuecomment-994747723

Fix release GHA

---

.github/workflows/pr.yml
.k3d/single-cluster.yml

bump k3d & k3s

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsDeterminer.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsDeterminerTest.scala
docs/Changelog.md
docs/MigrationGuide.md
version.sbt

Merge master into staging

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/LazyParameter.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/Service.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/service/EagerServiceWithStaticParameters.scala

EagerService Lifecycle handled in ServiceInvoker - TODOs added

---

designer/client/containers/CustomTabPage.tsx
designer/client/containers/DynamicTab.tsx
designer/client/containers/Metrics.tsx
nussknacker-dist/src/universal/conf/dev-application.conf

metrics fixed

---

.github/ISSUE_TEMPLATE/bug_report.md
CONTRIBUTING.md
README.md
docs/Changelog.md
docs/MigrationGuide.md
docs/developers_guide/GenericFunctions.md
docs/installation/Installation.md
docs/integration/Sql.md

Improve docs

---

components/openapi/src/test/resources/swagger/swagger-20.json
utils/json-utils/src/main/scala/pl/touk/nussknacker/engine/json/swagger/SwaggerTyped.scala

Fix additionalProperty when true/false

---

README.md

Fix broken link :)

---

docs/Changelog.md
engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/ClassExtractionBaseTest.scala
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
interpreter/src/main/scala/pl/touk/nussknacker/engine/TypeDefinitionSet.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/TypeInfos.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/types/EspTypeUtils.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/types/TypesInformationExtractor.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/types/EspTypeUtilsSpec.scala

Add Any/Unknown to fragment's input types

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala

Fix: make getLatestDeployment a public at PeriodicProcessService

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NussknackerApp.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DictResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/TestFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/VerificationFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMain.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompilerTest.scala
engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/ScenarioInterpreterFactory.scala
engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/TestRunner.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/testmode/TestDataPreparer.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelConversionServiceOverrideSpec.scala
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkProcessCompilerWithTestComponents.scala

Test with form for flink fix

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/AuthorizeProcessDirectives.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/RemoteEnvironmentResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/ProcessModelMigrator.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/RemoteEnvironmentResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessPosting.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/initialization/InitializationOnHsqlItSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/initialization/InitializationOnPostgresItSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepositorySpec.scala
docs/Changelog.md
docs/MigrationGuide.md
extensions-api/src/main/scala/pl/touk/nussknacker/security/Permission.scala

Add user info to migrate scenario action

---

.github/workflows/pr.yml

add docker logs of k3d containers

---

docs/Changelog.md
docs/MigrationGuide.md
docs/installation_configuration_guide/DesignerConfiguration.md
security/src/it/resources/keycloak.json
security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/GenericOidcServiceSpec.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthenticationConfiguration.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticator.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/GenericOidcService.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/JwtOAuth2Service.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Profile.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OpenIdConnectProfile.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationConfiguration.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/basicauth/BasicHttpAuthenticationResourcesSpec.scala

fix oidc access token check

---

ciRunSbt.sh

increase heap in CI tests

---

designer/client/src/components/Process/types.ts
designer/deployment-manager-api/src/test/scala/pl/touk/nussknacker/engine/api/deployment/StateStatusCodingSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/EspItTest.scala
designer/submodules/packages/legacy_scenarios/src/components/Process/types.ts
docs/Changelog.md
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessState.scala

Fix for incompatible serialization of status

---

.github/workflows/pr.yml
.github/workflows/test-report.yml
ciRunSbt.sh

Split cross-scala-version tests in seprate jobs

---

.github/workflows/pr.yml
.github/workflows/test-report.yml
ciRunSbt.sh

minor renames in CI

---

engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/DockerTest.scala
engine/lite/integration-test/src/it/scala/pl/touk/nussknacker/engine/lite/kafka/BaseNuKafkaRuntimeDockerTest.scala
utils/kafka-components-utils/src/it/scala/pl/touk/nussknacker/engine/kafka/validator/CachedTopicsExistenceValidatorTest.scala

bump kafka in integration tests

---

docs/Changelog.md
engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/TransformersTest.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/functional/CustomNodeProcessSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/dict/SpelDictTyper.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/TypeReferenceTyper.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

Typer always typing the whole expression

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentsUsageHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala

Flatten implementation for resolving usages inside fragments

---

build.sbt
docs/Changelog.md
engine/flink/management/src/it/resources/docker/Dockerfile

Update Flink to 1.16.2

---

designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx

Fix unnecessary fetchTestFormParameters reload 

---

build.sbt
project/plugins.sbt
security/src/it/scala/pl/touk/nussknacker/ui/security/oauth2/GenericOidcServiceSpec.scala

Minor dependency updates, add sbt-dependency-updates plugin

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/NumberTypesPromotionStrategy.scala
defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/DefaultConfigCreator.scala
docs/Changelog.md
docs/scenarios_authoring/Spel.md
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/date.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/dateFormat.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/geo.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/numeric.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/util.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/BaseSpelSpec.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/CollectionUtilsSpec.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/UtilSpelTest.scala

* hide toString on helper objects

Add collection helpers to default model (e.g. sum, shuffle, distinct, sorted...)

---

designer/server/src/test/resources/designer.conf
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/DevProcessConfigCreator.scala
engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/service/DynamicMultipleParamsService.scala

Test for: Computation of dynamic component's initial parameters based on componentsUiConfig

---

common-api/src/main/scala/pl/touk/nussknacker/engine/api/MetaData.scala
scenario-api/src/test/scala/pl/touk/nussknacker/engine/marshall/ProcessMarshallerBackwardsCompatibilitySpec.scala

backwards-compatibile Metadata decoder

---

designer/client/src/common/routerUtils.ts
designer/client/src/containers/Visualization.tsx

fix decoding scenario name

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/DeploymentManagerProvider.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/testing/DeploymentManagerStub.scala
designer/server/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentObjects.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/NewProcessPreparer.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactorySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionServiceSpec.scala
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala
engine/flink/management/dev-periodic-dm/src/main/scala/pl/touk/nussknacker/engine/management/dev/periodic/DevPeriodicDeploymentManagerProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerProvider.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkStreamingDeploymentManagerProvider.scala
engine/lite/deploymentManager/src/main/scala/pl/touk/nussknacker/lite/manager/LiteDeploymentManagerProvider.scala
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/RequestResponseSlugUtils.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ToStaticObjectDefinitionTransformer.scala

metadata initailizer

---

docs/installation_configuration_guide/DesignerConfiguration.md
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2Configuration.scala

possibility to override frontend authentication strategy for oauth2

---

designer/client/src/components/toolbars/creator/ComponentIcon.tsx

Fixed preloaded svg id

---

designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx
interpreter/src/main/scala/pl/touk/nussknacker/engine/testmode/TestDataPreparer.scala

Filter empty optional parameters while testing with form

---

utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunner.scala
utils/lite-components-testkit/src/test/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunnerSpec.scala

fix typing of sources in lite test runner

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/util/LocalNussknackerWithSingleModel.scala

Fix running LocalNussknackerWithSingleModel on Windows

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/IsFollowingDeployStatusDeterminer.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicStateStatus.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerTest.scala

Fix for: After clicking deploy with PeriodicDeploymentManager, status was presented as a PROBLEM

---

designer/client/src/components/modals/GenericActionDialog.tsx

Pass empty validators list rather than undefined

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/displayedgraph/DisplayableProcess.scala
designer/restmodel/src/test/scala/pl/touk/nussknacker/restmodel/NodeDataCodecSpec.scala

DisplayableProcess legacy decoder

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/cache/CachingProcessStateDeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/inconsistency/InconsistentStateDetector.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/EmbeddedDeploymentManager.scala
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala

extract DeploymentManagerInconsistentStateHandlerMixIn

---

designer/submodules/packages/components/src/components/usages/componentView.tsx
designer/submodules/packages/components/src/components/usages/filtersPart.tsx
designer/submodules/packages/components/src/components/usages/usagesFiltersModel.ts
designer/submodules/packages/components/src/components/usages/usagesTable.tsx

The goal is to change filtering policy in usages tab from "exclusive" into "inclusive".

Change filtering policy in usages tab

---

designer/submodules/packages/components/src/common/scenarioHref.tsx
designer/submodules/packages/components/src/components/usages/breadcrumbs.tsx

Minor fixes in components

---

designer/client/cypress/e2e/fragment.cy.ts

Fragment flaky test fix - 2nd attempt

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompiler.scala
engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryProcessMixin.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractor.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/AdditionalVariableSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/ProcessDefinitionExtractorSpec.scala

pass class loader in extractor

---

version.sbt

Use new sbt syntax in vesion.sbt

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/WebResources.scala

Fix Designer startup on Windows

---

build.sbt

Ensure that we use the same version of commons-text as Flink runtime

---

docs/Changelog.md
utils/components-testkit/src/main/scala/pl/touk/nussknacker/engine/util/test/TestScenarioRunner.scala
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkProcessCompilerWithTestComponents.scala
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkTestScenarioRunner.scala
utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/LiteKafkaTestScenarioRunner.scala
utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunner.scala
utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/RequestResponseTestScenarioRunner.scala
utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/SynchronousLiteInterpreter.scala
utils/lite-components-testkit/src/test/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunnerSpec.scala

Improvement: Allow to run TestScenarioRunner in TestRuntime mode

---

designer/server/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DefinitionResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentObjects.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockDeploymentManager.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactorySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataReaderSpec.scala
docs/Changelog.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/ToStaticObjectDefinitionTransformer.scala

Faster loading of diagram editor (components panel) and component's usage panel

---

docs/MigrationGuide.md

Move migrationGuide entry from Code API changes to REST API changes

---

designer/server/src/main/scala/db/migration/V1_043__RenameSubprocessToFragmentDefinition.scala

Handle Switch, Filter, Split in Subprocess in fragment migration

---

designer/server/src/main/scala/db/migration/V1_043__RenameSubprocessToFragmentDefinition.scala

Fix missing additionalBranches migration

---

.github/workflows/pr.yml
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerKafkaTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala

K8s test disable

---

.github/workflows/pr.yml

K8s tests flaky tests fix attempt: selfhosted

---

designer/client/webpack.config.ts

unhide sourcemaps

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DeploymentComment.scala

Simplify msg creation in CommentValidationError

---

designer/client/src/components/graph/node-modal/editors/expression/BoolEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/Cron/CronEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/DateTimeEditor/DateEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/DateTimeEditor/DateTimeEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/DateTimeEditor/TimeEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/DualParameterEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/Duration/DurationEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/Duration/PeriodEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/Editor.ts
designer/client/src/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/JsonEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/SqlEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/StringEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/TextareaEditor.tsx

fixed switchable editor hints

---

designer/client/cypress/e2e/components.cy.ts
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/processdetails.scala
designer/restmodel/src/test/scala/pl/touk/nussknacker/restmodel/ProcessDetailsCodecSpec.scala

Handle isFragment / isSubprocess in Decoder / Encoder

---

designer/client/cypress/e2e/components.cy.ts
designer/submodules/packages/components/src/components/componentTable.tsx

- fix issue with components tab documentation links

fix issue with components tab documentation links

---

designer/client/src/actions/notificationActions.tsx
designer/client/src/components/notifications/notifications.styl
designer/client/src/containers/Notifications.tsx

notification closing - fix attempt

---

designer/server/src/main/resources/defaultDesignerConfig.conf
designer/server/src/main/scala/pl/touk/nussknacker/ui/processreport/ProcessCounter.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/processreport/ProcessCounterTest.scala
docs/Changelog.md
docs/MigrationGuide.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFragmentInputDefinitionSource.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/StreamExecutionEnvPreparer.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkStubbedRunner.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFragmentInputDefinitionSourceSpec.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/TestWithTestDataSpec.scala
engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/RequestResponseTestWithParametersTest.scala
engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/ScenarioInterpreterFactory.scala
engine/lite/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/InterpreterTestRunnerTest.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompilationResult.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/PartSubGraphCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/StubbedFragmentInputTestSource.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/node.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/component/NodeComponentInfoExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/FragmentComponentDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/test/ModelDataTestInfoProvider.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/test/ModelDataTestInfoProviderSpec.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/api/PartReference.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/MetaDataExtractor.scala

Add ad hoc testing support to fragments

---

designer/client/src/actions/actionTypes.ts
designer/client/src/actions/nk/closeModals.ts
designer/client/src/actions/nk/genericAction.ts
designer/client/src/actions/nk/index.ts
designer/client/src/actions/nk/nodeDetails.ts
designer/client/src/actions/nk/ui/uiActions.ts
designer/client/src/actions/reduxTypes.ts
designer/client/src/components/graph/node-modal/NodeAdditionalInfoBox.tsx
designer/client/src/components/graph/node-modal/NodeDetailsContent/selectors.tsx
designer/client/src/components/graph/node-modal/NodeTypeDetailsContent.tsx
designer/client/src/components/graph/node-modal/Variable.tsx
designer/client/src/components/graph/node-modal/node/FragmentContent.tsx
designer/client/src/reducers/nodeDetailsState.ts

fixed test results display for fragment nodes
minor fixes

Fragment node validation fixed

---

designer/client/cypress/e2e/connectionError.cy.ts

- fix connection error flaky tests by changing the tick time

fix connection error flaky tests

---

designer/client/package-lock.json
designer/client/package.json
designer/client/src/components/Process/ProcessStateIcon.tsx
designer/client/src/overrides.d.ts

NU-976 remove dependency to Popover from react-bootstrap

---

designer/client/src/components/graph/node-modal/tests/TestResults.tsx
designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx
engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/ScenarioInterpreterFactory.scala
engine/lite/runtime/src/test/scala/pl/touk/nussknacker/engine/lite/InterpreterTestRunnerTest.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala

* Do not clear test parameters on scenario change
* Mark node as entered despite of error

Fixes to fragment testing 

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/BaseDeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/cache/CachingProcessStateDeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/testing/DeploymentManagerStub.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockDeploymentManager.scala
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/DeploymentManagerStub.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala
engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/EmbeddedDeploymentManager.scala
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala

DeploymentManager: ability to cancel specific deployment for scenario

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockDeploymentManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkSlotsChecker.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkSlotsCheckerTest.scala

Deploy stop all jobs instead of one

---

designer/server/src/main/scala/db/migration/V1_043__RenameSubprocessToFragmentDefinition.scala
designer/server/src/main/scala/db/migration/V1_046__RenameSubprocessToFragmentDefinition.scala
designer/server/src/main/scala/db/migration/hsql/V1_046__RenameSubprocessToFragment.scala
designer/server/src/main/scala/db/migration/postgres/V1_046__RenameSubprocessToFragment.scala
designer/server/src/test/scala/db/migration/V1_046__RenameSubprocessToFragmentDefinitionSpec.scala
docs/Changelog.md

Fix migration by adding missing field in SubprocessInput migration

---

designer/server/src/main/scala/db/migration/V1_043__RenameSubprocessToFragmentDefinition.scala
designer/server/src/main/scala/db/migration/V1_046__RenameSubprocessToFragmentDefinition.scala
designer/server/src/main/scala/db/migration/hsql/V1_046__RenameSubprocessToFragment.scala
designer/server/src/main/scala/db/migration/postgres/V1_046__RenameSubprocessToFragment.scala
designer/server/src/test/scala/db/migration/V1_046__RenameSubprocessToFragmentDefinitionSpec.scala
docs/Changelog.md

Fix migration in 1.11

---

README.md

Sample helpers project mentioned in readme

---

.github/workflows/pr.yml

update comment for snapshots pr

---

build.sbt
docs/Changelog.md
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/PeriodicSourceFactory.scala
engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/TypedJsonTimestampFieldAssigner.scala
engine/flink/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/UniversalTimestampFieldAssigner.scala
utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/TimestampUtils.scala

Log invalid timestamp field type

---

.github/pull_request_template.md

Added the checklist to PR tempalate

---

.github/workflows/pr.yml

K8 tests disabled

---

.github/pull_request_template.md

Checklist fix

---

designer/client/src/components/graph/Graph.tsx

On touch devices:
- A single click will open node details
- The long press will select the node
- Double click has no event
On the Desktop device, it works the same:
- A single click will select the node
- The long press has no event
- Double click will open node details

NU-1026 change graph node events on tablets

---

designer/client/package-lock.json
designer/client/package.json
designer/client/src/containers/Visualization.tsx
designer/client/src/helpers/detectDevice.ts

- Fix graph node adding on touch devices (like tablets). It was an issue with drag-and-drop elements from a toolbar to the graph board.
- 
- [x ] Added related issue id at the beginning of the title in \[brackets\] (could be GH issue or NU jira issue)
- [x ] Code is cleaned from temporal changes and commented lines 
- [x ] Code formatting checked
- [x ] Verify that PR will be squashed during the merge

[NU-1029] Fix graph node adding on touch devices

---

designer/client/package-lock.json
designer/client/package.json
designer/client/src/components/graph/Graph.tsx
designer/client/src/components/graph/arrowMarker.ts

arrows initially rendered on ios
updated jointjs to 3.7

[NU-1025] arrows on ios

---

designer/client/src/components/versionInfo.tsx

hiding version info on touchscreens fixed

[NU-1028] toolbar collapse fix

---

designer/client/src/helpers/detectDevice.ts

fixed touch event detection [ff]

---

designer/client/package-lock.json
designer/client/package.json

[NU-1051] fixed events on windows buttons

---

designer/client/src/components/graph/GraphContext.tsx
designer/client/src/components/sidePanels/SidePanel.tsx
designer/client/src/components/toolbars/edit/buttons/LayoutButton.tsx
designer/client/src/components/toolbars/process/buttons/PDFButton.tsx
designer/client/src/components/toolbars/view/buttons/ZoomInButton.tsx
designer/client/src/components/toolbars/view/buttons/ZoomOutButton.tsx

- Fix the issue with an unexpected error on ad hoc tests Apply button clicks
- [ x ] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [ x ] Code is cleaned from temporary changes and commented out lines
- [ x ] Code formatting checked

[NU-1072] fix ad hoc tests

---

docs/Changelog.md
security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationConfiguration.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationProvider.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactory.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResourcesSpec.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oidc/OidcAuthenticationResourcesSpec.scala

[NU-1078] OIDC: Support for overrideFrontendAuthenticationStrategy configuration parameter

---

designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx

Fix calling test capabilities on scenario rename

---

designer/client/cypress/e2e/processSelection.cy.ts

disable flaky test

---

designer/processReports/src/it/scala/pl/touk/nussknacker/processCounts/influxdb/InfluxCountsReporterSpec.scala
designer/processReports/src/main/scala/pl/touk/nussknacker/processCounts/influxdb/InfluxCountsReporter.scala
designer/processReports/src/main/scala/pl/touk/nussknacker/processCounts/influxdb/InfluxGenerator.scala
designer/processReports/src/main/scala/pl/touk/nussknacker/processCounts/influxdb/SimpleInfluxClient.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala

This synchronizes changes made in fix release 1.11.3 with staging

Add closing resources fixes from release 1.11

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppApiSpec.scala

[NU-981] non deterministic test fix in AppApiSpec

---

utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkProcessCompilerWithTestComponents.scala

Improvement: Flink Components Teskit allow passing customStreamTransformer as extra components

---

.github/pull_request_template.md

[NU-1093] we don't need the point about formatting check anymore

---

.editorconfig
.husky/pre-commit
designer/formatStagedFrontendFiles.sh
formatStagedBackendFiles.sh

1. Allows pre-commit hook to work when `SBT_OPTS` environment variable is set (e.g. to limit sbt's memory usage).
2. Adds basic .editorconfig, to ensure that files have trailing newlines (will Idea pick it up and always add missing newline on save)

Formatting fixes

---

version.sbt

[NU-1104] version changed: Nu 1.13.0-SNAPSHOT

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppApiSpec.scala

[NU-981] AppApiSpec fix

---

designer/client/package-lock.json
designer/client/package.json
designer/client/webpack.config.ts

fallback to BACKEND_DOMAIN if submodules not started locally - displays missing components in dev [NU-765]
[NU-765]: https://touk-jira.atlassian.net/browse/NU-765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NU-765] fixed submodules dev proxy setup

---

designer/client/cypress/e2e/fragment.cy.ts
designer/client/cypress/e2e/processSelection.cy.ts
designer/client/package-lock.json
designer/client/package.json
designer/client/src/components/graph/node-modal/editors/expression/CustomAceEditorCompleter.tsx
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggest.tsx
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggester.ts
designer/client/src/components/graph/svg-export/prepareSvg.ts
designer/client/src/containers/DynamicTab.tsx
designer/client/src/containers/ExternalLib/tools/createScript.ts
designer/client/src/containers/ExternalLib/tools/loadComponent.ts
designer/client/src/containers/ExternalLib/tools/splitUrl.tsx
designer/client/src/containers/ExternalLib/types.ts

resolves [NU-1092]
[NU-1092]: https://touk-jira.atlassian.net/browse/NU-1092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bulk cherrypicked fixes for 1.12

---

designer/client/src/components/graph/EspNode/element.ts
designer/client/src/components/graph/svg-export/export.styl

fixed text opacity problem in pdf export

---

designer/submodules/.env
designer/submodules/configs/webpack/common.ts
designer/submodules/configs/webpack/dev.ts
designer/submodules/configs/webpack/withModuleFederationPlugins.ts
designer/submodules/package.json
designer/submodules/packages/components/src/common/scenarioHref.tsx
designer/submodules/packages/components/webpack.config.ts

[NU-765] provide dev proxy to submodules

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessActionRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/StubDeploymentService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala

performance improvements of getting processes and processes' status

---

designer/client/src/common/ProcessUtils.ts
designer/client/src/components/graph/node-modal/AdditionalProperty.tsx
designer/client/src/components/graph/node-modal/editors/EditableEditor.tsx
designer/client/src/components/graph/node-modal/editors/Validators.ts
designer/client/src/containers/Visualization.tsx
designer/client/src/types/validation.ts

when trying to refresh or leave from scenario/fragment: added a check if the scenario/fragment was renamed when changes didn't save.

Nu 1125/add check scenario rename

---

designer/client/src/components/spinner/Spinner.tsx

NU-1085 fix loader position

---

utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/EmbeddedKafkaServer.scala

Reduce number of partitions created by EmbeddedKafkaServer

---

.github/workflows/pr.yml
.github/workflows/release.yml
build.sbt

* building docker images for linux/arm64 + linux/amd64 platforms in case of pr(preview releases)/release
* building docker image for host platform in case of publishLocal (previously amd64 was forced)

Make NU on Arm64 great once again

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
docs/Changelog.md

[NU-1140] Synchronize deployed scenario version after server restart in embedded engine

---

designer/client/src/actions/notificationActions.tsx
designer/client/src/components/notifications/Notification.tsx
designer/client/src/containers/Notifications.tsx
designer/client/src/http/HttpService.ts

fix problem alert error message

NU-1129 fix problem alert error message

---

utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/EmbeddedKafkaServer.scala

Remove temporary data after shutting down EmbeddedKafkaServer

---

docs/scenarios_authoring/Fragments.md

Reverts to previous fragment output image.

Fix image in fragment docs

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessCategoryService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ConfigProcessCategoryServiceTest.scala

[NU-1059] Proper handling of mixed legacy and new categories inside scenario types format

---

nussknacker-dist/src/universal/conf/dev-application.conf

Adding parameterisation in `dev-application.conf` for the connection to influxdb.

Parameterisation of metrics in dev-application.conf

---

build.sbt
designer/client/src/types/process.ts
designer/client/test/ProcessUtils-test.js
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala

[NU-1061] ClazzDefinition's method not exposed via REST API

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala

`HttpRemoteEnvironment` creates `HttpExt` in its constructor, which makes it bound to implicitly passed `ActorSystem`. Shutting down `ActorSystem` may cause an exception to be logged because Akka HTTP still depends on it. To prevent that we need to explicitly close its connection pool.
Currently we're using:
```scala
try {
// checkScenarioMigration(...)
} finally {
Await.ready(remoteEnv.http.shutdownAllConnectionPools(), 5.seconds)
}
```
but it's better not to depend in internal implementation.

Add close() method to HttpRemoteEnvironment

---

nussknacker-dist/src/universal/conf/dev-application.conf

Remove kafka from configExecutionOverrides for streaming-lite-k8s

---

designer/client/src/components/graph/CursorMask.ts
designer/client/src/components/graph/GlobalCursor.ts
designer/client/src/components/graph/PanZoomPlugin.ts
designer/client/src/components/graph/RangeSelectPlugin.ts

- Fix the issue with the pan on Firefox https://touk-jira.atlassian.net/browse/NU-1191
- Fix with the pan inside of the fragmentInput https://touk-jira.atlassian.net/browse/NU-1202
- Make pan smoothing  https://touk-jira.atlassian.net/browse/NU-1203
https://github.com/TouK/nussknacker/assets/9945753/ac8e95b1-2d65-4f19-af8e-ef6eb8300b59

[NU-1191][NU-1202][NU-1203] fix various issues with a diagram

---

designer/client/src/components/graph/node-modal/NodeAdditionalInfoBox.tsx

Fix NodeAdditionalInfo style

---

build.sbt
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/fragment/FragmentRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessAttachmentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/TestInfoResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/ProcessModelMigratorSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
docs/Changelog.md
docs/MigrationGuide.md
engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/FlinkKafkaDelayedSourceImplFactory.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/PeriodicProcessDeploymentsTable.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/DockerTest.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/rest/FlinkHttpClientTest.scala
engine/lite/runtime-app/src/main/scala/pl/touk/nussknacker/engine/lite/app/NuRuntimeApp.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/DefaultOAuth2ServiceFactorySpec.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/ExampleOAuth2ServiceFactorySpec.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResourcesSpec.scala
security/src/test/scala/pl/touk/nussknacker/ui/security/oidc/OidcDiscoveryTest.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/serialization/AzureAvroSerializerFactory.scala

Update Scala 2.13 to 2.13.12

---

.github/workflows/pr.yml

Fix SCALA_VERSION in pr.yml

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/suggester/ExpressionSuggesterBenchmarkSetup.scala
designer/client/src/actions/nk/genericAction.ts
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggest.tsx
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggester.ts
designer/client/src/components/modals/GenericActionDialog.tsx
designer/client/src/components/toolbars/test/buttons/TestWithFormButton.tsx
designer/client/src/http/HttpService.ts
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/suggester/ExpressionSuggester.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/ParametersValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ExpressionSuggesterSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NodeResourcesSpec.scala
docs/MigrationGuide.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/GenericNodeTransformationValidator.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/testmode/TestDataPreparer.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/variables/GlobalVariablesPreparer.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/variables/MetaVariables.scala

[NU-1290] Parameters API (suggester+validate) refactor: less data passed in request

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/interpreter/InterpreterSetup.scala
build.sbt
components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidatorSpec.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
docs/Changelog.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFragmentInputDefinitionSource.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/TestFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/VerificationFlinkProcessCompiler.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkTestMain.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkVerificationMain.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompilerTest.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFragmentInputDefinitionSourceSpec.scala
engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/RequestResponseTestWithParametersTest.scala
engine/lite/runtime/src/main/scala/pl/touk/nussknacker/engine/lite/ScenarioInterpreterFactory.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/FragmentComponentDefinitionExtractor.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/CustomNodeValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelConversionServiceOverrideSpec.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/graph/node.scala
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkProcessCompilerWithTestComponents.scala

ValidationExpressionParameterValidator

---

build.sbt

Revert Logback to 1.2

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala

Add todo comment to remind to revert fetching status in the future

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/NodeDependency.scala

default None for hintText in case class Parameter

---

.github/workflows/pr.yml
designer/client/cypress.config.ts

upload results only on failure

enable video in cypress

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessingTypeDeploymentService.scala
engine/flink/management/periodic/src/main/resources/db/batch_periodic/migration/common/V1_109__add_action_id_to_periodic_processes.sql
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/PeriodicProcessesRepository.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/PeriodicProcessesTable.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/PeriodicProcess.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessGen.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessServiceIntegrationTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessServiceTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/db/InMemPeriodicProcessesRepository.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/deployment/DeploymentData.scala

Set Action to EXECUTION_FINISHED when job is done

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/UserApiEndpoints.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md

[NU-1260] Add documentation for User OpenApi

---

designer/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/ProcessChangeEvent.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala

Adds OnActionExecutionFinished event to ProcessChangeEvents

---

engine/flink/components/base/src/main/java/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregateHelper.java
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/UnionTransformer.scala

Build fix for scala 2.12

---

designer/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/ProcessChangeEvent.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala

Adds actionId field to OnActionExecutionFinished event

---

docs/scenarios_authoring/Spel.md

Spel conditional dot - docs update

---

components/sql/src/test/scala/pl/touk/nussknacker/sql/service/DatabaseLookupLiteRuntimeTest.scala
components/sql/src/test/scala/pl/touk/nussknacker/sql/service/IgniteEnrichmentLiteRuntimeTest.scala
docs/MigrationGuide.md
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalAvroSchemaFunctionalTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalJsonFunctionalTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/UniversalCrossSourceLiteTest.scala
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/UniversalSourceAvroSchemaLiteTest.scala
utils/components-testkit/src/main/scala/pl/touk/nussknacker/engine/util/test/TestScenarioRunner.scala
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkTestScenarioRunner.scala

Nu 1338 testkit simper result type

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DefinitionResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/ComponentDefinitionPreparerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/model/ModelDefinitionWithComponentIds.scala

[NU-1330] REST API - validators removal from scenario properties config

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/TestAdditionalUIConfigProvider.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/UIProcessObjectsFactorySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala

[NU-1330] REST API - Parameter's validators removed

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NotificationApiEndpoints.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md

[NU-1228] Add documentaiton for Notification OpenApi 

---

version.sbt

Bumped version to 1.14.0-SNAPSHOT

---

components/openapi/src/test/scala/pl/touk/nussknacker/openapi/OpenAPIsConfigTest.scala
docs/integration/DataTypingAndSchemasHandling.md
docs/integration/OpenAPI.md
docs/integration/RequestResponse.mdx

OpenAPI enricher: Security configuration documentation clarification.

---

build.sbt
docs/Changelog.md
engine/flink/management/src/it/resources/docker/Dockerfile

Update Flink to 1.16.3

---

utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/confluent/serialization/ConfluentKafkaAvroSerializer.scala

Obsolete ConfluentAvroSerializerFactory removal

---

docs/Changelog.md

Move misplaced changelog entry

---

designer/client/src/components/graph/node-modal/editors/expression/SwitchButton.tsx

fixed editor switch icon

---

designer/client/src/components/AddProcessForm.tsx
designer/client/src/components/table/AddProcessButton.tsx

[NU-1384] fixed create window width

---

docs/Changelog.md
engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/CollectTransformerTest.scala
engine/lite/components/request-response/src/main/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/CollectTransformer.scala
engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreterSpec.scala

[NU-1383] Collect component clears context variables - 1.13 bugfix

---

docs/Changelog.md
engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/CollectTransformerTest.scala
engine/lite/components/request-response/src/main/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/CollectTransformer.scala
engine/lite/request-response/runtime/src/test/scala/pl/touk/nussknacker/engine/requestresponse/RequestResponseInterpreterSpec.scala

[NU-1383] Collect component clears context variables

---

designer/client/src/components/graph/node-modal/fragment-input-definition/settings/variants/fields/ValidationFields.tsx
designer/client/src/components/graph/node-modal/fragment-input-definition/settings/variants/fields/validation.tsx

[NU-1399] provide value type to suggester

---

designer/client/src/http/HttpService.ts

[NU-1398] removed unnecessary colon character

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/NumberTypesPromotionStrategy.scala
docs/Changelog.md
docs/scenarios_authoring/AggregatesInTimeWindows.md
engine/flink/components/base/src/main/java/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregateHelper.java
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/aggregates.scala
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/sampleTransformers.scala
engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregatesSpec.scala
engine/flink/components/base/src/test/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/TransformersTest.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/helpers/KafkaAvroSpecMixin.scala
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/numeric.scala
utils/math-utils/src/main/scala/pl/touk/nussknacker/engine/util/MathUtils.scala

Added AverageAggregator and CountWhenAggregator

Add AverageAggregator and CountWhenAggregator (#5313)

---

docs/Changelog.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/propertyAccessors.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

[NU-1372] Block accessing methods by field names in record

---

engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/KafkaAvroNamespacedSpec.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/KafkaAvroPayloadIntegrationSpec.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/KafkaJsonPayloadIntegrationSpec.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/helpers/KafkaAvroSpecMixin.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/sink/flink/SinkValueEditorWithAvroPayloadIntegrationTest.scala

KafkaAvroPayloadIntegrationSpec flaky test fix - 2nd attempt

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/NodeDependency.scala
components/openapi/src/main/scala/pl/touk/nussknacker/openapi/extractor/ParametersExtractor.scala
designer/client/src/components/graph/node-modal/FieldLabel.tsx
designer/client/src/components/graph/node-modal/NodeTypeDetailsContent.tsx
designer/client/src/components/modals/GenericActionDialog.tsx
designer/client/src/types/component.ts
designer/client/src/types/definition.ts
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/ValidationResults.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/DefinitionsService.scala
designer/server/src/test/resources/designer.conf
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NodesApiSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionsServiceSpec.scala
docs/Changelog.md
docs/MigrationGuide.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/ParameterExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/StandardParameterEnrichment.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/NodeDataValidatorSpec.scala

[NU-1403] Parameter's label moved into domain Parameter object

---

build.sbt

Set root project name in sbt

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/ModelDefinitionEnricher.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/UIComponentGroupsPreparerSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/model/ModelDefinition.scala

Fragments sources fix

---

designer/client/src/actions/nk/calculateProcessAfterChange.ts
designer/client/src/actions/nk/fetchVisualizationData.ts
designer/client/src/components/graph/node-modal/nodeUtils.tsx
designer/client/src/reducers/selectors/graph.ts
designer/client/src/types/node.ts

- remove scenarioGraph.properties.isFragment and switch it to scenario.isFragment

[NU-1409] remove properties.isFragment

---

build.sbt

Propagate fastutil exclusion to generated POM

---

common-api/src/main/scala/pl/touk/nussknacker/engine/util/Implicits.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/component/ComponentsUsageHelper.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/ModelDefinitionEnricher.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/ProcessTestData.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/ComponentsUsageHelperTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/EdgeTypesPreparerTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/component/UIComponentGroupsPreparerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/DefinitionsServiceSpec.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompilerDataFactory.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFragmentSourceDefinitionPreparer.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFragmentSourceDefinitionPreparerSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/fragment/FragmentComponentDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/fragment/FragmentParametersCompleteDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/fragment/FragmentParametersWithoutValidatorsDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/test/ModelDataTestInfoProvider.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/testing/ModelDefinitionBuilder.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala

see comments in https://github.com/TouK/nussknacker/pull/5356

Refactors leftover from PR 5356

---

designer/client/src/components/graph/node-modal/OutputParametersList.tsx

[NU-1412] fix error on fragment node open when there is no component

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/NumberTypesPromotionStrategy.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/numeric.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/BaseSpelSpec.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/CollectionUtilsSpec.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/NumericUtilsSpec.scala

[Nu-1407] Improve validation in numeric toNumber helper method

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/generics/TypingFunction.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
docs/Changelog.md
engine/flink/components/kafka/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkKafkaComponentProvider.scala
engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/KafkaAvroTestProcessConfigCreator.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/helpers/KafkaAvroSpecMixin.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/DelayedUniversalKafkaSourceIntegrationMixinSpec.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/TopicSelectionStrategySpec.scala
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalAvroSchemaFunctionalTest.scala
engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaComponentProvider.scala
extensions-api/src/main/java/pl/touk/nussknacker/engine/javaapi/process/ClassExtractionSettings.java
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/conversion/ProcessConfigCreatorMapping.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassExtractionSettings.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/ClassMemberPredicate.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/TypingFunctionForClassMember.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/clazz/ClassDefinition.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/clazz/ClassDefinitionExtractor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/clazz/MethodDefinition.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpression.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/typer/MethodReferenceTyper.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/clazz/ClassDefinitionDiscoverySpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/definition/clazz/MethodDefinitionSpec.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/UniversalKafkaSourceFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/delayed/DelayedUniversalKafkaSourceFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/typed/AvroSchemaTypeDefinitionExtractor.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/typed/SpelExpressionSchemedSpec.scala

Generic types (Records, Lists and other collections) using generic parameters in their method's return type

---

docs/Changelog.md
docs/MigrationGuide.md
extensions-api/src/main/scala/pl/touk/nussknacker/engine/modelconfig/ModelConfigLoader.scala
interpreter/src/test/resources/defaultModelConfig.conf
interpreter/src/test/scala/pl/touk/nussknacker/engine/DefaultModelConfigLoaderTest.scala

Remove system properties from merged model config

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/UIProcessValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompilationResult.scala

Also fixes a broken test and adds a variable for clarity

Fix duplicated global errors

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala

Post merge compilation fix

---

designer/client/src/components/MenuBar/TabElement.tsx

- open url in header in a new tab

NU-1338 open url in header in a new tab

---

engine/lite/components/request-response-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/requestresponse/LiteRequestResponseFunctionalTest.scala

Add test for nested json schema 

---

common-api/src/main/scala/pl/touk/nussknacker/engine/util/Implicits.scala
designer/client/src/http/HttpService.ts
designer/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/ProcessChangeEvent.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/services/AppApiHttpService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
docs/MigrationGuide.md

Remove unused endpoint: update category

---

build.sbt

Build cleanup:
* removal of `assembly / test := {}` - it's default since sbt-assembly 1.0
* removal of unused merge rules
* proper merging of Netty version information files
* resolution of commons-logging/spring-jcl conflict by removal of commons-logging
I verified that all projects that had their dependencies changed have a dependency on spring-jcl.
I thought about using jcl-over-slf4j, but it performs the same function as spring-jcl, and we already have spring-core in almost all of our projects.

Clean sbt-assembly rules, replace commons-logging with spring-jcl

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/WithExplicitTypesToExtract.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/process/Source.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/TypeConversionHandler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/clazz/ClassDefinitionDiscovery.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/internal/DefaultSpelConversionsProvider.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
utils/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/KafkaSourceFactory.scala
utils/lite-components-testkit/src/main/scala/pl/touk/nussknacker/engine/lite/util/test/LiteTestScenarioRunner.scala

Minor improvements

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/supertype/CommonSupertypeFinder.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultSpec.scala
docs/Changelog.md
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

Equals used with lists with different types checking

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/marshall/CanonicalProcessConverter.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/UIProcessValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/CompilationResult.scala
interpreter/src/test/scala/pl/touk/nussknacker/engine/compile/ProcessValidatorSpec.scala

Fixes bugs introduced previously while changing global error mechanism

Fix not merging global errors and ignoring non-matching

---

docs/MigrationGuide.md

Add migration guide note for #4698

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala

Allow only one PeriodicDeploymentManager instances per processingType

---

docs/Changelog.md

[NU-1379] Add missing changelog entry to the ScenarioActivityAPI security enhancements

---

designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/scenariodetails/ScenarioParameters.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ScenarioParametersEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/factory/LocalProcessingTypeDataStateFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/ProcessService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/AllDeployedScenarioService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReload.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersWithEngineSetupErrors.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ValueWithRestriction.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/services/ScenarioParametersHttpService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ScenarioParametersApiSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/component/DefaultComponentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/ProcessStateDefinitionServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataProviderTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersServiceTest.scala
docs-internal/api/nu-designer-openapi.yaml
extensions-api/src/main/scala/pl/touk/nussknacker/engine/deployment/EngineSetupName.scala

[NU-1061] engineSetupErrors in the separated field in response

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/cache/CachingProcessStateDeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/testing/DeploymentManagerStub.scala
docs/Changelog.md
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/MockableDeploymentManagerProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/DeploymentManagerStub.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerTest.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala

Scenario status caching more often

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/cache/CachingProcessStateDeploymentManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/DeploymentManagerStub.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala

… it already was used only internally in FlinkDeploymentManager

PostprocessingProcessStatus removal from DM API 

---

designer/client/package-lock.json
designer/client/package.json
designer/client/src/actions/nk/nodeDetails.ts
designer/client/src/api.ts
designer/client/src/common/SystemUtils.ts
designer/client/src/components/graph/node-modal/NodeAdditionalInfoBox.tsx
designer/client/src/http/HttpService.ts
designer/client/src/reducers/nodeDetailsState.ts

minor refactor
update of axios

NU-1401 cleanup unnecessary errors in console

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersServiceTest.scala

[Nu 1068] processing mode category with invalid engine setups only detection

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/factory/LocalProcessingTypeDataStateFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/factory/ProcessingTypeDataReaderBasedProcessingTypeDataStateFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/factory/ProcessingTypeDataStateFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/MockDeploymentManager.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/helpers/NuResourcesTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/ConfigurationTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReaderSpec.scala
docs/MigrationGuide.md
engine/flink/management/dev-model/src/test/scala/pl/touk/nussknacker/engine/process/SampleComponentProviderTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingDeploymentManagerProviderHelper.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingDeploymentManagerSpec.scala
engine/lite/runtime-app/src/main/scala/pl/touk/nussknacker/engine/lite/app/RunnableScenarioInterpreterFactory.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeConfig.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
utils/utils-internal/src/main/scala/pl/touk/nussknacker/engine/util/loader/ModelClassLoader.scala
utils/utils-internal/src/test/scala/pl/touk/nussknacker/engine/util/loader/ModelClassLoaderSpec.scala

[NU-1068] ModelClassLoader - ability to specify working directory for the tests purpose

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/HttpFlinkClient.scala

Backport 1.13-esp: better logging for scenario state fetching  

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/component/AdditionalUIConfigProvider.scala

Update AdditionalUIConfigProvider comments

---

build.sbt
engine/flink/scala-utils/src/main/java/pl/touk/nussknacker/engine/flink/api/typeinfo/caseclass/ScalaCaseClassSerializerSnapshot.java
engine/flink/scala-utils/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinfo/caseclass/ScalaCaseClassSerializer.scala
engine/flink/scala-utils/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinfo/option/OptionSerializer.scala
engine/flink/test-utils/src/main/resources/META-INF/services/org.apache.flink.metrics.reporter.MetricReporterFactory
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/process/functional/TestReporter.scala
engine/flink/tests/src/test/scala/pl/touk/nussknacker/defaultmodel/SerializationTest.scala

[NU-1288] flink 1.17

---

designer/client/src/components/AddProcessForm.tsx

[NU-1063] update categories link

---

docs/Changelog.md
engine/flink/management/src/it/resources/docker/Dockerfile

[NU-1288] missing changelog entry

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersServiceTest.scala
engine/flink/management/dev-model/src/test/scala/pl/touk/nussknacker/engine/process/SampleComponentProviderTest.scala
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/FlinkMiniClusterHolder.scala
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/MiniClusterExecutionEnvironment.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/ModelData.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/util/loader/ProcessConfigCreatorLoader.scala
utils/utils-internal/src/main/scala/pl/touk/nussknacker/engine/util/loader/LoadClassFromClassLoader.scala

Tests improvements: FlinkTestScenarioRunner showing job failure details + work around for Idea classloader issue

---

engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/DelayedUniversalKafkaSourceAvroPayloadIntegrationSpec.scala
utils/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/delayed/DelayedKafkaSourceFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/KafkaUniversalComponentTransformer.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/sink/UniversalKafkaSinkFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/UniversalKafkaSourceFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/source/delayed/DelayedUniversalKafkaSourceFactory.scala

Add fixed values parameter editor for timestampField in kafka source

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/BaseDeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/cache/CachingProcessStateDeploymentManager.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/testing/DeploymentManagerStub.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/CustomActionResponse.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/InvalidDeploymentManagerStub.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/mock/MockDeploymentManager.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/mock/StubDeploymentService.scala
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/MockableDeploymentManagerProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicCustomActionsProviderFactory.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/deployment/CustomActionDefinition.scala

* `CustomAction`, `CustomActionParameter` and `CustomActionResult` moved from `extension-api` to `deployment-manager-api` module
* `CustomActionResult.req` was removed
* `CustomAction` was renamed to `CustomActionDefinition`

[NU-1466] CustomAction refactor

---

interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compiledgraph/service.scala

ServiceRef.parameters removal

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/Params.scala
components/sql/src/main/scala/pl/touk/nussknacker/sql/service/DatabaseQueryEnricher.scala

ref: https://github.com/TouK/nussknacker/pull/5632/files#r1505646581

[NU-1490] DB components should treat missing `Cache TTL` in the same way they treat `null` value of the `Cache TTL`

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionParseError.scala

KeyWithLabelExpressionParsingError fieldname nodeid fix

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/Params.scala
components/sql/src/main/scala/pl/touk/nussknacker/sql/service/DatabaseQueryEnricher.scala
docs/MigrationGuide.md

Remove unnecessary Optional wrapping in Params class

---

.github/workflows/pr.yml
.k3d/single-cluster.yml
build.sbt
docs/Changelog.md
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala

[NU-1069] K3s bumped 1.26.5 -> 1.29.1

---

docs/Changelog.md
docs/MigrationGuide.md
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/DeploymentActor.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/JarManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/PeriodicProcessesRepository.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/db/PeriodicProcessesTable.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/flink/FlinkJarManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/DeploymentWithJarData.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/PeriodicProcess.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/PeriodicProcessDeployment.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/SchedulesState.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/service/AdditionalDeploymentDataProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/service/PeriodicProcessListener.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/service/ProcessConfigEnricher.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/DeploymentActorTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/JarManagerStub.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/JarManagerTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessDeploymentGen.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessGen.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessServiceTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/db/InMemPeriodicProcessesRepository.scala

cherrypick: fetching/parsing batch periodic json only when needed (stop parsing during status check)

---

engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/generic/FlinkKafkaDelayedSourceImplFactory.scala
utils/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/delayed/DelayedKafkaSourceFactory.scala

DelayedKafkaSourceFactory delay parameters bug fix

---

designer/client/src/actions/nk/displayTestResults.ts
designer/client/src/http/HttpService.ts

[Nu 1509] generated doesn t work

---

.github/workflows/pr.yml
CONTRIBUTING.md
docs/Changelog.md
docs/integration/KafkaIntegration.md
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/AzureSchemaRegistryKafkaAvroTest.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/AzureSchemaRegistryClientFactory.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/SchemaNameTopicMatchStrategy.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/AzureSchemaRegistryClientIntegrationTest.scala
utils/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/azure/SchemaNameTopicMatchStrategyTest.scala

https://github.com/TouK/nussknacker/pull/5657

[5615] Fix for eventhub naming convention with Azure Schema Registry

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersDeterminer.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ScenarioParametersService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReaderSpec.scala
docs/Changelog.md
docs/MigrationGuide.md
docs/installation_configuration_guide/DeploymentManagerConfiguration.md
extensions-api/src/main/scala/pl/touk/nussknacker/engine/ProcessingTypeConfig.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/deployment/EngineSetupName.scala

- corrected status codes during creation of scenario
- ability to specify engine setup name in the deployment configuration
- Changelog/MG notice about steps needed to perform after helm charg upgrade

Small fixes around processing mode / engine setup handling

---

designer/client/src/actions/nk/displayTestResults.ts
designer/client/src/components/graph/Graph.tsx
designer/client/src/components/toolbarComponents/toolbarWrapper/ToolbarWrapper.tsx
designer/client/src/components/toolbars/test/buttons/FromFileButton.tsx
designer/client/src/components/toolbars/view/buttons/ResetViewButton.tsx

[NU-1358] fit graph on reset button

---

docs/Changelog.md

1.13.2 update for 1.14

---

build.sbt
designer/server/src/test/resources/config/oauth2/users.conf
designer/server/src/test/scala/pl/touk/nussknacker/test/base/db/DbTesting.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/mock/WithWireMockServer.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/UserApiHttpServiceOAuth2Spec.scala
docs/Changelog.md
security/src/main/scala/pl/touk/nussknacker/ui/security/oauth2/OAuth2AuthenticationResources.scala

[NU-1516] Fix for OAuth2 authentication stop to work

---

designer/client/src/components/graph/node-modal/editors/expression/Table/errorHighlights.tsx
designer/client/src/types/validation.ts

fixed tableEditor cell error display

---

designer/client/src/actions/nk/editNode.ts
designer/client/src/common/ProcessUtils.ts
designer/client/src/components/graph/node-modal/DescriptionField.tsx
designer/client/src/components/graph/node-modal/IdField.tsx
designer/client/src/components/graph/node-modal/MapVariable.tsx
designer/client/src/components/graph/node-modal/NodeCommonDetailsDefinition.tsx
designer/client/src/components/graph/node-modal/NodeField.tsx
designer/client/src/components/graph/node-modal/Variable.tsx
designer/client/src/components/graph/node-modal/editors/Validators.ts
designer/client/src/components/graph/node-modal/editors/map/Map.tsx
designer/client/src/components/graph/node-modal/node/NodeDetails.tsx
designer/client/src/types/validation.ts

[NU-1124] node rename error

---

designer/client/src/components/AddProcessDialog.tsx
designer/client/src/components/AddProcessForm.tsx
designer/client/src/components/useProcessFormDataOptions.test.ts
designer/client/src/components/useProcessFormDataOptions.ts

[NU-1551] display processing mode batch

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/AppApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/BaseHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ComponentApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NotificationApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NuDesignerExposedApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ScenarioActivityApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ScenarioParametersApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/UserApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/AppApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/NodesApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/NotificationApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/ScenarioActivityApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/ScenarioParametersApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/UserApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/test/ScenarioTestService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/NodeValidator.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/ParametersValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NuDesignerApiAvailableToExposeYamlSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/BaseFlowTest.scala

[NU-1443] Tapir services: packages refactor

---

docs/Changelog.md
docs/MigrationGuide.md

provide info about processing mode and new toolbars to the changelog

---

docs/scenarios_authoring/Spel.md

The main reason for this change is to rebalance the structure and contents of the SpEL cheatsheet. Currently, the 3rd level section on handling date & time is:
- very big
- almost at the beginning of the document
With the current structure one can have an impression that handling date & time is the essence of SpEL, which of course it is not; not to mention the fact that the way we handle date & time has nothing to do with SpEL. 
The change in a nutshell:
- pushed the section on date & time to the bottom of the document
- The date & time section is on level 1 now, which makes the structure of the document more balanced.
The checklist below does not apply.

changes done

---

README.md

Removed DEFAULT_SCENARIO_TYPE from oneliner in readme

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
designer/client/src/http/HttpService.ts
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/CustomActionRequest.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/NuDesignerError.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/NodesApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceImpl.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/services/ManagementApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/CustomActionValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementApiHttpServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/CustomActionValidatorTest.scala
docs-internal/api/nu-designer-openapi.yaml
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/MockableDeploymentManagerProvider.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/deployment/CustomActionDefinition.scala

fixes for custom_action_params

Add custom action validators fix tapir

---

designer/submodules/packages/components/src/components/filterRules.tsx

[Nu-5807] Change filter rules for categories in components table

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/FragmentParameterValidator.scala

Fix validation of initial value - ValueInputWithDictEditor

---

interpreter/src/main/scala/pl/touk/nussknacker/engine/definition/fragment/FragmentParametersDefinitionExtractor.scala

Fix wrong language for initial value for ValueInputWithDictEditor

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/PrettyValidationErrors.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/FragmentParameterValidator.scala

Validate blank `dictId` in fragment definition

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/integration/DictsFlowTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/service/ServiceWithDictParameterEditor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/FragmentParameterValidator.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/dict/ProcessDictSubstitutor.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/language/dictWithLabel/DictKeyWithLabelExpressionParser.scala

Fixed empty value handling in DictParameterEditor optional parameters

---

.github/workflows/pr.yml
README.md
build.sbt
engine/flink/test-utils/src/main/resources/docker/Dockerfile
project/plugins.sbt

Coverage removal

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/TapirCodecs.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/StatisticsApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsDeterminer.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/SettingsResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpServiceSecuritySpec.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md

[NU-1524] Add endpoint to provide statistics URLs

---

.github/workflows/pr.yml
components-api/src/main/scala/pl/touk/nussknacker/engine/api/generics/ExpressionParseError.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/NodesApiEndpoints.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NuDesignerApiAvailableToExposeYamlSpec.scala
engine/common/components-tests/src/test/scala/pl/touk/nussknacker/engine/common/components/DecisionTableSpec.scala
interpreter/src/main/scala/pl/touk/nussknacker/engine/language/tabularDataDefinition/TabularDataDefinitionParser.scala

[NU-1596] Scala 212 different openapi fix 2

---

build.sbt
designer/server/src/main/resources/db/migration/hsql/V1_049__CreateFingerprintTable.sql
designer/server/src/main/resources/db/migration/postgres/V1_049__CreateFingerprintTable.sql
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/StatisticsApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/entity/FingerprintEntityFactory.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/FileName.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/Fingerprint.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/FingerprintService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsDeterminer.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/repository/FingerprintRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/base/db/DbTesting.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/FingerprintServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsDeterminerTest.scala

[NU-1574] Save fingerprint in DB

---

defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/migrations/DecisionTableParameterNamesMigration.scala
defaultModel/src/test/scala/pl/touk/nussknacker/defaultModel/migrations/DecisionTableParameterNamesMigrationSpec.scala
docs/MigrationGuide.md
engine/common/components-tests/src/test/scala/pl/touk/nussknacker/engine/common/components/DecisionTableSpec.scala
engine/common/components/src/main/scala/pl/touk/nussknacker/engine/common/components/DecisionTable.scala
scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala

[NU-1607] Decision Table component field rename: "Filter expression" -> "Match condition"

---

docs/integration/MachineLearning.md
docs/scenarios_authoring/Enrichers.md

[NU-1484] Improve Machine Learning docs

---

version.sbt

Bump version to "1.16.0-SNAPSHOT"

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/Utils.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/UtilsSpec.scala

Gracefully stop deployment actors (and wait for free names) on PeriodicDeploymentManager close()

---

designer/client/src/components/modals/CustomActionDialog.tsx
designer/client/src/http/HttpService.ts
designer/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/ProcessChangeEvent.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/CustomActionRequest.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ScenarioCommand.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DeploymentComment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/CustomActionValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentCommentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesConcurrentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/CustomActionValidatorTest.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala

1. Add (temporary) deploy and cancel action definitions ~with deployment comment validators~
2. ~Remove old DeploymentComment validation~
3. Use common steps for deploy, cancel and custom actions with action parameters validation
4. rename OnDeployAction... -> OnAction...
5. custom action panel with "comment" field with validation
Next steps:
rename CustomAction -> ScenarioAction
align ActionDefinition with ScenarioPropertyConfig (maybe rename ScenarioPropertyConfig -> ScenarioPropertyDefinition)
align ScenarioPropertyValidator with CustomActionValidator
??? move deploy/cancel action definitions to deployment manager
use the same form for deploy/cancel/custom actions

Use common steps for deploy, cancel and custom actions.

---

designer/client/src/components/modals/CustomActionDialog.tsx
designer/client/src/http/HttpService.ts
designer/listener-api/src/main/scala/pl/touk/nussknacker/ui/listener/ProcessChangeEvent.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/CustomActionRequest.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ScenarioCommand.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DeploymentComment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/CustomActionValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesConcurrentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesChangeListenerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/CustomActionValidatorTest.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala

Use common steps for deploy, cancel and custom actions. (#5798)

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/component/AdditionalUIConfigProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/NewProcessPreparer.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/ScenarioPropertiesValidator.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/validation/UIProcessValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/mock/TestAdditionalUIConfigProviderFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ProcessTestData.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/TestFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/NewProcessPreparerSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/ScenarioPropertiesValidatorTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala

[Nu-1594] Use ScenarioPropertiesConfigFinalizer in NewProcessPreparer and ScenarioPropertiesValidatior

---

build.sbt
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/MigrationApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/TapirCodecs.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/MigrationApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/utils/ApiVersion.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/migrations/MigrateScenarioData.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/migrations/MigrationApiAdapterService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/migrations/MigrationApiAdapters.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/migrations/MigrationService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/migrate/RemoteEnvironment.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/util/ApiAdapter.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/util/ApiAdapterService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/util/VersionedData.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ReflectionBasedUtils.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/migration/MigrationUtils.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/MigrationApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/MigrationApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NuDesignerApiAvailableToExposeYamlSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/description/MigrationApiEndpointsSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/migrate/StandardRemoteEnvironmentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/util/ApiAdapterServiceSpec.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md

* Adds API versioning for migrations between environments, general ApiAdapter trait which may be reused in other APIs for versioning purposes.
---------

Cherry pick Migration API Versioning to release 1.15

---

defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/DefaultConfigCreator.scala
docs/Changelog.md
docs/scenarios_authoring/Spel.md
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/conversion.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/geo.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/numeric.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/random.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/util.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/RandomSpec.scala

[NU-1646] Add RANDOM helper

---

utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/random.scala

[NU-1646] Fix docs generation

---

docs/Changelog.md
engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/TestWithTestDataSpec.scala
engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaSourceImplFactory.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/parameters/TestingParametersSupport.scala
utils/components-utils/src/test/scala/pl/touk/nussknacker/engine/util/parameters/TestingParametersSupportTest.scala

[NU-1648] Fix ad hoc tests with schemas containing nested fields

---

defaultModel/src/main/scala/pl/touk/nussknacker/defaultmodel/DefaultConfigCreator.scala
docs/Changelog.md
docs/scenarios_authoring/Spel.md
engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
engine/flink/schemed-kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/schemedkafka/source/flink/TestWithTestDataSpec.scala
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
engine/lite/components/kafka/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaSourceImplFactory.scala
utils/components-utils/src/main/scala/pl/touk/nussknacker/engine/util/parameters/TestingParametersSupport.scala
utils/components-utils/src/test/scala/pl/touk/nussknacker/engine/util/parameters/TestingParametersSupportTest.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/conversion.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/geo.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/numeric.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/random.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/util.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/RandomSpec.scala

Cherry pick random helper and adhoc tests fix to 1.15

---

PRIVACY_POLICY.md
README.md

- Privacy Policy file added.
- Link to Privacy Policy added to README.

Privacy Policy added

---

designer/client/src/components/graph/node-modal/editors/expression/CustomAceEditorCompleter.tsx
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggest.tsx
designer/client/src/components/graph/node-modal/editors/expression/ExpressionSuggester.ts

[NU-1092] fixed ExpressionSuggester

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/AppApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ComponentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ComponentApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceDeploymentCommentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DictApiHttpServiceSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/MigrationApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/MigrationApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NodesApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NodesApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NotificationApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NotificationApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/NuDesignerApiSwaggerUISpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ScenarioActivityApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ScenarioActivityApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ScenarioParametersApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ScenarioParametersApiHttpServiceSecuritySpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/UserApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/UserApiHttpServiceCategoryUsedMoreThanOnceConfigSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/UserApiHttpServiceOAuth2Spec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/UserApiHttpServiceSecuritySpec.scala
utils/test-utils/src/main/scala/pl/touk/nussknacker/test/RestAssuredVerboseLogging.scala
utils/test-utils/src/main/scala/pl/touk/nussknacker/test/RestAssuredVerboseLoggingIfValidationFails.scala

[MAINTENANCE] Adjust designer IT tests logging

---

designer/client/src/components/MenuBar/menu.tsx

one more menu flicker fix

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/QuestDbFEStatisticsRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpServiceBusinessSpec.scala

[NU-1520] QuestDB recover tests

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpServiceBusinessSpec.scala

[NU-1520] Temporary ignore statistic recover test

---

docs/MigrationGuide.md

[NU-1643] migration guide: link fix

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DMScenarioCommand.scala
designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentUpdateStrategy.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ScenarioCommand.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/DeploymentService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/notifications/NotificationServiceTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/deployment/DeploymentServiceSpec.scala
docs/MigrationGuide.md
engine/development/deploymentManager/src/main/scala/pl/touk/nussknacker/development/manager/DevelopmentDeploymentManagerProvider.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManagerTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingDeploymentManagerSlotsCountSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingDeploymentManagerSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/JavaConfigDeploymentManagerSpec.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/StreamingDockerTest.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkDeploymentManager.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/FlinkRestManagerSpec.scala
engine/lite/embeddedDeploymentManager/src/main/scala/pl/touk/nussknacker/engine/embedded/EmbeddedDeploymentManager.scala
engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/BaseStreamingEmbeddedDeploymentManagerTest.scala
engine/lite/embeddedDeploymentManager/src/test/scala/pl/touk/nussknacker/streaming/embedded/RequestResponseEmbeddedDeploymentManagerTest.scala
engine/lite/k8sDeploymentManager/src/main/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManager.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/BaseK8sDeploymentManagerTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerKafkaTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala

Explicitly named current strategy (ReplaceDeploymentWithSameScenarioName), explicitly named StateRestoringStrategy (was Option before)

[NU-1639] DeploymentUpdateStrategy introduced

---

.run/NussknackerApp-dist-config.run.xml

Fix: Run NussknackerApp-dist-config.run.xml

---

docs/installation_configuration_guide/ScenarioDeploymentConfiguration.md
examples/installation/README.md
examples/installation/clean.sh
examples/installation/designer/application-customizations.conf
examples/installation/docker-compose.yml
examples/installation/flink/Dockerfile
examples/installation/flink/flink-properties.yml
examples/installation/grafana/dashboards/dashboards.yml
examples/installation/grafana/dashboards/nussknacker-lite-scenario.json
examples/installation/grafana/dashboards/nussknacker-request-response-scenario.json
examples/installation/grafana/dashboards/nussknacker-scenario.json
examples/installation/grafana/datasources/datasources.yml
examples/installation/nginx/additional/akhq.conf
examples/installation/nginx/additional/flink.conf
examples/installation/nginx/nginx.conf
examples/installation/run.sh
examples/installation/telegraf/telegraf.conf

* it's cherrypicked from staging (ref: https://github.com/TouK/nussknacker/pull/6069)

[NU-1616] NU installation example 

---

engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/async/DefaultServiceExecutionContextPreparer.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/process/AsyncExecutionContextPreparer.scala

Add tickets mechanism for AsyncExecutionContext

---

engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala

Close async poll only in hook

---

designer/client/src/components/MenuBar/menu.tsx

[NU-1655] change top menu style

---

designer/client/cypress/support/process.ts
designer/client/src/components/graph/node-modal/MarkdownStyled.tsx

normal links:
```
[normal link](href)
```
router links:
```
:router-link[router link]{to=/path}
```

add router-link directive in markdown

---

designer/client/src/actions/nk/assignSettings.ts
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/SettingsResourcesSpec.scala
docs/Changelog.md

Fix statistics configuration

---

designer/client/src/actions/nk/assignSettings.ts
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/SettingsResources.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtype/ProcessingTypeDataReader.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/SettingsResourcesSpec.scala
docs/Changelog.md
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkEngineRuntimeContextImpl.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/FlinkProcessCompilerData.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/MetricsProviderForFlink.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/FlinkProcessRegistrar.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/SourceMetricsFunction.scala

1.15.1 statistics and adhoc test fix

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DBFetchingProcessRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessActionRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/ProcessDBQueryRepository.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/base/it/WithAccessControlCheckingConfigScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ProcessesResourcesSpec.scala
docs/Changelog.md

(cherry picked from commit 41325b59ebdd1dca50b047631f7131f181c2e4ac)

Fix last action data determining (forwardport from #6134)

---

docs/installation_configuration_guide/model/Flink.md

Fix aggregate window offset configuration doc

---

docs/installation_configuration_guide/model/Flink.md

Merge release to staging - doc fix

---

scenario-api/src/main/scala/pl/touk/nussknacker/engine/spel/Implicits.scala

[MAINTENANCE] Remove deprecated annotation

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesBatchBusinessSpec.scala
engine/flink/components/dev-table/src/main/scala/pl/touk/nussknacker/engine/flink/table/source/TableSource.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/TestFlinkProcessCompilerDataFactory.scala

Ad hoc test support for Table Source

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/synchronize/DeploymentsStatusesSynchronizer.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceDeploymentCommentSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/process/newdeployment/DeploymentRepositorySpec.scala

Temporary disable Deployment api flaky tests

---

engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessService.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/PeriodicProcessDeployment.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/model/SchedulesState.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicProcessServiceTest.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/db/InMemPeriodicProcessesRepository.scala

Fix periodic scenarios that are Running being shown as Scheduled

---

.github/workflows/pr.yml

Simpler cross build: two phases merged

---

docs/Changelog.md
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/CachedFlinkClient.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/rest/CachedFlinkClientTest.scala

Flink cache config fix

---

docs/Changelog.md
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/CachedFlinkClient.scala
engine/flink/management/src/test/scala/pl/touk/nussknacker/engine/management/rest/CachedFlinkClientTest.scala

Release 1.15 port

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/DeploymentRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/DeploymentService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/BaseDeploymentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceDeploymentCommentSpec.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/runner/FlinkProcessMain.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/FlinkRestManager.scala
engine/flink/management/src/main/scala/pl/touk/nussknacker/engine/management/rest/HttpFlinkClient.scala
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/docker/WithFlinkContainers.scala

Deployment api unignore + additional logging 

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/NoOpFEStatisticsRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/NopFEStatisticsRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbConfig.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbExtensions.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbFEStatisticsRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/factory/NussknackerAppFactory.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbConfigSpec.scala

[NU-1520] Add statistics configuration

---

designer/client/src/components/graph/node-modal/editors/expression/DictParameterEditor/DictParameterEditor.tsx
docs/Changelog.md

Before:
https://github.com/TouK/nussknacker/assets/9945753/61730505-2b4b-49bf-ba2a-24fe69435c08
After:
https://github.com/TouK/nussknacker/assets/9945753/39c39242-b5c4-4483-9953-38052232a50a

[NU-1714] fix-problem-with-parsing-object-in-fragment-input-parameter

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/FlushDataTask.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbExtensions.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbFEStatisticsRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/RetentionTask.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/TaskRecovery.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/StatisticsApiHttpServiceBusinessSpec.scala

Nu.1520.flush.data.on.close.and.compact.data.in.statistics.db

---

engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/AsyncInterpretationFunction.scala

Cherrypick of (#6109) with fixup to changes already merged to staging in #6055

[NU-1657] Additional fixup to DefaultAsyncExecutionContextPreparer

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/DeploymentApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newdeployment/DeploymentService.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/base/it/WithBatchConfigScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/BaseDeploymentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/DeploymentApiHttpServiceBusinessSpec.scala
docs/Changelog.md

[NU-1687] Blocking of deployment of either fragment or archived scenario

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/component/ComponentsValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/Validations.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/DynamicNodeValidator.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/StandardParameterEnrichment.scala

Dynamic components properly use validators from AdditionalUIConfigProvider

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/component/ComponentService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/component/ComponentsValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/Validations.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/DynamicNodeValidator.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/StandardParameterEnrichment.scala

Dynamic components use validators from AdditionalUIConfigProvider

---

designer/client/src/http/HttpService.ts
designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/DeploymentComment.scala
extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessAction.scala

[NU-6254] Add action name prefix to custom action comment

---

designer/client/src/components/toolbarSettings/buttons/ActionButton.tsx
designer/client/src/reducers/selectors/graph.ts

Disable custom action button for periodic engine.

---

docs/scenarios_authoring/Spel.md

[MAINTENANCE] Enhance type conversion docs

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/suggester/ExpressionSuggesterBenchmarkSetup.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/NodesApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/suggester/ExpressionSuggester.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ExpressionSuggesterSpec.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSuggester.scala
utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/CaretPosition2d.scala

* Restrict SpEL expression based on caret position
---------

[NU-6301] Restrict SpEL expression based on caret position (#6302)

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/migrations/MigrationService.scala
docs/Changelog.md

Fix migration between environments

---

build.sbt

[NU-1728] Remove redundant deps of table jar

---

docs/installation_configuration_guide/model/ModelConfiguration.md

Enhance component group mapping configuration docs

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/migrations/MigrationService.scala
designer/server/src/test/resources/config/business-cases/category-used-more-than-once-designer.conf
designer/server/src/test/scala/pl/touk/nussknacker/test/base/it/WithCategoryUsedMoreThanOnceConfigScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/config/WithCategoryUsedMoreThanOnceDesignerConfig.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/config/WithDesignerConfig.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ScenarioHelper.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/MigrationApiHttpServiceBusinessSpec.scala
utils/test-utils/src/main/scala/pl/touk/nussknacker/test/StandardPatientScalaFutures.scala

[MAINTENANCE] Enhance scenario migration tests

---

designer/client/src/components/toolbarComponents/toolbarButtons/ToolbarButtonStyled.tsx

quickfix for LinkButton/ToolbarButton icon in safari

---

README.md

[NU-1727] readme changed related to the new quickstart

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ExpressionSuggesterSpec.scala
docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSuggester.scala

* improve expression suggester
* add changelog
---------

Improve spel expression suggestions V2

---

docs/Changelog.md
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/PeriodicDeploymentManager.scala
engine/flink/management/periodic/src/main/scala/pl/touk/nussknacker/engine/management/periodic/Utils.scala
engine/flink/management/periodic/src/test/scala/pl/touk/nussknacker/engine/management/periodic/UtilsSpec.scala

(cherry picked from commit 9be719fcd3af4d8fe744dec4a91dfc019636cddc)

Stop deployment and reschedule actors less gracefully on reload (backport of #6314)

---

designer/client/src/components/graph/node-modal/properties.tsx

This change fixes a failing cypress `JsonEditor` test that started to fail after https://github.com/TouK/nussknacker/pull/6398 changes

Modify property label form title to fix failing cypress test

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/typing.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
docs/Changelog.md
docs/MigrationGuide.md
engine/lite/components/kafka-tests/src/test/scala/pl/touk/nussknacker/engine/lite/components/LiteKafkaUniversalAvroSchemaFunctionalTest.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/compile/GenericTransformationValidationSpec.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/TyperSpec.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/BaseSpelSpec.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/CollectionUtilsSpec.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/AvroSchemaOutputValidator.scala

backport of https://github.com/TouK/nussknacker/pull/6269

Fix TypingResult.valueOpt for the purpose of SpEL validator (backport of #6269)

---

designer/client/src/components/graph/node-modal/NodeTypeDetailsContent.tsx
designer/client/src/components/graph/node-modal/ParameterExpressionField.tsx
designer/client/src/components/graph/node-modal/customNode.tsx
designer/client/src/components/graph/node-modal/joinNode.tsx
designer/client/src/components/graph/node-modal/parametersList.tsx

added FieldWrapper in ParameterExpressionField

---

build.sbt
docs/Changelog.md
engine/flink/components/base-unbounded/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/aggregate/AggregatorFunction.scala

Improvement: Remove using flink-metrics-dropwizard at flink-components-utils

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ProcessesResources.scala
docs/Changelog.md
docs/MigrationGuide.md

[MAINTENANCE] Remove deprecated create process API

---

e2e-tests/src/test/scala/pl/touk/nussknacker/DockerBasedInstallationExampleNuEnvironment.scala

Increase e2e tests startup timeout

---

engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sDeploymentManagerReqRespTest.scala
engine/lite/k8sDeploymentManager/src/test/scala/pl/touk/nussknacker/k8s/manager/K8sTestUtils.scala

K8s flaky test fix attempt

---

designer/server/src/main/scala/db/migration/V1_054__FragmentAddComponentGroupProperty.scala
designer/server/src/test/scala/db/migration/V1_054__FragmentAddComponentGroupPropertyMigrationSpec.scala

componentGroup migration fix: don't apply for non-fragments

---

docs/MigrationGuide.md
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/DockerTest.scala
engine/flink/management/src/it/scala/pl/touk/nussknacker/engine/management/streaming/FlinkStreamingProcessTestRunnerSpec.scala
utils/test-utils/src/main/scala/pl/touk/nussknacker/test/WithConfig.scala

Improvement: Load resource config only in test context

---

docs/configuration/Common.md

Docs link fix

---

docs/Changelog.md
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/join/TableJoinTest.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/join/TableJoinComponent.scala

Nu 1679 table join improvements

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/QuestDbFEStatisticsRepository.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/db/timeseries/questdb/RetentionTask.scala

[MAINTENANCE] Statistics retention enhancements

---

designer/server/src/test/scala/pl/touk/nussknacker/ui/api/BaseDeploymentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ManagementResourcesBatchBusinessSpec.scala
docs/Changelog.md
engine/flink/components/base-tests/src/test/resources/tables-definition-table-sink-parameters-test.sql
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/TableTestCases.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/extractor/TableExtractorTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/sink/TableFileSinkTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/sink/TableSinkParametersTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/source/TableSourceDataGenerationTest.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/sink/TableSinkFactory.scala
engine/flink/tests/src/test/scala/pl/touk/nussknacker/devmodel/TableKafkaPingPongTest.scala

[NU-1750] Add non-raw editor for Table Source

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/ConfigParameterDefaultValueDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/EditorBasedLanguageDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/OptionalityBasedDefaultValueDeterminer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/defaults/TypeRelatedParameterValueDeterminer.scala

* language of parameter's expression is based on editor type
* fixes after review
---------

language of parameter's expression is based on editor type (#6524)

---

docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/Interpreter.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/InterpreterSpec.scala

Backport https://github.com/TouK/nussknacker/commit/03082093e114cc0b77195af6ea3738489154a1a8 to 1.16 for esp

Fix processing fragment output in interpreter

---

designer/server/src/test/resources/config/business-cases/batch-designer.conf
docs/Changelog.md
docs/MigrationGuide.md
docs/configuration/model/Flink.md
e2e-tests/src/test/resources/spec-setup/batch-config/batch-customizations.conf
engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/util/source/CollectionSource.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/TestTableComponents.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/aggregate/TableAggregationTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/join/TableJoinTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/sink/TableFileSinkTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/sink/TableSinkParametersTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/source/TableSourceDataGenerationTest.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/FlinkTableComponentProvider.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/source/TableSource.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/source/TableSourceFactory.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/FlinkJobConfig.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/compiler/TestFlinkProcessCompilerDataFactory.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/registrar/StreamExecutionEnvPreparer.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/compiler/StubbedFlinkProcessCompilerDataFactoryTest.scala
engine/flink/tests/src/test/scala/pl/touk/nussknacker/devmodel/TableKafkaPingPongTest.scala
nussknacker-dist/src/universal/conf/dev-application.conf
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/FlinkTestScenarioRunner.scala

[NU-1570] Move Flink's Runtime Execution Mode to model level config

---

docs/configuration/Common.mdx
docs/configuration/DesignerConfiguration.md
docs/configuration/ScenarioDeploymentConfiguration.md
docs/configuration/index.mdx
docs/configuration/model/ModelConfiguration.md
docs/configuration/model/index.mdx
docs/developers_guide/index.mdx
docs/installation/index.mdx
docs/integration/OpenAPI.md
docs/integration/Sql.md
docs/integration/index.mdx
docs/operations_guide/index.mdx
docs/scenarios_authoring/Enrichers.md
docs/scenarios_authoring/index.mdx

1.16 docs adjustments to docusaurus 3

---

docs/configuration/model/ModelConfiguration.mdx
docs/installation/Binaries.md
docs/installation/Docker.md

More changes related to docs and docusaurus 3 and 1.16 release

---

docs/configuration/Common.mdx
docs/configuration/DesignerConfiguration.md

docusaurus 3 release 1.16 fix-errors

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/server/AkkaHttpBasedRouteProvider.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/Encryption.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/StatisticError.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/StatisticUrlConfig.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/Statistics.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/EncryptionSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/StatisticsSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsServiceTest.scala

some adjustments

---

docs/installation/index.mdx
docs/integration/Sql.md

docusaurus 3 fixes

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/ValueDecoder.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/typed/ValueEncoder.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultDecoderSpec.scala
components-api/src/test/scala/pl/touk/nussknacker/engine/api/typed/TypingResultGen.scala
docs/Changelog.md

Add encode/decode support for java.time.* values

---

docs/MigrationGuide.md
engine/flink/components-api/src/main/scala/pl/touk/nussknacker/engine/flink/api/process/FlinkSink.scala
engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/util/sink/EmptySink.scala
engine/flink/components-utils/src/main/scala/pl/touk/nussknacker/engine/flink/util/sink/SingleValueSinkFactory.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/functional/FlinkSinkSpec.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/helpers/ProcessTestHelpers.scala
engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/sink/flink/FlinkKafkaSink.scala
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/process/helpers/SampleNodes.scala
utils/flink-components-testkit/src/main/scala/pl/touk/nussknacker/engine/flink/util/test/TestResultSinkFactory.scala

[Nu-6588] Add flink node context as parameter to BasicFlinkSink

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterValidator.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/validator/ValidationExpressionParameterValidator.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/definition/component/parameter/validator/ValidationExpressionParameterValidatoTest.scala

ValidationExpressionParameterValidator fails if expression is not compile-time evaluable

---

docs/Changelog.md
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/aggregate/TableAggregationTest.scala
engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/join/TableJoinTest.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/aggregate/TableAggregation.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/join/TableJoinComponent.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/utils/BestEffortTableTypeEncoder.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/utils/RowConversions.scala

Table types alignment in other places than sink value

---

designer/client/src/http/HttpService.ts
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/component/ComponentApiEndpoints.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ComponentApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/definition/component/ComponentService.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ComponentApiHttpServiceBusinessSpec.scala
designer/server/src/test/scala/pl/touk/nussknacker/ui/definition/component/DefaultComponentServiceSpec.scala
designer/submodules/packages/components/src/components/useComponentsQuery.tsx
docs-internal/api/nu-designer-openapi.yaml

`/components` endpoint new  `skipFragments` param

---

build.sbt
engine/flink/metrics-deferred-reporter/src/main/java/pl/touk/nussknacker/engine/flink/metrics/MetricRemovalDeferredToNextReportMetricReporter.java
engine/flink/metrics-deferred-reporter/src/main/java/pl/touk/nussknacker/engine/flink/metrics/MetricRemovalDeferredToNextReportMetricReporterFactory.java
engine/flink/metrics-deferred-reporter/src/main/resources/META-INF/services/org.apache.flink.metrics.reporter.MetricReporterFactory

[NU-1677] metrics reporter workaround

---

benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/spel/SpelBenchmarkSetup.scala
benchmarks/src/test/scala/pl/touk/nussknacker/engine/benchmarks/spel/SpelSecurityBenchmarkSetup.scala
build.sbt
designer/server/src/test/scala/pl/touk/nussknacker/ui/validation/UIProcessValidatorSpec.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/ExpressionCompiler.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompilerData.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/DynamicNodeValidator.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeCompiler.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/NodeDataValidator.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/component/parameter/validator/ValidationExpressionParameterValidator.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/expression/ExpressionEvaluator.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/testmode/TestDataPreparer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/definition/component/parameter/validator/ValidationExpressionParameterValidatorTest.scala

Global variables (helpers) and `#meta` in `ValidationExpressionParameterValidator`

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/ProcessCompiler.scala

`unOptimizedEvaluator` in `ProcessValidator` (missing commit from #6648)

---

build.sbt

Doc compilation fixup

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/NodeValidationExceptionHandler.scala

Makes this log useful. Currently it's really hard to find error source because logged exception looks like this:
```
11:38:41.737 [nussknacker-designer-akka.actor.default-dispatcher-7] ERROR p.t.n.e.c.NodeValidationExceptionHandler$ - Exception during validation handling
java.lang.IllegalArgumentException: SQL error: ORA-00942: table or view does not exist
at org.my.company.process.batchmode.sql.SqlDataRetrieverFactory$.org$my$company$process$batchmode$sql$SqlDataRetrieverFactory$$getFieldsWithTypes(SqlDataRetrieverFactory.scala:117)
at org.my.company.process.batchmode.sql.SqlDataRetrieverFactory.fieldsWithTypes$lzycompute(SqlDataRetrieverFactory.scala:143)
at org.my.company.process.batchmode.sql.SqlDataRetrieverFactory.fieldsWithTypes(SqlDataRetrieverFactory.scala:143)
at …
```

Add source node to failure logs

---

docs/Changelog.md
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/CollectionUtilsSpec.scala

[NU-1489] Fix COLLECTION merge function

---

designer/client/src/components/graph/utils/fragmentSchemaAligner.ts

[Nu-1792] properties save fix when fragment is in different group than fragments

---

designer/client/src/components/graph/node-modal/node/NodeDetails.tsx
designer/submodules/packages/components/src/components/cellRenderers/nameCell.tsx

- fix an issue with the properties update
- Resolve problem with logging
- Resolve fragment detection in components

[Nu-1794] fix problem with properties fields update

---

designer/client/src/components/graph/node-modal/node/NodeDetails.tsx
designer/client/src/components/graph/utils/fragmentSchemaAligner.ts
designer/submodules/packages/components/src/components/cellRenderers/nameCell.tsx

Fe release 1.17 staging synchronization

---

docs/Changelog.md
engine/flink/management/dev-model/src/test/resources/extractedTypes/devCreator.json
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/collection.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/CollectionUtilsSpec.scala

[NU-1791] Add varargs to concat and merge helper functions

---

designer/client/src/reducers/panel.ts
designer/client/src/reducers/selectors/panel.ts

collapsed panels fixed

---

designer/client/src/components/graph/node-modal/editors/expression/CustomAceEditorCompleter.tsx
docs/Changelog.md
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

[NU-1656] Check for methods if property does not exist

---

engine/flink/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/sink/flink/FlinkKafkaUniversalSink.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/universal/ParsedSchemaSupport.scala
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/schemaregistry/universal/UniversalSchemaSupport.scala

Optimize serializer creation in UniversalSchemaSupport

---

docs/Changelog.md

[NU-1700] Highlights moved to changelog

---

docs/Changelog.md

[NU-1700] changelog improvements cherry-pick from release/1.17

---

docs/Changelog.md

[NU-1700] changelog formatting fix

---

docs/Changelog.md
engine/flink/tests/src/test/resources/extractedTypes/defaultModel.json
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
utils/default-helpers/src/main/scala/pl/touk/nussknacker/engine/util/functions/conversion.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/BaseSpelSpec.scala
utils/default-helpers/src/test/scala/pl/touk/nussknacker/engine/util/functions/ConversionUtilsSpec.scala

[NU-1701] Add conversions to primitive types to helper functions

---

designer/client/federation.config.json

Expose NuThemeProvider using module federation mechanism

---

defaultModel/src/main/resources/defaultModelConfig.conf
engine/flink/components/base/src/main/scala/pl/touk/nussknacker/engine/flink/util/transformer/FlinkBaseComponentProvider.scala
engine/lite/components/base/src/main/scala/pl/touk/nussknacker/engine/lite/components/LiteBaseComponentProvider.scala

Docs links fixed for fragment output and decision table

---

designer/client/src/components/graph/node-modal/editors/expression/Cron/CronEditor.tsx
designer/client/src/components/graph/node-modal/editors/expression/Duration/TimeRangeComponent.tsx

(cherry picked from commit a8f548430fdeeffb700bc8705b087b39e9e01079)

[NU-1804] TimeRangeComponent border issue

---

.github/workflows/benchmark-e2e.yml
.github/workflows/benchmark-jmh.yml
benchmarks/Readme.md

benchmark pipeline fix

---

docs/Changelog.md
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/ToAvroSchemaBasedEncoder.scala

Faster serialization of Avro unions

---

docs/Changelog.md
utils/schemed-kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/schemedkafka/encode/ToAvroSchemaBasedEncoder.scala

Faster avro nulls (backport to 1.17)

---

docs/Changelog.md

Release1.17 to staging merge

---

build.sbt
engine/flink/executor/src/main/java/pl/touk/nussknacker/engine/process/util/TimeSerializers.java
engine/flink/scala-utils/src/main/java/pl/touk/nussknacker/engine/flink/api/typeinfo/caseclass/ScalaCaseClassSerializerSnapshot.java
engine/flink/scala-utils/src/main/java/pl/touk/nussknacker/engine/flink/api/typeinfo/option/ScalaOptionSerializerSnapshot.java
utils/kafka-test-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/EmbeddedKafkaServer.scala

No changelog entry, this is a change that should have been done in #6805

Update commons-io to version from Flink 1.19

---

examples/dev/local-testing.docker-compose.yml

[NU-1790] Bump flink version in example

---

engine/flink/components/base-tests/src/test/scala/pl/touk/nussknacker/engine/flink/table/aggregate/TableAggregationTest.scala
engine/flink/components/table/src/main/scala/pl/touk/nussknacker/engine/flink/table/aggregate/TableAggregator.scala
engine/flink/test-utils/src/main/scala/pl/touk/nussknacker/engine/flink/test/FlinkTestConfiguration.scala
utils/utils/src/main/scala/pl/touk/nussknacker/engine/util/json/ToJsonEncoder.scala

[NU-1763] Add Collect aggregation 

---

designer/client/src/components/graph/node-modal/NodeDetailsContent/NodeTableStyled.tsx

[NU-1816] fixing checkbox style on firefox

---

build.sbt
docs/Changelog.md

Updates to version with mitigation for CVE-2024-47561

Avro 1.11.3 -> 1.11.4

---

build.sbt
docs/Changelog.md

Upgrade swagger parser to 2.1.15 -> 2.1.22

---

designer/client/src/components/graph/node-modal/fragment-input-definition/settings/variants/fields/UserDefinedListInput.tsx

…st (#7017)
* [NU-7016] Add new button
* [NU-7016] Use i18n
---------

Cherry pick NU-7016 to esp preview branch

---

build.sbt
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/BaseEndpointDefinitions.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/TestingApiHttpService.scala
designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/TestingApiEndpoints.scala
docs-internal/api/nu-designer-openapi.yaml
docs/Changelog.md
security/src/main/scala/pl/touk/nussknacker/ui/security/api/AuthManager.scala
security/src/main/scala/pl/touk/nussknacker/ui/security/api/SecurityError.scala

Upgrade tapir / openapiCirceYaml versions

---

docs/configuration/index.mdx

fixed the problem

---

docs/configuration/index.mdx

The same stuff as [this PR.](https://github.com/TouK/nussknacker/pull/7047)

Fix docs with rich text code

---

docs/configuration/Common.mdx

The same stuff as https://github.com/TouK/nussknacker/pull/7047

Fix docs with rich text code 1.16

---

docs/installation_configuration_guide/Common.md

The same stuff as https://github.com/TouK/nussknacker/pull/7047

Fix docs with rich text code 1.14

---

designer/server/src/main/resources/defaultDesignerConfig.conf

Improvement: Restore HikariCP metrics

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/scenarioActivity/Dtos.scala
docs-internal/api/nu-designer-openapi.yaml

[NU-1778] Fix OutgoingMigration supported actions

---

designer/deployment-manager-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/DeploymentManager.scala
docs/MigrationGuide.md

[NU-1772] DeploymentManager activity handling default value and migration guide

---

docs/Changelog.md
docs/MigrationGuide.md

[NU-1790] Update docs after Flink 1.19 bump

---

docs/MigrationGuide.md

Add missing migration info about TimeMeasuringService

---

designer/server/src/main/scala/pl/touk/nussknacker/ui/process/repository/activities/DbScenarioActivityRepository.scala

[NU-1772] Fix DB serialization for AutomaticUpdate

---

designer/server/src/test/scala/pl/touk/nussknacker/test/base/it/NuResourcesTest.scala
designer/server/src/test/scala/pl/touk/nussknacker/test/utils/domain/ScenarioHelper.scala

[Tech] Workaround for flaky tests

---

designer/client/cypress/e2e/fragment.cy.ts

flaky cypress test fix

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

Validate indexer expression on Unknown and on non-map non-list TypedClass

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/extension/ExtensionMethods.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/Typer.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/internal/OptimizedEvaluationContext.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/spel/internal/propertyAccessors.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/TyperSpec.scala

[NU-1836] Handle extension methods in PropertyAccessors

---

docs/Changelog.md

1.18 release highlights

---

designer/client/cypress/e2e/activities.cy.ts
designer/client/src/components/modals/ModifyActivityCommentDialog.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItem.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItemComment.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItemCommentModify.tsx
designer/client/src/components/toolbars/activities/ActivityPanelRowItem/ActivityItemHeader.tsx
designer/client/src/components/toolbars/activities/helpers/extendActivitiesWithUIData.ts
designer/client/src/components/toolbars/activities/types.ts
designer/client/src/components/toolbars/activities/useActivitiesSearch.test.ts
designer/client/src/windowManager/ContentGetter.tsx
designer/client/src/windowManager/WindowKind.tsx
docs/Changelog.md
engine/flink/components-api/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinformation/FlinkTypeInfoRegistrar.scala
engine/flink/components-api/src/main/scala/pl/touk/nussknacker/engine/flink/api/typeinformation/TypeInformationDetection.scala
engine/flink/components-api/src/test/scala/pl/touk/nussknacker/engine/flink/api/typeinformation/FlinkTypeInfoRegistrarTest.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/ExecutionConfigPreparer.scala
engine/flink/executor/src/main/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetection.scala
engine/flink/executor/src/test/scala/pl/touk/nussknacker/engine/process/typeinformation/TypingResultAwareTypeInformationDetectionSpec.scala

1.18 ports 2

---

designer/client/src/actions/nk/adhocTesting.ts
designer/client/src/components/modals/AdhocTesting/useAdhocTestingParametersValidation.tsx
designer/client/src/http/HttpService.ts

Graph was not sanitized before validation request

Fix adhoc validation request with sanitizeScenarioGraph

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/language/dictWithLabel/DictKeyWithLabelExpressionParser.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/language/dictWithLabel/DictKeyWithLabelExpressionParserTest.scala

Cherry pick lifting type result information to 1.17-esp

---

scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/extension/ToMapConversionExt.scala
scenario-compiler/src/test/scala/pl/touk/nussknacker/engine/spel/SpelExpressionSpec.scala

[NU-1846] List of Unkownn toMap conversion fix

---

components-api/src/main/scala/pl/touk/nussknacker/engine/api/context/ProcessCompilationError.scala
designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/validation/PrettyValidationErrors.scala
scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/compile/nodecompilation/ValueEditorValidator.scala

Fragment input fields: better error message for situation when required field has an empty list of possible values

---

designer/client/src/components/graph/node-modal/node/HeaderWithGlobalCursor.tsx
designer/client/src/components/graph/node-modal/node/StyledHeader.tsx

Optimize CSS selector for cursor dragging

---

build.sbt
docs/Changelog.md

Updated Swagger Parser, removed shading workaround added in previous update

Update Swagger dependencies

---

designer/client/src/components/graph/node-modal/node/HeaderWithGlobalCursor.tsx
designer/client/src/components/graph/node-modal/node/StyledHeader.tsx
docs/Changelog.md

[Nu-7284] Optimize CSS selector related to cursor type

---

build.sbt
designer/client/package-lock.json
designer/client/package.json
designer/client/src/components/graph/node-modal/node/HeaderWithGlobalCursor.tsx
designer/client/src/components/graph/node-modal/node/StyledHeader.tsx
docs/Changelog.md

1.18 ports11
